import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { classifyNativeSourcePath, computeNativeSourceIdentity } from "../scripts/windows_native_source_identity";

const roots: string[] = [];

function fixture(): string {
  const root = mkdtempSync(path.join(tmpdir(), "dca-native-identity-"));
  roots.push(root);
  const files: Record<string, string> = {
    "apps/desktop/src/app/App.tsx": "export const App = () => null;\n",
    "apps/desktop/src-tauri/src/lib.rs": "pub fn run() {}\n",
    "apps/desktop/src-tauri/Cargo.lock": "cargo-lock-v1\n",
    "apps/desktop/src-tauri/gen/schemas/desktop-schema.json": "generated-schema\n",
    "apps/desktop/src-tauri/tauri.conf.json": "{\"version\":1}\n",
    "package-lock.json": "{\"lockfileVersion\":3}\n",
    "services/runtime.ts": "export const runtime = true;\n",
    "tsconfig.app.tsbuildinfo": "generated-a\n",
    "tsconfig.node.tsbuildinfo": "generated-b\n"
  };
  for (const [relativePath, value] of Object.entries(files)) {
    mkdirSync(path.dirname(path.join(root, relativePath)), { recursive: true });
    writeFileSync(path.join(root, relativePath), value);
  }
  return root;
}

function mutate(root: string, relativePath: string): void {
  const absolute = path.join(root, relativePath);
  mkdirSync(path.dirname(absolute), { recursive: true });
  writeFileSync(absolute, `${readFileSync(absolute, "utf8")}changed\n`);
}

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe("normalized Windows native source identity", () => {
  for (const generated of ["tsconfig.node.tsbuildinfo", "tsconfig.app.tsbuildinfo"]) {
    it(`ignores the exact generated cache ${generated}`, () => {
      const root = fixture(); const before = computeNativeSourceIdentity(root).sha256;
      mutate(root, generated);
      expect(computeNativeSourceIdentity(root).sha256).toBe(before);
    });
  }

  it("ignores the exact Tauri schema output proven to be generated by the native build", () => {
    const root = fixture(); const before = computeNativeSourceIdentity(root).sha256;
    mutate(root, "apps/desktop/src-tauri/gen/schemas/desktop-schema.json");
    expect(computeNativeSourceIdentity(root).sha256).toBe(before);
  });

  it("does not let the Tauri schema exclusion hide adjacent files", () => {
    expect(classifyNativeSourcePath("apps/desktop/src-tauri/gen/schemas/custom.json")).toBe("AUTHORITATIVE_SOURCE");
    expect(classifyNativeSourcePath("apps/desktop/src-tauri/gen/other/desktop-schema.json")).toBe("AUTHORITATIVE_SOURCE");
  });

  for (const authoritative of [
    "services/runtime.ts",
    "apps/desktop/src/app/App.tsx",
    "apps/desktop/src-tauri/src/lib.rs",
    "package-lock.json",
    "apps/desktop/src-tauri/Cargo.lock",
    "apps/desktop/src-tauri/tauri.conf.json"
  ]) {
    it(`changes when authoritative ${authoritative} changes`, () => {
      const root = fixture(); const before = computeNativeSourceIdentity(root).sha256;
      mutate(root, authoritative);
      expect(computeNativeSourceIdentity(root).sha256).not.toBe(before);
    });
  }

  it("fails closed by treating an unknown file as authoritative", () => {
    const root = fixture(); const before = computeNativeSourceIdentity(root).sha256;
    writeFileSync(path.join(root, "unknown.future-format"), "unknown\n");
    expect(computeNativeSourceIdentity(root).sha256).not.toBe(before);
    expect(classifyNativeSourcePath("unknown.future-format")).toBe("AUTHORITATIVE_SOURCE");
  });

  it("does not let similar cache names mask arbitrary source files", () => {
    expect(classifyNativeSourcePath("src/tsconfig.node.tsbuildinfo")).toBe("AUTHORITATIVE_SOURCE");
    expect(classifyNativeSourcePath("tsconfig.node.tsbuildinfo.ts")).toBe("AUTHORITATIVE_SOURCE");
    expect(classifyNativeSourcePath("tsconfig.other.tsbuildinfo")).toBe("AUTHORITATIVE_SOURCE");
  });
});
