import React from "react";
import type { RunProjection } from "../../../../packages/event-protocol/src/index";
import type { VisualizationState } from "../../../../services/experiment-visualization/src/index";
import { CapabilityMatrix, ExperimentTimeline, FailureStack, InterventionBars, ModelComparison, ObservabilityComparison, RuntimeCards, TransitionFlow, VerificationFunnel, VisualizationBoundary } from "../components/visualization/Charts";

export function DashboardView({ state, onNavigate }: { state: VisualizationState; onNavigate: (view: string) => void }) {
  return <VisualizationBoundary state={state}>{(dashboard) => <section className="portfolio-page dashboard-page">
    <header className="portfolio-hero"><div><span className="viz-kicker">LOCAL-FIRST · EVIDENCE-GATED</span><h2>Engineering intelligence you can inspect.</h2><p>Desk Code Agent turns a repository into a bounded, observable workspace. The research phase is frozen; this dashboard presents what the sealed evidence supports—and what it does not.</p><div className="hero-actions"><button onClick={() => onNavigate("Workspace")}>Explore the workflow</button><button className="secondary" onClick={() => onNavigate("Experiments")}>View experiment evidence</button></div></div><aside><span>PRODUCT STATE</span><strong>Mutation disabled</strong><p>No current model or task class passed the product admission gate.</p><b>KEEP_MUTATION_DISABLED</b></aside></header>
    <div className="highlight-grid">{dashboard.highlights.map((item) => <article key={item.label}><strong>{item.value}</strong><span>{item.label}</span><small>{item.detail}</small></article>)}</div>
    <div className="chart-grid"><ObservabilityComparison chart={dashboard.charts.observability}/><CapabilityMatrix chart={dashboard.charts.capabilityMatrix}/><RuntimeCards chart={dashboard.charts.runtime}/></div>
  </section>}</VisualizationBoundary>;
}

export function CapabilitiesView({ state }: { state: VisualizationState }) {
  return <VisualizationBoundary state={state}>{(dashboard) => <section className="portfolio-page"><header className="page-intro"><span className="viz-kicker">PRODUCT ADMISSION</span><h2>Capabilities, with their claim boundaries intact.</h2><p>Routing follows measured task-class evidence and machine-checkable oracles—not model confidence.</p></header><div className="chart-grid"><CapabilityMatrix chart={dashboard.charts.capabilityMatrix}/><ModelComparison chart={dashboard.charts.modelComparison}/></div><div className="claim-boundaries"><article><b>SUPPORTED</b><strong>Structured planning</strong><p>Read-only paths and components under a machine-checkable development oracle.</p></article><article><b>ASSISTED</b><strong>Repository navigation</strong><p>Complete-context navigation at 6/12; verify before relying on the answer.</p></article><article><b>RESEARCH ONLY</b><strong>Privacy observability</strong><p>L1 diagnosis is justified as instrumentation, not mutation capability.</p></article><article className="locked"><b>DISABLED</b><strong>Autonomous mutation</strong><p>No current class or model qualifies. The UI exposes no production action.</p></article></div></section>}</VisualizationBoundary>;
}

export function ExperimentsView({ state }: { state: VisualizationState }) {
  return <VisualizationBoundary state={state}>{(dashboard) => <section className="portfolio-page"><header className="page-intro"><span className="viz-kicker">RESEARCH ARCHIVE · CANONICAL PROJECTION</span><h2>Decisions traced back to sealed evidence.</h2><p>Every chart preserves its original denominator and links to the supporting repository artifact.</p></header><div className="chart-grid"><ExperimentTimeline chart={dashboard.charts.timeline}/><ModelComparison chart={dashboard.charts.modelComparison}/><FailureStack chart={dashboard.charts.failureDecomposition}/><InterventionBars chart={dashboard.charts.interventionComparison}/><VerificationFunnel chart={dashboard.charts.verificationFunnel}/><ObservabilityComparison chart={dashboard.charts.observability}/><TransitionFlow chart={dashboard.charts.transitions}/><RuntimeCards chart={dashboard.charts.runtime}/></div></section>}</VisualizationBoundary>;
}

export function ResearchCaptureView({ state }: { state: VisualizationState }) {
  return <VisualizationBoundary state={state}>{(dashboard) => <section className="portfolio-page media-capture-page"><header className="capture-title"><div><span className="viz-kicker">SEALED RESEARCH EVIDENCE</span><h2>Capability is admitted by behavior, not appearance.</h2></div><p>Different stages answer different questions: valid structure and syntax are not strict software-repair success.</p></header><div className="capture-board"><CapabilityMatrix chart={dashboard.charts.capabilityMatrix}/><VerificationFunnel chart={dashboard.charts.verificationFunnel}/><ModelComparison chart={dashboard.charts.modelComparison}/><ObservabilityComparison chart={dashboard.charts.observability}/></div></section>}</VisualizationBoundary>;
}

export function ArchitectureEvidenceCaptureView({ state }: { state: VisualizationState }) {
  return <VisualizationBoundary state={state}>{(dashboard) => <section className="portfolio-page media-capture-page"><header className="capture-title"><div><span className="viz-kicker">EVIDENCE-GATED SYSTEM</span><h2>Privacy-safe observability without raw retention.</h2></div><p>Typed evidence moves through explicit admission gates while raw model output and edit bodies remain discarded.</p></header><div className="capture-evidence-board"><ExperimentTimeline chart={dashboard.charts.timeline}/><ObservabilityComparison chart={dashboard.charts.observability}/><TransitionFlow chart={dashboard.charts.transitions}/></div></section>}</VisualizationBoundary>;
}

export function TaskWorkflowView({ projection, onRun }: { projection: RunProjection; onRun: () => void }) {
  const stages = [
    ["01", "Repository intelligence", "Map symbols, tests, and bounded dependencies", projection.totalEvents > 0],
    ["02", "Evidence retrieval", "Package cited, task-specific context", projection.evidence.length > 0],
    ["03", "Diagnosis summary", "Separate facts, hypotheses, and unknowns", ["ANALYZING", "PLANNING", "DONE"].includes(projection.state)],
    ["04", "Bounded proposal", "Preview only; autonomous mutation is disabled", projection.events.some((event) => event.type === "patch.created")],
    ["05", "Machine verification", "Tests and trusted tools remain authoritative", projection.verification.length > 0]
  ] as const;
  return <section className="portfolio-page workflow-page"><header className="page-intro"><span className="viz-kicker">REPOSITORY → EVIDENCE → DECISION</span><h2>A calm, inspectable task workflow.</h2><p>The current trace drives every state. Demo fixtures are labeled, and unobserved verification remains NOT RUN.</p><button className="primary-inline" onClick={onRun}>Run deterministic trace</button></header><div className="workflow-layout"><div className="workflow-stages">{stages.map(([number, title, detail, active]) => <article className={active ? "observed" : ""} key={number}><b>{number}</b><span><strong>{title}</strong><small>{detail}</small></span><em>{active ? "OBSERVED" : "WAITING"}</em></article>)}</div><aside className="workflow-preview"><span className="viz-kicker">BOUNDARY PREVIEW</span><h3>{projection.currentMessage}</h3><dl><dt>Runtime state</dt><dd>{projection.state}</dd><dt>Evidence items</dt><dd>{projection.evidence.length}</dd><dt>Verification stages</dt><dd>{projection.verification.length || "NOT RUN"}</dd><dt>Mutation route</dt><dd>DISABLED</dd></dl><div className="lock-note"><b>⌁</b><span><strong>Proposal remains reversible</strong><small>Exact scope, deterministic verification, approval, and rollback remain mandatory.</small></span></div></aside></div></section>;
}

export function SafetyView({ state }: { state: VisualizationState }) {
  return <VisualizationBoundary state={state}>{(dashboard) => <section className="portfolio-page"><header className="page-intro safety-intro"><span className="viz-kicker">DETERMINISTIC TRUST BOUNDARY</span><h2>The model proposes. The system decides what is true.</h2><p>Scope enforcement, trusted commands, verification, exact approval, and byte-correct rollback are deterministic controls.</p></header><div className="safety-grid"><article><span>01</span><strong>Worktree isolation</strong><p>Writes never target the source workspace directly.</p></article><article><span>02</span><strong>Exact scope</strong><p>Files, lines, commands, and expiry are bounded.</p></article><article><span>03</span><strong>Machine verification</strong><p>NOT RUN, timeout, and unknown never become PASS.</p></article><article><span>04</span><strong>Rollback</strong><p>Pre-patch content and mode are restorable.</p></article></div><div className="chart-grid"><VerificationFunnel chart={dashboard.charts.verificationFunnel}/><ObservabilityComparison chart={dashboard.charts.observability}/></div><div className="mutation-lock"><b>LOCKED</b><span><strong>Autonomous mutation is not a production capability.</strong><small>Current status: {dashboard.product.mutation}. Final formation study primary calls: {dashboard.product.primaryCallsInFinalStudy}.</small></span></div></section>}</VisualizationBoundary>;
}
