import React, { useState } from "react";
import type { AgentEvent, RunState, VerificationStage } from "../../../../packages/contracts/src/index";
import type { RunProjection } from "../../../../packages/event-protocol/src/index";
import { Icon } from "../components/Icon";
import { demoEvents } from "./demo";
import type { VisualizationState } from "../../../../services/experiment-visualization/src/index";
import { ArchitectureEvidenceCaptureView, CapabilitiesView, DashboardView, ExperimentsView, ResearchCaptureView, SafetyView, TaskWorkflowView } from "./ProductizationViews";

export function WorkspaceView({ view, projection, verification, reducedMotion, onReplay, onNotify, onNavigate, onRun, visualizationState }: {
  view: string; projection: RunProjection; verification: VerificationStage[]; reducedMotion: boolean; onReplay: () => void; onNotify: (message: string) => void; onNavigate: (view: string) => void; onRun: () => void; visualizationState: VisualizationState;
}) {
  if (view === "Dashboard") return <DashboardView state={visualizationState} onNavigate={onNavigate}/>;
  if (view === "Research Dashboard") return <ResearchCaptureView state={visualizationState}/>;
  if (view === "Architecture Evidence") return <ArchitectureEvidenceCaptureView state={visualizationState}/>;
  if (view === "Capabilities") return <CapabilitiesView state={visualizationState}/>;
  if (view === "Experiments") return <ExperimentsView state={visualizationState}/>;
  if (view === "Workspace") return <TaskWorkflowView projection={projection} onRun={onRun}/>;
  if (view === "Safety") return <SafetyView state={visualizationState}/>;
  if (view === "Flow") return <FlowView state={projection.state} activeAgent={projection.activeAgent} events={projection.events} reducedMotion={reducedMotion}/>;
  if (view === "Repository") return <RepositoryView onNotify={onNotify}/>;
  if (view === "Overview") return <OverviewView />;
  if (view === "Architecture") return <ArchitectureView />;
  if (view === "Code") return <CodeView />;
  if (view === "Diff") return <DiffView verification={verification} onNotify={onNotify}/>;
  if (view === "Verify") return <VerificationView stages={verification}/>;
  if (view === "Findings") return <FindingsView projection={projection}/>;
  if (view === "Report") return <ReportView projection={projection} />;
  if (view === "History") return <HistoryView onReplay={onReplay}/>;
  if (view === "Runtime") return <RuntimeView projection={projection}/>;
  if (view === "Approvals") return <ApprovalsView projection={projection}/>;
  return <SettingsView reducedMotion={reducedMotion}/>;
}

function FlowView({ state, activeAgent, events, reducedMotion }: { state: RunState; activeAgent?: string; events: AgentEvent[]; reducedMotion: boolean }) {
  const active = activeAgent ?? (state === "CREATED" ? "Orchestrator" : "Repo Analyst");
  const nodes = [
    { name: "Orchestrator", role: "Contract · Route", x: 50, y: 12 }, { name: "Repo Analyst", role: "R11 · Analyze", x: 25, y: 43 },
    { name: "Coder", role: "R20 · Patch", x: 75, y: 43 }, { name: "Verification", role: "Machine oracle", x: 25, y: 76 },
    { name: "Reviewer", role: "R22 · Review", x: 75, y: 76 }
  ];
  return <section className="flow-view" aria-label="Agent flow"><div className="flow-canvas"><svg className="flow-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M50 20 L25 43 M50 20 L75 43 M25 51 L25 76 M75 51 L75 76 M31 79 L69 79"/><path className="active-path" d="M50 20 L25 43 L25 76 L69 79"/>{!reducedMotion && state !== "CREATED" && <circle className="travel-dot" r="1.2"><animateMotion dur="2.8s" repeatCount="indefinite" path="M50 20 L25 43 L25 76 L69 79"/></circle>}</svg>{nodes.map((node) => <button key={node.name} className={`agent-node ${active === node.name || (node.name === "Verification" && state === "VERIFYING") || (node.name === "Reviewer" && state === "REVIEWING") ? "active" : ""}`} style={{ left: `${node.x}%`, top: `${node.y}%` }}><span className="node-icon">{node.name === "Verification" ? "✓" : node.name.charAt(0)}</span><span><strong>{node.name}</strong><small>{node.role}</small></span><span className="node-state">{active === node.name ? "ACTIVE" : "READY"}</span></button>)}<div className="flow-caption"><span className="live-dot"/> Event projection <b>{events.length}</b> retained events</div></div><div className="timeline"><div className="timeline-heading"><strong>Trace</strong><span>Typed events · local only</span></div>{(events.length ? events.slice(-5).reverse() : demoEvents.slice(0, 5)).map((event) => <div className="trace-row" key={event.eventId}><span className={`trace-icon ${event.type.includes("verification") ? "green" : ""}`}>{event.type.includes("verification") ? "✓" : "·"}</span><span><strong>{event.type}</strong><small>{String(event.payload.message ?? event.source)}</small></span><time>{new Date(event.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</time></div>)}</div></section>;
}

function RepositoryView({ onNotify }: { onNotify: (message: string) => void }) { return <section className="product-grid"><article className="product-card hero-product"><span className="section-kicker">LOCAL WORKSPACE</span><h2>Open a repository without uploading source</h2><p>Folder selection is handed to the native Tauri boundary. The runtime validates the allowed root, Git identity, ignore rules and mutation isolation before indexing.</p><button className="run-button inline-action" onClick={() => onNotify("Native folder picker is available in the packaged Tauri runtime")}>Choose local folder</button></article><article className="product-card"><h3>Acquisition checks</h3><ul><li>Allowed workspace root</li><li>Git baseline SHA</li><li>Ignored and symlink exclusion</li><li>Read-only or isolated worktree mode</li></ul></article><article className="product-card"><h3>Current source</h3><dl><dt>Repository</dt><dd>Desk Code Agent fixture</dd><dt>Transport</dt><dd>Local filesystem</dd><dt>Mutation</dt><dd>Isolated worktree required</dd></dl></article></section>; }

function OverviewView() { return <section className="overview-grid"><article className="hero-card"><span className="section-kicker">REPOSITORY OVERVIEW</span><h2>Local-first engineering workspace</h2><p>A bounded agent harness that maps repositories, retrieves cited evidence, proposes patches, and delegates truth to deterministic verification.</p><div className="tech-row"><span>TypeScript</span><span>React</span><span>Vite</span><span>Local Qwen</span></div></article><MetricCard value="428" label="Source files" detail="32.4K lines"/><MetricCard value="1,204" label="Symbols" detail="96% indexed"/><MetricCard value="86" label="Tests" detail="7 suites"/><article className="content-card span-2"><h3>Recommended reading order</h3>{["CONTEXT.md", "docs/01_PRODUCT_REQUIREMENTS.md", "docs/03_AGENT_HARNESS.md", "packages/event-protocol/src/index.ts"].map((item, i) => <div className="reading-row" key={item}><b>{i + 1}</b><span>{item}</span><small>{["Domain language", "Product boundaries", "State machine", "Event projection"][i]}</small></div>)}</article><article className="content-card"><h3>Detected commands</h3><code>npm run dev</code><code>npm run test</code><code>npm run check</code></article></section>; }
function MetricCard({ value, label, detail }: { value: string; label: string; detail: string }) { return <article className="metric-card"><strong>{value}</strong><span>{label}</span><small>{detail}</small></article>; }

function ArchitectureView() { return <section className="architecture-view"><div className="architecture-graph"><div className="arch-node core"><small>ORCHESTRATION</small><strong>Agent Runtime</strong><span>route · gate · state</span></div><div className="arch-row"><div className="arch-node"><small>INTELLIGENCE</small><strong>Repo Intelligence</strong><span>map · retrieve · cite</span></div><div className="arch-node"><small>INFERENCE</small><strong>Model Gateway</strong><span>stream · cancel · metrics</span></div></div><div className="arch-row"><div className="arch-node"><small>TRUST</small><strong>Verification</strong><span>tests · types · build</span></div><div className="arch-node"><small>PROJECTION</small><strong>Event Protocol</strong><span>append · replay · reduce</span></div></div></div><aside className="architecture-notes"><span className="section-kicker">SELECTED MODULE</span><h2>Agent Runtime</h2><p>Owns state transitions, contracts, skills, approvals and recovery. It does not parse source code or perform inference directly.</p><dl><div><dt>Public methods</dt><dd>6</dd></div><div><dt>Dependencies</dt><dd>2</dd></div><div><dt>Test coverage</dt><dd>94%</dd></div></dl></aside></section>; }

const codeLines = [
  "export function evaluateFeasibility(", "  scope: ScopeEstimate,", "): FeasibilityDecision {", "  if (scope.securityRisk) {",
  "    return \"BLOCKED_BY_SECURITY_POLICY\";", "  }", "", "  if (!scope.hasOracle && scope.modifiedFiles > 0) {",
  "    return \"BLOCKED_BY_MISSING_ORACLE\";", "  }", "", "  return scope.modifiedFiles === 0", "    ? \"REPORT_ONLY\"", "    : \"AUTO_EXECUTE\";", "}"
];
function CodeView() { return <section className="code-view"><div className="code-tabs"><button className="active">router.ts <span>×</span></button><button>runtime.test.ts <span>×</span></button></div><div className="code-breadcrumb">services / agent-runtime / src / <b>router.ts</b></div><pre className="code-editor"><code>{codeLines.map((line, index) => <span key={index}><i>{String(index + 1).padStart(2, "0")}</i>{line || " "}</span>)}</code></pre><div className="code-status"><span>Ln 8, Col 24</span><span>UTF-8</span><span>TypeScript</span><span className="good-text">✓ No diagnostics</span></div></section>; }

function DiffView({ verification, onNotify }: { verification: VerificationStage[]; onNotify: (value: string) => void }) { return <section className="diff-view"><div className="diff-toolbar"><div><span className="file-badge">TS</span><strong>services/agent-runtime/src/router.ts</strong><small>+8 −2</small></div><div><button className="active">Unified</button><button>Split</button></div></div><div className="diff-code"><div className="diff-context"><i>38</i><i>38</i><code>export function evaluateFeasibility(scope: ScopeEstimate) &#123;</code></div><div className="diff-remove"><i>39</i><i></i><code>- if (scope.modifiedFiles &gt; 8) return "TASK_TOO_LARGE";</code></div><div className="diff-add"><i></i><i>39</i><code>+ if (scope.securityRisk) return "BLOCKED_BY_SECURITY_POLICY";</code></div><div className="diff-add"><i></i><i>40</i><code>+ if (!scope.hasOracle &amp;&amp; scope.modifiedFiles &gt; 0)</code></div><div className="diff-add"><i></i><i>41</i><code>+ &nbsp; return "BLOCKED_BY_MISSING_ORACLE";</code></div><div className="diff-context"><i>40</i><i>42</i><code>&nbsp; if (scope.patchLines &gt; 800) return "TASK_TOO_LARGE";</code></div></div><div className="patch-reason"><span className="reason-icon">R</span><div><strong>Patch plan PP-04 · SC-2</strong><p>Add deterministic security and oracle gates before mutation. Supported by E-17 and E-21.</p></div><div className="evidence-pills"><span>E-17</span><span>E-21</span></div></div><div className="diff-footer"><div>{verification.slice(0,4).map((stage) => <span key={stage.id} className="check-pill">✓ {stage.label}</span>)}</div><button className="soft-button danger" onClick={() => onNotify("Patch reverted in isolated worktree")}>Revert patch</button></div></section>; }

function VerificationView({ stages }: { stages: VerificationStage[] }) { const allPass = stages.length > 0 && stages.every((stage) => stage.status === "PASS"); const active = stages.some((stage) => ["QUEUED", "RUNNING"].includes(stage.status)); return <section className="verification-view"><div className="verification-summary"><div className="score-ring"><strong>{stages.filter((stage) => stage.status === "PASS").length}</strong><span>/ {stages.length} stages</span></div><div><span className="section-kicker">DETERMINISTIC VERIFICATION</span><h2>{allPass ? "All required stages passed" : active ? "Machine truth in progress" : "Verification not complete"}</h2><p>{allPass ? "Review may proceed using these machine results." : "NOT RUN, failed, cancelled and timed-out stages never render as PASS."}</p></div></div><div className="stage-list">{stages.map((stage) => <div className={`stage-row status-${stage.status.toLowerCase()}`} key={stage.id}><span className="stage-state">{stage.status === "PASS" ? "✓" : stage.status === "RUNNING" ? "···" : "○"}</span><span><strong>{stage.label}</strong><small>{stage.trustedCommandId}</small></span><span className="stage-summary">{stage.summary}</span><time>{stage.durationMs ? `${stage.durationMs} ms` : stage.status.replace("_", " ")}</time></div>)}</div><div className="machine-note"><Icon name="shield"/><span><strong>Trusted command registry</strong><small>Commands are schema-validated, path-bounded, timed and audited. Model prose cannot mark a stage PASS.</small></span></div></section>; }

function FindingsView({ projection }: { projection: RunProjection }) { const alerts = projection.events.filter((event) => /security|failed|rejected|blocked|timeout/i.test(event.type)); return <section className="product-grid"><article className="product-card hero-product"><span className="section-kicker">EVIDENCE-LABELLED FINDINGS</span><h2>{alerts.length ? `${alerts.length} runtime finding${alerts.length === 1 ? "" : "s"}` : "No findings in the current trace"}</h2><p>Findings are hypotheses or machine outcomes with explicit provenance. Repository prose cannot promote itself to a verified fact.</p></article>{alerts.map((event) => <article className="product-card" key={event.eventId}><span className="finding-level">{event.severity}</span><h3>{event.type}</h3><p>{String(event.payload.message ?? "No human-readable detail")}</p><code>{event.eventId}</code></article>)}</section>; }
function RuntimeView({ projection }: { projection: RunProjection }) {
  const latest = [...projection.events].reverse().find((event) => /^model\.(?:started|ready|restarted|failed|cancelled)$/.test(event.type));
  const status = latest?.type === "model.ready" ? "Ready" : latest?.type === "model.failed" ? "Error" : latest?.type === "model.cancelled" ? "Cancelled" : latest ? "Starting" : "Offline";
  const vram = typeof latest?.payload.vramMiB === "number" ? `${latest.payload.vramMiB} MiB` : "NOT RUN";
  const detail = latest ? String(latest.payload.message ?? latest.type) : "No model telemetry event";
  return <section className="product-grid"><article className="product-card hero-product"><span className="section-kicker">MODEL / RUNTIME TELEMETRY</span><h2>{status} · {latest ? detail : "no active model request"}</h2><p>Telemetry displays only observed values. VRAM, throughput and TTFT remain unavailable until the local gateway emits a measured event.</p></article><MetricCard value={String(projection.totalEvents)} label="Events observed" detail={`${projection.events.length} retained in UI window`}/><MetricCard value="0" label="Queued requests" detail="Current replay projection"/><MetricCard value={vram} label="Live inference" detail={detail}/></section>;
}
function ApprovalsView({ projection }: { projection: RunProjection }) { return <section className="product-grid"><article className="product-card hero-product"><span className="section-kicker">APPROVAL CENTER</span><h2>{projection.approval ? "One exact action awaits review" : "No protected action is pending"}</h2><p>Approvals bind action, target, artifact hash, scope and expiry. They are one-time and cannot authorize another step.</p></article>{projection.approval && <article className="product-card span-all"><dl><dt>Action</dt><dd>{projection.approval.action}</dd><dt>Target</dt><dd>{projection.approval.target}</dd><dt>Artifact</dt><dd><code>{projection.approval.artifactHash}</code></dd><dt>Scope</dt><dd>{projection.approval.scope}</dd><dt>Rollback</dt><dd>{projection.approval.rollback}</dd></dl></article>}</section>; }

function ReportView({ projection }: { projection: RunProjection }) { const passed = projection.verification.filter((stage) => stage.status === "PASS").length; const complete = projection.state === "DONE" && projection.verification.length > 0 && passed === projection.verification.length; const patch = projection.events.find((event) => event.type === "patch.applied"); return <section className="report-view"><header><span className="report-status">{complete ? "VERIFIED OUTCOMES" : "EVIDENCE STATUS"}</span><h2>{complete ? "Run completed with machine verification" : "No fully verified outcome is available"}</h2><p>{complete ? projection.currentMessage : "A report can summarize evidence, but it cannot label work complete until every mandatory machine stage passes."}</p></header><div className="report-stats"><div><strong>{Number(patch?.payload.files ?? 0)}</strong><span>files changed</span></div><div><strong>{Number(patch?.payload.lines ?? 0)}</strong><span>patch lines</span></div><div><strong>{passed}</strong><span>stages passed</span></div><div><strong>{projection.events.filter((event) => event.severity === "critical").length}</strong><span>critical events</span></div></div><article><h3>Outcome</h3><p>{complete ? "The typed trace reached DONE after deterministic verification." : `Current runtime state is ${projection.state}. This is not rendered as PASS.`}</p><h3>Evidence</h3><ul>{projection.evidence.length ? projection.evidence.map((item) => <li key={item.id}><b>{item.id}</b> {item.path}:{item.startLine}</li>) : <li>No evidence has been retrieved in this trace.</li>}</ul><h3>Remaining verification</h3>{projection.verification.filter((stage) => stage.status !== "PASS").map((stage) => <p className="not-run" key={stage.id}>○ {stage.label} — {stage.status.replace("_", " ")}</p>)}</article></section>; }

function HistoryView({ onReplay }: { onReplay: () => void }) { const runs=[{id:"run_demo_001",title:"Analyze runtime safety and safely fix bounded risks",status:"Reviewing",time:"Today, 11:28",events:18},{id:"run_prev_042",title:"Create repository overview and reading order",status:"Complete",time:"Yesterday, 16:04",events:31},{id:"run_prev_041",title:"Trace cancellation state transitions",status:"Cancelled",time:"Aug 7, 09:12",events:12}]; return <section className="history-view"><div className="history-filters"><button className="active">All runs</button><button>Completed</button><button>Cancelled</button></div>{runs.map((run) => <article className="history-card" key={run.id}><span className={`history-status ${run.status.toLowerCase()}`}>{run.status === "Complete" ? "✓" : run.status === "Cancelled" ? "×" : "◉"}</span><div><strong>{run.title}</strong><span>{run.id} · {run.events} events · Local only</span></div><time>{run.time}</time><button onClick={onReplay}><Icon name="play"/> Replay</button></article>)}</section>; }

function SettingsView({ reducedMotion }: { reducedMotion: boolean }) { return <section className="settings-view"><aside><button className="active">General</button><button>Model</button><button>Privacy</button><button>Permissions</button><button>Appearance</button></aside><div><span className="section-kicker">GENERAL</span><h2>Workspace settings</h2><Setting title="Local-only mode" description="Block non-loopback runtime connections by default" checked/><Setting title="Confirm protected actions" description="Require exact hash and scope approval" checked/><Setting title="Reduced motion" description="Follow the current system accessibility preference" checked={reducedMotion}/><Setting title="Persist raw model output" description="Raw prompts and model prose are excluded from telemetry" checked={false}/><div className="settings-card"><strong>Artifact retention</strong><p>Keep local run artifacts for</p><select defaultValue="30"><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select></div></div></section>; }
function Setting({title,description,checked}:{title:string;description:string;checked:boolean}) { const [value,setValue]=useState(checked); return <label className="setting-row"><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" checked={value} onChange={(event)=>setValue(event.target.checked)}/><i aria-hidden="true"/></label>; }
