import React from "react";
import type { AgentEvent, RunState, VerificationStage } from "../../../../packages/contracts/src/index";
import type { RunProjection } from "../../../../packages/event-protocol/src/index";
import { Icon } from "../components/Icon";
import { demoEvents } from "./demo";
import type { VisualizationState } from "../../../../services/experiment-visualization/src/index";
import { ArchitectureEvidenceCaptureView, CapabilitiesView, DashboardView, ExperimentsView, ResearchCaptureView, SafetyView, TaskWorkflowView } from "./ProductizationViews";

export function WorkspaceView({ view, projection, verification, reducedMotion, onReplay, onNotify, onNavigate, onRun, visualizationState, theme, textScale, density, motionOverride, onThemeChange, onTextScaleChange, onDensityChange, onMotionOverrideChange }: {
  view: string;
  projection: RunProjection;
  verification: VerificationStage[];
  reducedMotion: boolean;
  onReplay: () => void;
  onNotify: (message: string) => void;
  onNavigate: (view: string) => void;
  onRun: () => void;
  visualizationState: VisualizationState;
  theme: "system" | "dark" | "light";
  textScale: "100" | "110" | "125";
  density: "comfortable" | "compact";
  motionOverride: boolean | null;
  onThemeChange: (value: "system" | "dark" | "light") => void;
  onTextScaleChange: (value: "100" | "110" | "125") => void;
  onDensityChange: (value: "comfortable" | "compact") => void;
  onMotionOverrideChange: (value: boolean | null) => void;
}) {
  if (view === "Dashboard") return <DashboardView state={visualizationState} onNavigate={onNavigate}/>;
  if (view === "Research Dashboard") return <ResearchCaptureView state={visualizationState}/>;
  if (view === "Architecture Evidence") return <ArchitectureEvidenceCaptureView state={visualizationState}/>;
  if (view === "Capabilities") return <CapabilitiesView state={visualizationState}/>;
  if (view === "Experiments") return <ExperimentsView state={visualizationState}/>;
  if (view === "Workspace") return <TaskWorkflowView projection={projection} onRun={onRun}/>;
  if (view === "Safety") return <SafetyView state={visualizationState}/>;
  if (view === "Flow") return <FlowView state={projection.state} activeAgent={projection.activeAgent} events={projection.events} reducedMotion={reducedMotion}/>;
  if (view === "Repository") return <RepositoryDemoView/>;
  if (view === "Overview") return <OverviewView />;
  if (view === "Architecture") return <ArchitectureView />;
  if (view === "Code") return <CodeView />;
  if (view === "Diff") return <DiffView verification={verification} onNotify={onNotify}/>;
  if (view === "Verify") return <VerificationView stages={verification}/>;
  if (view === "Findings") return <FindingsView projection={projection}/>;
  if (view === "Report") return <ReportView projection={projection} />;
  if (view === "History") return <HistoryView onReplay={onReplay}/>;
  if (view === "Runtime") return <RuntimeView projection={projection}/>;
  if (view === "Approvals") return <ApprovalsView projection={projection}/>;
  if (view === "Settings") return <SettingsView reducedMotion={reducedMotion} theme={theme} textScale={textScale} density={density} motionOverride={motionOverride} onThemeChange={onThemeChange} onTextScaleChange={onTextScaleChange} onDensityChange={onDensityChange} onMotionOverrideChange={onMotionOverrideChange}/>;
  return <UnavailableWorkspaceView view={view}/>;
}

function UnavailableWorkspaceView({ view }: { view: string }) {
  return <section className="unavailable-view"><span className="unavailable-icon"><Icon name="overview" size={24}/></span><span className="section-kicker">VIEW UNAVAILABLE</span><h2>This workspace view is not available</h2><p><strong>{view || "Unknown"}</strong> does not map to a supported Desk surface in this build. Choose a labelled item from the primary navigation.</p></section>;
}

function FlowView({ state, activeAgent, events, reducedMotion }: { state: RunState; activeAgent?: string; events: AgentEvent[]; reducedMotion: boolean }) {
  const active = activeAgent ?? (state === "CREATED" ? "Orchestrator" : "Repo Analyst");
  const nodes = [
    { name: "Orchestrator", role: "Contract · Route", x: 50, y: 12 }, { name: "Repo Analyst", role: "R11 · Analyze", x: 25, y: 43 },
    { name: "Coder", role: "R20 · Patch", x: 75, y: 43 }, { name: "Verification", role: "Machine oracle", x: 25, y: 76 },
    { name: "Reviewer", role: "R22 · Review", x: 75, y: 76 }
  ];
  return <section className="flow-view" aria-label="Agent flow"><div className="flow-canvas"><svg className="flow-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M50 20 L25 43 M50 20 L75 43 M25 51 L25 76 M75 51 L75 76 M31 79 L69 79"/><path className="active-path" d="M50 20 L25 43 L25 76 L69 79"/>{!reducedMotion && state !== "CREATED" && <circle key={events.at(-1)?.eventId ?? state} className="travel-dot" r="1.2"><animateMotion dur="1.1s" repeatCount="1" fill="freeze" path="M50 20 L25 43 L25 76 L69 79"/></circle>}</svg>{nodes.map((node) => <div key={node.name} className={`agent-node ${active === node.name || (node.name === "Verification" && state === "VERIFYING") || (node.name === "Reviewer" && state === "REVIEWING") ? "active" : ""}`} style={{ left: `${node.x}%`, top: `${node.y}%` }}><span className="node-icon">{node.name === "Verification" ? "✓" : node.name.charAt(0)}</span><span><strong>{node.name}</strong><small>{node.role}</small></span><span className="node-state">{active === node.name ? "ACTIVE" : "READY"}</span></div>)}<div className="flow-caption"><span className="live-dot"/> Event projection <b>{events.length}</b> retained events</div></div><div className="timeline"><div className="timeline-heading"><strong>Trace</strong><span>Typed events · local only</span></div>{(events.length ? events.slice(-5).reverse() : demoEvents.slice(0, 5)).map((event) => <div className="trace-row" key={event.eventId}><span className={`trace-icon ${event.type.includes("verification") ? "green" : ""}`}>{event.type.includes("verification") ? "✓" : "·"}</span><span><strong>{event.type}</strong><small>{String(event.payload.message ?? event.source)}</small></span><time>{new Date(event.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</time></div>)}</div></section>;
}

function RepositoryDemoView() { return <section className="product-grid"><article className="product-card hero-product"><span className="section-kicker">GUIDED DEMO · FIXTURE DATA</span><h2>Explore the repository workflow safely</h2><p>This surface is a deterministic product tour. It does not read a repository, run a model, or modify files. Exit the demo to choose a real local Git folder.</p></article><article className="product-card"><h3>What the demo explains</h3><ul><li>Repository evidence and provenance</li><li>Typed activity events</li><li>Deterministic verification states</li><li>Approval and rollback boundaries</li></ul></article><article className="product-card"><h3>Demo boundaries</h3><dl><dt>Repository</dt><dd>Fixture only</dd><dt>Model calls</dt><dd>0</dd><dt>Mutation</dt><dd>DISABLED</dd></dl></article></section>; }

function OverviewView() { return <section className="overview-grid"><article className="hero-card"><span className="section-kicker">REPOSITORY OVERVIEW</span><h2>Local-first engineering workspace</h2><p>A bounded agent harness that maps repositories, retrieves cited evidence, proposes patches, and delegates truth to deterministic verification.</p><div className="tech-row"><span>TypeScript</span><span>React</span><span>Vite</span><span>Local Qwen</span></div></article><MetricCard value="428" label="Source files" detail="32.4K lines"/><MetricCard value="1,204" label="Symbols" detail="96% indexed"/><MetricCard value="86" label="Tests" detail="7 suites"/><article className="content-card span-2"><h3>Recommended reading order</h3>{["CONTEXT.md", "docs/01_PRODUCT_REQUIREMENTS.md", "docs/03_AGENT_HARNESS.md", "packages/event-protocol/src/index.ts"].map((item, i) => <div className="reading-row" key={item}><b>{i + 1}</b><span>{item}</span><small>{["Domain language", "Product boundaries", "State machine", "Event projection"][i]}</small></div>)}</article><article className="content-card"><h3>Detected commands</h3><code>npm run dev</code><code>npm run test</code><code>npm run check</code></article></section>; }
function MetricCard({ value, label, detail }: { value: string; label: string; detail: string }) { return <article className="metric-card"><strong>{value}</strong><span>{label}</span><small>{detail}</small></article>; }

function ArchitectureView() { return <section className="architecture-view"><div className="architecture-graph"><div className="arch-node core"><small>ORCHESTRATION</small><strong>Agent Runtime</strong><span>route · gate · state</span></div><div className="arch-row"><div className="arch-node"><small>INTELLIGENCE</small><strong>Repo Intelligence</strong><span>map · retrieve · cite</span></div><div className="arch-node"><small>INFERENCE</small><strong>Model Gateway</strong><span>stream · cancel · metrics</span></div></div><div className="arch-row"><div className="arch-node"><small>TRUST</small><strong>Verification</strong><span>tests · types · build</span></div><div className="arch-node"><small>PROJECTION</small><strong>Event Protocol</strong><span>append · replay · reduce</span></div></div></div><aside className="architecture-notes"><span className="section-kicker">SELECTED MODULE</span><h2>Agent Runtime</h2><p>Owns state transitions, contracts, skills, approvals and recovery. It does not parse source code or perform inference directly.</p><dl><div><dt>Public methods</dt><dd>6</dd></div><div><dt>Dependencies</dt><dd>2</dd></div><div><dt>Test coverage</dt><dd>94%</dd></div></dl></aside></section>; }

const codeLines = [
  "export function evaluateFeasibility(", "  scope: ScopeEstimate,", "): FeasibilityDecision {", "  if (scope.securityRisk) {",
  "    return \"BLOCKED_BY_SECURITY_POLICY\";", "  }", "", "  if (!scope.hasOracle && scope.modifiedFiles > 0) {",
  "    return \"BLOCKED_BY_MISSING_ORACLE\";", "  }", "", "  return scope.modifiedFiles === 0", "    ? \"REPORT_ONLY\"", "    : \"AUTO_EXECUTE\";", "}"
];
function CodeView() { return <section className="code-view"><div className="code-tabs"><span className="active">router.ts</span><span>Demo preview · read only</span></div><div className="code-breadcrumb">services / agent-runtime / src / <b>router.ts</b></div><pre className="code-editor"><code>{codeLines.map((line, index) => <span key={index}><i>{String(index + 1).padStart(2, "0")}</i>{line || " "}</span>)}</code></pre><div className="code-status"><span>Ln 8, Col 24</span><span>UTF-8</span><span>TypeScript</span><span className="good-text">✓ Demo fixture</span></div></section>; }

function DiffView({ verification, onNotify }: { verification: VerificationStage[]; onNotify: (value: string) => void }) { return <section className="diff-view"><div className="diff-toolbar"><div><span className="file-badge">TS</span><strong>services/agent-runtime/src/router.ts</strong><small>+8 −2</small></div><span className="demo-view-label">Unified demo preview</span></div><div className="diff-code"><div className="diff-context"><i>38</i><i>38</i><code>export function evaluateFeasibility(scope: ScopeEstimate) &#123;</code></div><div className="diff-remove"><i>39</i><i></i><code>- if (scope.modifiedFiles &gt; 8) return "TASK_TOO_LARGE";</code></div><div className="diff-add"><i></i><i>39</i><code>+ if (scope.securityRisk) return "BLOCKED_BY_SECURITY_POLICY";</code></div><div className="diff-add"><i></i><i>40</i><code>+ if (!scope.hasOracle &amp;&amp; scope.modifiedFiles &gt; 0)</code></div><div className="diff-add"><i></i><i>41</i><code>+ &nbsp; return "BLOCKED_BY_MISSING_ORACLE";</code></div><div className="diff-context"><i>40</i><i>42</i><code>&nbsp; if (scope.patchLines &gt; 800) return "TASK_TOO_LARGE";</code></div></div><div className="patch-reason"><span className="reason-icon">R</span><div><strong>Demo patch plan PP-04 · SC-2</strong><p>This fixture illustrates how evidence would support a bounded proposal. No repository was changed.</p></div><div className="evidence-pills"><span>E-17</span><span>E-21</span></div></div><div className="diff-footer"><div>{verification.slice(0,4).map((stage) => <span key={stage.id} className="check-pill">{stage.status === "PASS" ? "✓" : "○"} {stage.label}</span>)}</div><button className="soft-button" onClick={() => onNotify("This deterministic demo preview is read-only; nothing was changed.")}>Explain preview</button></div></section>; }

function VerificationView({ stages }: { stages: VerificationStage[] }) { const allPass = stages.length > 0 && stages.every((stage) => stage.status === "PASS"); const active = stages.some((stage) => ["QUEUED", "RUNNING"].includes(stage.status)); return <section className="verification-view"><div className="verification-summary"><div className="score-ring"><strong>{stages.filter((stage) => stage.status === "PASS").length}</strong><span>/ {stages.length} stages</span></div><div><span className="section-kicker">DETERMINISTIC VERIFICATION</span><h2>{allPass ? "All required stages passed" : active ? "Machine truth in progress" : "Verification not complete"}</h2><p>{allPass ? "Review may proceed using these machine results." : "NOT RUN, failed, cancelled and timed-out stages never render as PASS."}</p></div></div><div className="stage-list">{stages.map((stage) => <div className={`stage-row status-${stage.status.toLowerCase()}`} key={stage.id}><span className="stage-state">{stage.status === "PASS" ? "✓" : stage.status === "RUNNING" ? "···" : "○"}</span><span><strong>{stage.label}</strong><small>{stage.trustedCommandId}</small></span><span className="stage-summary">{stage.summary}</span><time>{stage.durationMs ? `${stage.durationMs} ms` : stage.status.replace("_", " ")}</time></div>)}</div><div className="machine-note"><Icon name="shield"/><span><strong>Trusted command registry</strong><small>Commands are schema-validated, path-bounded, timed and audited. Model prose cannot mark a stage PASS.</small></span></div></section>; }

function FindingsView({ projection }: { projection: RunProjection }) { const alerts = projection.events.filter((event) => /security|failed|rejected|blocked|timeout/i.test(event.type)); return <section className="product-grid"><article className="product-card hero-product"><span className="section-kicker">EVIDENCE-LABELLED FINDINGS</span><h2>{alerts.length ? `${alerts.length} runtime finding${alerts.length === 1 ? "" : "s"}` : "No findings in the current trace"}</h2><p>Findings are hypotheses or machine outcomes with explicit provenance. Repository prose cannot promote itself to a verified fact.</p></article>{alerts.map((event) => <article className="product-card" key={event.eventId}><span className="finding-level">{event.severity}</span><h3>{event.type}</h3><p>{String(event.payload.message ?? "No human-readable detail")}</p><code>{event.eventId}</code></article>)}</section>; }
function RuntimeView({ projection }: { projection: RunProjection }) {
  const latest = [...projection.events].reverse().find((event) => /^model\.(?:started|ready|restarted|failed|cancelled)$/.test(event.type));
  const status = latest?.type === "model.ready" ? "Ready" : latest?.type === "model.failed" ? "Error" : latest?.type === "model.cancelled" ? "Cancelled" : latest ? "Starting" : "Offline";
  const vram = typeof latest?.payload.vramMiB === "number" ? `${latest.payload.vramMiB} MiB` : "NOT RUN";
  const detail = latest ? String(latest.payload.message ?? latest.type) : "No model telemetry event";
  return <section className="product-grid"><article className="product-card hero-product"><span className="section-kicker">MODEL / RUNTIME TELEMETRY</span><h2>{status} · {latest ? detail : "no active model request"}</h2><p>Telemetry displays only observed values. VRAM, throughput and TTFT remain unavailable until the local gateway emits a measured event.</p></article><MetricCard value={String(projection.totalEvents)} label="Events observed" detail={`${projection.events.length} retained in UI window`}/><MetricCard value="0" label="Queued requests" detail="Current replay projection"/><MetricCard value={vram} label="Live inference" detail={detail}/></section>;
}
function ApprovalsView({ projection }: { projection: RunProjection }) { return <section className="product-grid"><article className="product-card hero-product"><span className="section-kicker">APPROVAL CENTER</span><h2>{projection.approval ? "One exact action awaits review" : "No protected action is pending"}</h2><p>Approvals bind action, target, artifact hash, scope and expiry. They are one-time and cannot authorize another step.</p></article>{projection.approval && <article className="product-card span-all"><dl><dt>Action</dt><dd>{projection.approval.action}</dd><dt>Target</dt><dd>{projection.approval.target}</dd><dt>Artifact</dt><dd><code>{projection.approval.artifactHash}</code></dd><dt>Scope</dt><dd>{projection.approval.scope}</dd><dt>Rollback</dt><dd>{projection.approval.rollback}</dd></dl></article>}</section>; }

function ReportView({ projection }: { projection: RunProjection }) { const passed = projection.verification.filter((stage) => stage.status === "PASS").length; const complete = projection.state === "DONE" && projection.verification.length > 0 && passed === projection.verification.length; const patch = projection.events.find((event) => event.type === "patch.applied"); return <section className="report-view"><header><span className="report-status">{complete ? "VERIFIED OUTCOMES" : "EVIDENCE STATUS"}</span><h2>{complete ? "Run completed with machine verification" : "No fully verified outcome is available"}</h2><p>{complete ? projection.currentMessage : "A report can summarize evidence, but it cannot label work complete until every mandatory machine stage passes."}</p></header><div className="report-stats"><div><strong>{Number(patch?.payload.files ?? 0)}</strong><span>files changed</span></div><div><strong>{Number(patch?.payload.lines ?? 0)}</strong><span>patch lines</span></div><div><strong>{passed}</strong><span>stages passed</span></div><div><strong>{projection.events.filter((event) => event.severity === "critical").length}</strong><span>critical events</span></div></div><article><h3>Outcome</h3><p>{complete ? "The typed trace reached DONE after deterministic verification." : `Current runtime state is ${projection.state}. This is not rendered as PASS.`}</p><h3>Evidence</h3><ul>{projection.evidence.length ? projection.evidence.map((item) => <li key={item.id}><b>{item.id}</b> {item.path}:{item.startLine}</li>) : <li>No evidence has been retrieved in this trace.</li>}</ul><h3>Remaining verification</h3>{projection.verification.filter((stage) => stage.status !== "PASS").map((stage) => <p className="not-run" key={stage.id}>○ {stage.label} — {stage.status.replace("_", " ")}</p>)}</article></section>; }

function HistoryView({ onReplay }: { onReplay: () => void }) { const runs=[{id:"run_demo_001",title:"Analyze runtime safety and safely fix bounded risks",status:"Reviewing",time:"Demo trace",events:18},{id:"run_prev_042",title:"Create repository overview and reading order",status:"Complete",time:"Demo trace",events:31},{id:"run_prev_041",title:"Trace cancellation state transitions",status:"Cancelled",time:"Demo trace",events:12}]; return <section className="history-view"><div className="history-filters"><strong>Guided demo traces</strong><span>Fixture data · no repository accessed</span></div>{runs.map((run) => <article className="history-card" key={run.id}><span className={`history-status ${run.status.toLowerCase()}`}>{run.status === "Complete" ? "✓" : run.status === "Cancelled" ? "×" : "◉"}</span><div><strong>{run.title}</strong><span>{run.id} · {run.events} events · Local only</span></div><time>{run.time}</time><button onClick={onReplay}><Icon name="play"/> Replay</button></article>)}</section>; }

function SettingsView({ reducedMotion, theme, textScale, density, motionOverride, onThemeChange, onTextScaleChange, onDensityChange, onMotionOverrideChange }: {
  reducedMotion: boolean;
  theme: "system" | "dark" | "light";
  textScale: "100" | "110" | "125";
  density: "comfortable" | "compact";
  motionOverride: boolean | null;
  onThemeChange: (value: "system" | "dark" | "light") => void;
  onTextScaleChange: (value: "100" | "110" | "125") => void;
  onDensityChange: (value: "comfortable" | "compact") => void;
  onMotionOverrideChange: (value: boolean | null) => void;
}) {
  return <section className="settings-view"><aside aria-label="Settings sections"><span>Settings</span><span className="settings-section-current" aria-current="page">Appearance</span><span>Safety defaults are always on</span></aside><div><span className="section-kicker">APPEARANCE & ACCESSIBILITY</span><h2>Make the workspace comfortable</h2><p className="settings-intro">These preferences apply immediately and are stored only on this computer.</p>
    <fieldset className="settings-card"><legend>Color theme</legend><p>Use your system setting or choose a stable light or dark palette.</p><div className="segmented-control">{(["system", "dark", "light"] as const).map((value) => <label key={value}><input type="radio" name="theme" checked={theme === value} onChange={() => onThemeChange(value)}/><span>{value.charAt(0).toUpperCase() + value.slice(1)}</span></label>)}</div></fieldset>
    <div className="settings-card settings-select"><label htmlFor="text-scale"><strong>Text size</strong><span>Increase all interface text without changing display scaling.</span></label><select id="text-scale" value={textScale} onChange={(event) => onTextScaleChange(event.target.value as "100" | "110" | "125")}><option value="100">100%</option><option value="110">110%</option><option value="125">125%</option></select></div>
    <fieldset className="settings-card"><legend>Spacing</legend><p>Comfortable is recommended for everyday use.</p><div className="segmented-control">{(["comfortable", "compact"] as const).map((value) => <label key={value}><input type="radio" name="density" checked={density === value} onChange={() => onDensityChange(value)}/><span>{value.charAt(0).toUpperCase() + value.slice(1)}</span></label>)}</div></fieldset>
    <label className="setting-row"><span><strong>Reduce motion</strong><small>Remove travelling markers, loops, and spatial transitions. Current effective setting: {reducedMotion ? "Reduced" : "Full"}.</small></span><input type="checkbox" checked={motionOverride ?? reducedMotion} onChange={(event) => onMotionOverrideChange(event.target.checked)}/><i aria-hidden="true"/></label>
    <button className="soft-button system-motion-button" onClick={() => onMotionOverrideChange(null)} disabled={motionOverride === null}>Use system motion setting</button>
    <div className="immutable-settings" aria-label="Safety defaults"><article><Icon name="shield"/><span><strong>Local-only mode</strong><small>Non-loopback runtime connections are blocked by default.</small></span><b>ON</b></article><article><Icon name="verify"/><span><strong>Repository mutation</strong><small>Autonomous writes remain unavailable.</small></span><b>DISABLED</b></article><article><Icon name="report"/><span><strong>Raw model output</strong><small>Raw prompts and model prose are excluded from telemetry.</small></span><b>NOT STORED</b></article></div>
  </div></section>;
}
