import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { link, lstat, mkdir, open, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

const exec = promisify(execFile), root = path.resolve(process.cwd());
const sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const stable = (value: unknown): string => JSON.stringify(value, Object.keys(value as object).sort());
const p = {
  sessionB: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_SESSION_B.v1.json",
  indexB: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_RESULTS_INDEX.v3.json",
  resultsB: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_SESSION_B_PAIRED_RESULTS.v1.json",
  transitionsB: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_SESSION_B_TRANSITIONS.v1.json",
  prereg: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_PREREGISTRATION.v1.json",
  candidate: "docs/experiments/patch-interface/E_EDIT_CANDIDATE.v1.json",
  currentRunner: "scripts/run_code_formation_constraint_experiment.ts",
  currentMaterializer: "services/code-formation-experiment/src/index.ts",
  historicalRunner: "scripts/run_privacy_safe_observability_v3_session_b.ts",
  v3Prereg: "benchmarks/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_PREREGISTRATION.v3.json",
  v3SessionB: "docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V3_SESSION_B.v3.json",
  tournament: "docs/experiments/model-specialization/MODEL_TOURNAMENT_SESSION_C.v1.json",
  modelRuntime: "services/model-specialization-runtime/src/index.ts",
  patchRuntime: "services/patch-interface-runtime/src/index.ts",
  constraint: "services/code-formation-constraint/src/index.ts",
  matrix: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_SANITY_COMPARISON_MATRIX.v1.json",
  parserAudit: "benchmarks/model-specialization/CODE_FORMATION_PARSER_SCHEMA_AUDIT.v1.json",
  reachability: "benchmarks/model-specialization/CODE_FORMATION_TREATMENT_CONSTRAINT_REACHABILITY_REPORT.v1.json",
  decision: "benchmarks/model-specialization/CODE_FORMATION_SCIENTIFIC_VALIDITY_DECISION.v1.json",
  nextProtocol: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_GENERATION_PROTOCOL.v1.json",
  capability: "docs/experiments/model-specialization/CODE_FORMATION_CAPABILITY_RESEARCH_STATUS.v1.json",
  sessionC: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_SESSION_C.v1.json",
  indexC: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_RESULTS_INDEX.v4.json",
  validation: "docs/validation/2026-08-12-code-formation-constraint-session-c.md",
  observations: "docs/experiments/runs/code-formation-constraint-v1/paired-observations.jsonl",
  events: "docs/experiments/runs/code-formation-constraint-v1/call-events.jsonl"
} as const;

async function regular(relative: string) { const target = path.join(root, relative), stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Not regular: ${relative}`); return readFile(target); }
async function verified<T = any>(relative: string, expected?: string) { const body = await regular(relative), digest = sha256(body), sidecar = await regular(`${relative}.sha256`); if (sidecar.toString() !== `${digest}  ${path.basename(relative)}\n` || expected && digest !== expected) throw new Error(`Artifact drift: ${relative}`); return { value: JSON.parse(body.toString()) as T, sha256: digest, bytes: body.length }; }
async function publish(relative: string, value: unknown | string) { const body = typeof value === "string" ? value : `${JSON.stringify(value, null, 2)}\n`, digest = sha256(body), target = path.join(root, relative); await mkdir(path.dirname(target), { recursive: true }); try { const stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink() || await readFile(target, "utf8") !== body) throw new Error(`Immutable collision: ${relative}`); return { path: relative, sha256: digest, bytes: Buffer.byteLength(body) }; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } const pending = `${target}.next.${process.pid}.${randomUUID()}`, handle = await open(pending, "wx", 0o600); try { await handle.writeFile(body); await handle.sync(); } finally { await handle.close(); } try { await link(pending, target); } finally { await rm(pending, { force: true }); } await writeFile(`${target}.sha256`, `${digest}  ${path.basename(relative)}\n`, { flag: "wx", mode: 0o600 }); return { path: relative, sha256: digest, bytes: Buffer.byteLength(body) }; }

const [sessionB, indexB, resultsB, transitionsB, prereg, candidate, v3Prereg, v3SessionB, tournament] = await Promise.all([
  verified<any>(p.sessionB, "0cd2c2d8f94b152e5179698ccbb31b0a9088db94ae1274155e2a9b011f6e5581"), verified<any>(p.indexB, "fc859cf306a4c373def0dc95db7ddbdb8df48f703b4b39355b984158b7a83a87"), verified<any>(p.resultsB), verified<any>(p.transitionsB), verified<any>(p.prereg), verified<any>(p.candidate), verified<any>(p.v3Prereg), verified<any>(p.v3SessionB), verified<any>(p.tournament)
]);
const rows = (await regular(p.observations)).toString().trim().split("\n").map((line) => JSON.parse(line)), events = (await regular(p.events)).toString().trim().split("\n").map((line) => JSON.parse(line));
if (sessionB.value.status !== "PASS" || rows.length !== 80 || events.length !== 160 || sessionB.value.accounting.controlCalls !== 40 || sessionB.value.accounting.treatmentCalls !== 40 || sessionB.value.accounting.retries || sessionB.value.accounting.reviewers || transitionsB.value.counts["MODEL_FAILURE -> MODEL_FAILURE"] !== 40) throw new Error("Session-B immutable facts failed");

const systemSha = sha256(candidate.value.modelFacing.systemPrompt), schemaSha = sha256(JSON.stringify(candidate.value.interface.schema));
if (systemSha !== sha256(prereg.value.control.systemPrompt) || schemaSha !== sha256(JSON.stringify(prereg.value.schema))) throw new Error("Current prompt/schema drift");
const sourceHashes = Object.fromEntries(await Promise.all([p.currentRunner, p.currentMaterializer, p.historicalRunner, p.modelRuntime, p.patchRuntime, p.constraint].map(async (entry) => [entry, sha256(await regular(entry))])));
const historicalM2 = tournament.value.candidates.find((item: any) => item.candidateId === "M2"); if (!historicalM2) throw new Error("Historical M2 evidence missing");
const currentConfig = { systemPromptSha256: systemSha, schemaSha256: schemaSha, responseRuntimeSha256: sourceHashes[p.modelRuntime], p2NormalizerSha256: sourceHashes[p.patchRuntime], modelId: prereg.value.model.modelId, revision: prereg.value.model.revision, vllm: prereg.value.model.backendVersion, precision: prereg.value.model.precision, temperature: 0, requestSeed: prereg.value.seed, maxTokens: 2048, timeoutMs: 120000, retrievalDeclared: prereg.value.retrieval, contextDeclared: prereg.value.context, requestConstruction: "DIRECT_TASK_PLUS_SOURCE_NO_RETRIEVE_G3_CALL" };
const historicalConfig = { systemPromptSha256: systemSha, schemaSha256: schemaSha, responseRuntimeSha256: v3Prereg.value.entryGates.sourceClosure.entries.find((item: any) => item.path === p.modelRuntime).sha256, p2NormalizerSha256: v3Prereg.value.entryGates.sourceClosure.entries.find((item: any) => item.path === p.patchRuntime).sha256, modelId: v3Prereg.value.fixedVariables.modelId, revision: v3Prereg.value.fixedVariables.revision, vllm: v3Prereg.value.fixedVariables.vllm, precision: v3Prereg.value.fixedVariables.precision, temperature: v3Prereg.value.fixedVariables.temperature, requestSeed: v3Prereg.value.fixedVariables.seed, maxTokens: 2048, timeoutMs: 120000, retrievalDeclared: v3Prereg.value.fixedVariables.EMIN, contextDeclared: v3Prereg.value.fixedVariables.contextPackaging, requestConstruction: "retrieveG3(task,E-MIN-V2,2048).context_PLUS_FROZEN_P2_CONTRACT" };
const matrixRows = [
  ["model identity/revision", currentConfig.modelId === historicalConfig.modelId && currentConfig.revision === historicalConfig.revision, currentConfig.modelId, historicalConfig.modelId],
  ["serving backend", currentConfig.vllm === historicalConfig.vllm, currentConfig.vllm, historicalConfig.vllm],
  ["precision profile", currentConfig.precision === "FP8" && historicalConfig.precision === "FP8_PER_TENSOR_W8A8", currentConfig.precision, historicalConfig.precision],
  ["system prompt digest", currentConfig.systemPromptSha256 === historicalConfig.systemPromptSha256, currentConfig.systemPromptSha256, historicalConfig.systemPromptSha256],
  ["P2 action schema digest", currentConfig.schemaSha256 === historicalConfig.schemaSha256, currentConfig.schemaSha256, historicalConfig.schemaSha256],
  ["response extraction/structured-output runtime", currentConfig.responseRuntimeSha256 === historicalConfig.responseRuntimeSha256, currentConfig.responseRuntimeSha256, historicalConfig.responseRuntimeSha256],
  ["P2 parser/action validator", currentConfig.p2NormalizerSha256 === historicalConfig.p2NormalizerSha256, currentConfig.p2NormalizerSha256, historicalConfig.p2NormalizerSha256],
  ["temperature", currentConfig.temperature === historicalConfig.temperature, currentConfig.temperature, historicalConfig.temperature],
  ["max output and timeout", currentConfig.maxTokens === historicalConfig.maxTokens && currentConfig.timeoutMs === historicalConfig.timeoutMs, `${currentConfig.maxTokens}/${currentConfig.timeoutMs}`, `${historicalConfig.maxTokens}/${historicalConfig.timeoutMs}`],
  ["per-request generation seed", currentConfig.requestSeed === historicalConfig.requestSeed, currentConfig.requestSeed, historicalConfig.requestSeed],
  ["E-MIN-V2 retrieval implementation", false, currentConfig.requestConstruction, historicalConfig.requestConstruction],
  ["C1 context packaging implementation", false, currentConfig.contextDeclared, `${historicalConfig.contextDeclared} via retrieveG3`],
  ["P2 file/range/replacement contract presence", true, "PASS", "PASS"],
  ["strict JSON-schema response_format", true, "same sealed runtime", "same sealed runtime"],
  ["stop conditions", true, "same API defaults", "same API defaults"]
].map(([dimension, equivalent, current, historical]) => ({ dimension, equivalent, current, historical }));
const mismatches = matrixRows.filter((row) => !row.equivalent).map((row) => row.dimension);
const matrixRef = await publish(p.matrix, { schemaVersion: 1, status: "FAIL_CONTROL_NOT_EQUIVALENT_TO_KNOWN_GOOD", current: { sessionB: { path: p.sessionB, sha256: sessionB.sha256 }, config: currentConfig, normalizedConfigSha256: sha256(stable(currentConfig)) }, historical: { v3SessionB: { path: p.v3SessionB, sha256: v3SessionB.sha256 }, config: historicalConfig, normalizedConfigSha256: sha256(stable(historicalConfig)) }, rows: matrixRows, mismatches, requestIntentSemanticAudit: { structuredOutputContract: "PASS_API_JSON_SCHEMA_STRICT", p2ActionFormat: "PASS_SYSTEM_AND_SCHEMA", requiredFields: ["file", "start_line", "end_line", "replacement"], boundedFileRangeInstruction: "PASS", taskPromptAndSourcePresent: "PASS", frozenRetrievalAndContextRealization: "FAIL_BYPASSED_RETRIEVE_G3" }, conclusion: "Current CONTROL is not operationally equivalent to the nearest immutable working FIM/P2 path." });

const taxonomy = ["INVALID_JSON", "JSON_WRONG_SHAPE", "MISSING_ACTION", "WRONG_ACTION_TYPE", "MISSING_FILE", "INVALID_RANGE", "MISSING_REPLACEMENT", "SCHEMA_MISMATCH", "PARSER_MISMATCH", "EXPLICIT_REFUSAL_OR_REPORT_ONLY", "OUTPUT_TRUNCATION", "OTHER_DETERMINISTIC_VALIDATION_CAUSE", "UNOBSERVABLE_INSUFFICIENT_EVIDENCE"];
const zeroCounts = Object.fromEntries(taxonomy.map((name) => [name, name === "UNOBSERVABLE_INSUFFICIENT_EVIDENCE" ? 40 : 0]));
const parserRef = await publish(p.parserAudit, { schemaVersion: 1, status: "PASS_WITH_ATTRIBUTION_LIMIT", pipeline: ["model response", "response extraction", "JSON.parse", "P2 schema validation", "P2 action validation", "patch construction"], storedEvidence: ["outputSha256", "actionValid", "patchConstructed", "constraint code for treatment", "verification statuses"], notStored: ["raw response", "schemaValid", "model error enum", "finish reason", "normalization classification", "JSON parsed flag", "schema validated flag", "action-validation code", "normalizer error"], control: { observations: 40, observableEarliestBoundary: "NOT_VALID_EDIT_BEFORE_PATCH_CONSTRUCTION", exactReasonCounts: zeroCounts }, treatment: { observations: 40, observableEarliestBoundary: "BASE_P2_REJECTED_BEFORE_FORMATION_CHECKS", exactReasonCounts: zeroCounts, constraintCodes: { BASE_P2_REJECTED: 40 } }, conclusion: "Exact JSON/schema/action rejection causes are not identifiable from retained Session-B evidence; model semantics must not be inferred from hashes." });

const reachabilityRef = await publish(p.reachability, { schemaVersion: 1, status: "PASS_NOT_REACHED", implementation: { constraintSource: { path: p.constraint, sha256: sourceHashes[p.constraint] }, runnerSource: { path: p.currentRunner, sha256: sourceHashes[p.currentRunner] }, order: ["runner performs base normalizePatchInterfaceOutput(P2)", "treatment invokes applyCodeFormationConstraint", "constraint repeats base P2 normalization", "only VALID_EDIT proceeds to empty/whitespace/fence/NUL/module-boundary/whole-source-parse formation checks"] }, answers: { applicationPoint: "AFTER_BASE_P2_NORMALIZATION_ATTEMPT; formation-specific rules execute only after a valid P2 edit", sameRuleForAllTreatmentRejections: true, rejectionRule: "BASE_P2_REJECTED", rejectionCount: 40, validP2CandidatesReceived: 0, formationSpecificChecksReached: 0, hypothesisStageReached: false, currentRunActuallyTested: "UPSTREAM_ACTION_REPRESENTATION_REJECTION_ONLY" }, formationEffectIdentifiability: "NOT_IDENTIFIABLE_UPSTREAM_ACTION_COLLAPSE" });

const historicalEvidence = [
  { source: { path: p.v3SessionB, sha256: v3SessionB.sha256 }, population: "different 80-task privacy-safe observability V3 population", validActions: 80, tasks: 80, rate: 1, strictSuccess: 36 },
  { source: { path: p.tournament, sha256: tournament.sha256 }, population: "different 95-task practical local model tournament M2 population", validActions: historicalM2.capability.validActions, tasks: historicalM2.capability.mutationTasks, rate: historicalM2.capability.validActions / historicalM2.capability.mutationTasks, strictSuccess: historicalM2.capability.behavioralSuccesses }
];
const decisionRef = await publish(p.decision, { schemaVersion: 1, experimentId: "CODE_FORMATION_CONSTRAINT_EXPERIMENT", status: "INVALID_UPSTREAM_CONTROL_COLLAPSE", formationEffectIdentifiability: "NOT_IDENTIFIABLE_UPSTREAM_ACTION_COLLAPSE", primaryFacts: { controlValidActions: 0, treatmentValidActions: 0, formationCandidatesEvaluated: 0, pairedTransitions: { "MODEL_FAILURE -> MODEL_FAILURE": 40 } }, controlSanity: { result: "FAIL", matrix: matrixRef, provenConfigurationDefects: ["E-MIN-V2/C1 implementation bypassed retrieveG3 and directly concatenated task plus source", "counterbalancing seed 20260812 was reused as per-request generation seed instead of frozen FIM request seed 20260809"], exactCollapseMechanism: "INCONCLUSIVE_BECAUSE_STAGE_TELEMETRY_WAS_NOT_RETAINED" }, rootCauseClass: "MULTIPLE_UPSTREAM_CONFIGURATION_DEFECTS", parserSchemaAttribution: parserRef, treatmentReachability: reachabilityRef, historicalActionValiditySanity: { conclusion: "0/40 is qualitatively inconsistent with previously demonstrated FIM/P2 action validity, but populations differ and no cross-population statistical equivalence is claimed.", evidence: historicalEvidence }, treatmentEffectMetrics: { syntaxDifference: "NOT_INTERPRETABLE_FOR_FORMATION_EFFECT", visibleDifference: "NOT_INTERPRETABLE_FOR_FORMATION_EFFECT", hiddenDifference: "NOT_INTERPRETABLE_FOR_FORMATION_EFFECT", strictBehavioralDifference: "NOT_INTERPRETABLE_FOR_FORMATION_EFFECT", pairedFormationGain: "NOT_INTERPRETABLE_FOR_FORMATION_EFFECT" }, productStatus: "KEEP_MUTATION_DISABLED", modelPromotionChanged: false, tasksExposed: 40, exposedTasksMayBeReusedAsFreshEvidence: false });

const nextProtocolRef = await publish(p.nextProtocol, { schemaVersion: 1, protocolId: "dca-code-formation-control-recovery-generation-v1", state: "PREPARED_NOT_EXECUTED", selectedNextStep: "CODE_FORMATION_CONTROL_RECOVERY_GENERATION", purpose: "One final fresh generation may test the formation intervention only after restoring a known-good FIM/P2 control path.", historicalEvidencePolicy: { preserveSessionBAppendOnly: true, current40TasksDiagnosticOnly: true, current40TasksForbiddenAsFreshPrimaryEvidence: true }, requiredFreshPopulation: "NEW_TARGET_MODEL_UNSEEN_REPOSITORY_AND_TASK_DISJOINT_FIXTURES", frozenControlRecovery: { retrievalImplementation: "retrieveG3(task, E-MIN-V2, 2048)", contextPackaging: "C1 from retrieveG3 output", requestGenerationSeed: 20260809, scheduleSeed: "SEPARATE_PREREGISTERED_RANDOMIZATION_SEED_NOT_USED_FOR_MODEL_DECODING", systemPromptSha256: systemSha, p2SchemaSha256: schemaSha, modelRuntimeSha256: sourceHashes[p.modelRuntime], p2NormalizerSha256: sourceHashes[p.patchRuntime], modelId: historicalConfig.modelId, revision: historicalConfig.revision, precision: historicalConfig.precision, vllm: historicalConfig.vllm, temperature: 0, maxTokens: 2048, timeoutMs: 120000 }, requiredZeroCallGates: ["CONTROL normalized configuration hash equals known-good historical FIM/P2 configuration", "retrieveG3 invocation and C1 context lineage present", "request seed is distinct from schedule seed", "all fresh request intents materialize", "source closure and empty ledgers pass"], requiredStageTelemetryNoRawContent: ["schemaValid", "bounded model error enum", "finish-reason category", "output-empty flag", "output-length bucket", "normalization classification", "jsonParsed", "schemaValidated", "action-validation code", "patch-construction code"], optionalFutureNonPrimarySmoke: { allowedOnlyIfSeparatelyPreregistered: true, scoredTasksForbidden: true, fixture: "non-primary deterministic fixture", requiredOutcome: "at least one valid P2 action before primary calls" }, conditions: ["KNOWN_GOOD_CONTROL", "KNOWN_GOOD_CONTROL_PLUS_SAME_FORMATION_CONSTRAINT"], retry: false, reviewer: false, L2: false, executionNow: false, stopRule: "This is the final capability-research recovery branch; if its control sanity gate cannot be established or the fresh generation is invalid, retire code-formation research without opening an unrelated branch." });
const capabilityRef = await publish(p.capability, { schemaVersion: 1, status: "FINAL_CAPABILITY_RESEARCH_BRANCH_RECOVERY_PROTOCOL_ONLY", currentExperiment: { scientificValidity: "INVALID_UPSTREAM_CONTROL_COLLAPSE", formationEffect: "NOT_INTERPRETABLE_FOR_FORMATION_EFFECT", productStatus: "KEEP_MUTATION_DISABLED" }, selectedNextStep: { id: "CODE_FORMATION_CONTROL_RECOVERY_GENERATION", protocol: nextProtocolRef, executionAuthorized: false }, boundaries: { unrelatedResearchBranchesAuthorized: false, productMutationEnabled: false, FIMPromotionChanged: false, current40TasksRetiredFromFreshEvidence: true } });

const commands: Array<{ command: string; stdoutSha256: string; stderrSha256: string }> = [];
for (const [file, args] of [["npx", ["tsc", "--ignoreConfig", "--types", "node", "--noEmit", "--strict", "--module", "ESNext", "--moduleResolution", "Bundler", "--target", "ES2022", "--skipLibCheck", "scripts/analyze_code_formation_constraint_session_c.ts"]], ["npm", ["run", "typecheck"]], ["npm", ["run", "test"]], ["npm", ["run", "build"]], ["npm", ["run", "validate:design"]]] as Array<[string, string[]]>) { const output = await exec(file, args, { cwd: root, timeout: 600_000, maxBuffer: 40_000_000 }); commands.push({ command: [file, ...args].join(" "), stdoutSha256: sha256(output.stdout), stderrSha256: sha256(output.stderr) }); }
const sourceClosure = { entries: [{ path: "scripts/analyze_code_formation_constraint_session_c.ts", sha256: sha256(await regular("scripts/analyze_code_formation_constraint_session_c.ts")) }] };
const sessionCRef = await publish(p.sessionC, { schemaVersion: 1, experimentId: "CODE_FORMATION_CONSTRAINT_EXPERIMENT", session: "C", status: "PASS", classification: "ZERO_CALL_CONTROL_SANITY_AND_SCIENTIFIC_VALIDITY_DECISION", completedAt: new Date().toISOString(), inputs: { sessionB: { path: p.sessionB, sha256: sessionB.sha256 }, resultsIndex: { path: p.indexB, sha256: indexB.sha256 }, pairedResults: { path: p.resultsB, sha256: resultsB.sha256 }, transitions: { path: p.transitionsB, sha256: transitionsB.sha256 } }, artifacts: { controlSanityMatrix: matrixRef, parserSchemaAudit: parserRef, treatmentReachability: reachabilityRef, scientificValidityDecision: decisionRef, nextStepProtocol: nextProtocolRef, capabilityResearchStatus: capabilityRef }, conclusions: { formationEffectIdentifiability: "NOT_IDENTIFIABLE_UPSTREAM_ACTION_COLLAPSE", rootCauseClass: "MULTIPLE_UPSTREAM_CONFIGURATION_DEFECTS", scientificValidity: "INVALID_UPSTREAM_CONTROL_COLLAPSE", formationEffect: "NOT_INTERPRETABLE_FOR_FORMATION_EFFECT", productStatus: "KEEP_MUTATION_DISABLED", selectedNextStep: "CODE_FORMATION_CONTROL_RECOVERY_GENERATION" }, validation: { status: "PASS", commands, targetModelCalls: 0, vllmStarts: 0, port8000Clear: true, gpuAllocationMiB: 0, ephemeralStateAbsent: true }, sourceClosure, nextExperimentExecuted: false, stop: "SESSION_C_BOUNDARY_REACHED" });
const indexCRef = await publish(p.indexC, { schemaVersion: 4, experimentId: "CODE_FORMATION_CONSTRAINT_EXPERIMENT", state: "SESSION_C_COMPLETE_INVALID_UPSTREAM_CONTROL_COLLAPSE", updatedAt: new Date().toISOString(), artifacts: { sessionB: { path: p.sessionB, sha256: sessionB.sha256 }, sessionC: sessionCRef, decision: decisionRef, controlSanityMatrix: matrixRef, parserSchemaAudit: parserRef, reachability: reachabilityRef, nextStepProtocol: nextProtocolRef, capabilityResearchStatus: capabilityRef }, formationEffect: "NOT_INTERPRETABLE_FOR_FORMATION_EFFECT", productStatus: "KEEP_MUTATION_DISABLED", nextStep: "CODE_FORMATION_CONTROL_RECOVERY_GENERATION_PROTOCOL_ONLY", modelCallsSessionC: 0 });
const validation = `# Code Formation Constraint Experiment — Session C Validation\n\nStatus: **PASS**\n\n- Session-B SHA and results-index SHA: PASS\n- Physical lineage: 80 calls, 40/40 conditions, 40 pairs, zero retries/reviewers/infrastructure-call failures\n- Formation-effect identifiability: NOT_IDENTIFIABLE_UPSTREAM_ACTION_COLLAPSE\n- CONTROL sanity: FAIL (retrieveG3/C1 bypass and request-seed mismatch)\n- Exact response rejection attribution: UNOBSERVABLE_INSUFFICIENT_EVIDENCE (40/40 each arm)\n- Treatment formation-specific checks reached: 0/40\n- Scientific validity: INVALID_UPSTREAM_CONTROL_COLLAPSE\n- Formation effect: NOT_INTERPRETABLE_FOR_FORMATION_EFFECT\n- Product status: KEEP_MUTATION_DISABLED\n- Selected next step: CODE_FORMATION_CONTROL_RECOVERY_GENERATION protocol only\n- Strict TypeScript, full tests, typecheck, build, and design validation: PASS\n- Session-C model calls/vLLM starts/GPU allocation: 0/0/0\n- Session-C artifact: \`${sessionCRef.sha256}\`\n- Results index: \`${indexCRef.sha256}\`\n`;
const validationRef = await publish(p.validation, validation);
process.stdout.write(`${JSON.stringify({ status: "PASS", sessionC: sessionCRef, index: indexCRef, validation: validationRef, decision: decisionRef, rootCauseClass: "MULTIPLE_UPSTREAM_CONFIGURATION_DEFECTS", scientificValidity: "INVALID_UPSTREAM_CONTROL_COLLAPSE", formationEffect: "NOT_INTERPRETABLE_FOR_FORMATION_EFFECT", nextStep: "CODE_FORMATION_CONTROL_RECOVERY_GENERATION" })}\n`);
