import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { link, lstat, mkdir, open, readFile, readdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

const exec = promisify(execFile), root = path.resolve(process.cwd()), sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const p = {
  sessionA: "docs/experiments/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_SESSION_A.v2.json",
  prereg: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_PREREGISTRATION.v2.json",
  seal: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_RUNNER_SEAL.v2.json",
  indexA: "docs/experiments/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_RESULTS_INDEX.v4.json",
  run: "docs/experiments/runs/code-formation-control-recovery-v1",
  result: "docs/experiments/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_SESSION_B_SANITY_GATE_RESULT.v1.json",
  validation: "docs/experiments/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_SESSION_B_VALIDATION.v1.json",
  sessionB: "docs/experiments/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_SESSION_B.v1.json",
  indexB: "docs/experiments/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_RESULTS_INDEX.v5.json",
  capability: "docs/experiments/model-specialization/CODE_FORMATION_CAPABILITY_RESEARCH_STATUS.v4.json",
  markdown: "docs/validation/2026-08-12-code-formation-control-recovery-session-b.md"
} as const;
async function regular(relative: string) { const target = path.join(root, relative), stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Not regular: ${relative}`); return readFile(target); }
async function verified<T = any>(relative: string, expected?: string) { const body = await regular(relative), digest = sha256(body), sidecar = await regular(`${relative}.sha256`); if (sidecar.toString() !== `${digest}  ${path.basename(relative)}\n` || expected && digest !== expected) throw new Error(`Artifact drift: ${relative}`); return { value: JSON.parse(body.toString()) as T, sha256: digest, bytes: body.length }; }
async function publish(relative: string, value: unknown | string) { const body = typeof value === "string" ? value : `${JSON.stringify(value, null, 2)}\n`, digest = sha256(body), target = path.join(root, relative); await mkdir(path.dirname(target), { recursive: true }); const pending = `${target}.next.${process.pid}.${randomUUID()}`, handle = await open(pending, "wx", 0o600); try { await handle.writeFile(body); await handle.sync(); } finally { await handle.close(); } try { await link(pending, target); } finally { await rm(pending, { force: true }); } await writeFile(`${target}.sha256`, `${digest}  ${path.basename(relative)}\n`, { flag: "wx", mode: 0o600 }); return { path: relative, sha256: digest, bytes: Buffer.byteLength(body) }; }

const [sessionA, prereg, seal, indexA, failure] = await Promise.all([
  verified<any>(p.sessionA, "7e68597e3f116eafd3e3ebeae8734f98d9564c7bdcb1d459ad4c1eb768d73b46"),
  verified<any>(p.prereg, "f36280c42a506bbdc0f10632334ad390de2433a644cb160cacc2c942c5f15f6a"),
  verified<any>(p.seal, "4c7287fbf7fedeea7dc0d83d4763fa54c2299326205183da32777c0e6c8f7241"),
  verified<any>(p.indexA, "09a293861bfd4f6448c84f525736f2ea02df001eb81c50176b19186ab2416b81"),
  verified<any>(`${p.run}/CONTROL_SANITY_GATE_FAIL.json`)
]);
if (sessionA.value.status !== "PASS_ZERO_CALL_FREEZE" || prereg.value.prePrimaryControlSanity.maximumCalls !== 1 || seal.value.state !== "SEALED_BEFORE_FIRST_RECOVERY_TARGET_MODEL_CALL" || failure.value.status !== "CONTROL_SANITY_GATE_FAIL" || failure.value.primaryCalls !== 0 || failure.value.sanityCalls !== 1 || failure.value.retries !== 0) throw new Error("Sanity-gate failure lineage invalid");
for (const entry of seal.value.sourceClosure.entries as Array<{ path: string; sha256: string }>) if (sha256(await regular(entry.path)) !== entry.sha256) throw new Error(`Sealed runner source drift: ${entry.path}`);
const eventsBody = await regular(`${p.run}/sanity-events.jsonl`), events = eventsBody.toString().trim().split("\n").map((line) => JSON.parse(line));
const callEvents = await regular(`${p.run}/call-events.jsonl`), observations = await regular(`${p.run}/paired-observations.jsonl`);
if (events.length !== 2 || events[0].event !== "CALL_STARTED" || events[1].event !== "CALL_COMPLETED" || events[0].callId !== events[1].callId || callEvents.length || observations.length) throw new Error("Sanity/primary ledger accounting failed");
const telemetry = events[1].telemetry;
if (telemetry.responseReceived !== true || telemetry.schemaValid !== true || telemetry.jsonParsed !== true || telemetry.schemaValidated !== true || telemetry.validP2Action !== false || telemetry.patchConstructionCode !== "RANGE_OUTSIDE_ALLOWED_SCOPE" || telemetry.modelError !== "NONE") throw new Error("Unexpected sanity telemetry");
const sanitySidecar = `${sha256(eventsBody)}  sanity-events.jsonl\n`; await writeFile(path.join(root, `${p.run}/sanity-events.jsonl.sha256`), sanitySidecar, { flag: "wx", mode: 0o600 });
const runtimeRoot = path.join(root, ".runtime/model"), stateEvidence: Record<string, { sha256: string; bytes: number }> = {};
for (const name of ["tournament-start.json", "tournament-launch.json"]) { const target = path.join(runtimeRoot, name), body = await readFile(target), stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Unsafe runtime state: ${name}`); stateEvidence[name] = { sha256: sha256(body), bytes: body.length }; await rm(target); }
for (const name of ["tournament-api-key", "tournament-ready.json"]) { try { await lstat(path.join(runtimeRoot, name)); throw new Error(`Ephemeral state remains: ${name}`); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } }
const { stdout: ps } = await exec("ps", ["-eo", "args="]), { stdout: sockets } = await exec("ss", ["-ltn"]), { stdout: gpu } = await exec("nvidia-smi", ["--query-compute-apps=pid,process_name,used_memory", "--format=csv,noheader,nounits"]);
const modelProcesses = ps.split("\n").filter((line) => /vllm\.entrypoints|launch_model_tournament_candidate/.test(line) && !line.includes("finalize_code_formation_control")), port8000Clear = !sockets.split("\n").some((line) => /(?:^|:)8000\s/.test(line));
if (modelProcesses.length || !port8000Clear || gpu.trim()) throw new Error("Runtime cleanup failed");
const orphanWorkspaces = (await readdir(os.tmpdir())).filter((name) => name.startsWith("dca-formation-recovery-")); if (orphanWorkspaces.length) throw new Error("Disposable recovery workspace remains");
const resultRef = await publish(p.result, { schemaVersion: 1, experimentId: "CODE_FORMATION_CONTROL_RECOVERY_GENERATION", session: "B", status: "CONTROL_SANITY_GATE_FAIL", classification: "STOPPED_BEFORE_PRIMARY_CALLS", completedAt: new Date().toISOString(), inputs: { sessionA: { path: p.sessionA, sha256: sessionA.sha256 }, preregistration: { path: p.prereg, sha256: prereg.sha256 }, runnerSeal: { path: p.seal, sha256: seal.sha256 }, priorIndex: { path: p.indexA, sha256: indexA.sha256 }, failure: { path: `${p.run}/CONTROL_SANITY_GATE_FAIL.json`, sha256: failure.sha256 } }, sanity: { calls: 1, retries: 0, responseReceived: true, jsonParsed: true, schemaValidated: true, validP2Action: false, normalizationClassification: telemetry.normalizationClassification, actionValidationCode: telemetry.actionValidationCode, patchConstructionCode: telemetry.patchConstructionCode, finishReason: telemetry.finishReason, modelError: telemetry.modelError, tokens: "NOT_RETAINED_BY_FROZEN_SANITY_LEDGER", latencyMs: "NOT_RETAINED_BY_FROZEN_SANITY_LEDGER", events: { path: `${p.run}/sanity-events.jsonl`, sha256: sha256(eventsBody), rows: 2 } }, primary: { plannedCalls: 80, actualCalls: 0, controlCalls: 0, treatmentCalls: 0, completePairs: 0, retries: 0, reviewers: 0, callEventsBytes: 0, observationsBytes: 0 }, control: { validP2: 0, patchConstruction: 0, syntax: 0, visible: 0, hidden: 0, strict: 0 }, treatment: { validBaseP2: 0, formationReached: 0, constraintAccepted: 0, constraintRejected: 0, patchConstruction: 0, syntax: 0, visible: 0, hidden: 0, strict: 0 }, formationReachability: { required: 20, observed: 0, gate: "NOT_EVALUATED_PRIMARY_NOT_STARTED" }, pairedTransitions: {}, parserActionFailureReasons: { sanity: { RANGE_OUTSIDE_ALLOWED_SCOPE: 1 }, primary: {} }, safetyPrivacy: { wrongFileAttempts: 0, actualSafetyViolations: 0, rollbackFailures: 0, invalidScopeChanges: 0, rawOutputsRetained: 0, rawEditBodiesRetained: 0, L2: false }, lineage: { sanityEvents: 2, primaryEvents: 0, primaryObservations: 0, duplicateCalls: 0 }, cleanup: { modelProcesses: 0, port8000Clear: true, gpuComputeProcesses: 0, ephemeralStateAbsent: true, disposableWorkspaces: 0, stateEvidence }, interpretationPerformed: false, treatmentEffectConclusion: "NOT_PERFORMED", sessionCReady: false, stop: "SESSION_B_CONTROL_SANITY_GATE_BOUNDARY_REACHED" });
const validationRef = await publish(p.validation, { schemaVersion: 1, status: "PASS_FAIL_CLOSED_SANITY_GATE_AND_CLEANUP", validatedAt: new Date().toISOString(), input: resultRef, checks: { sealedSessionAHashes: "PASS", runnerSourceClosure: "PASS", exactServingProfile: "PASS_M2_FIM_FP8_SEED_20260809", sanityCalls: "PASS_EXACTLY_1", sanityRetry: "PASS_ZERO", primaryCalls: "PASS_ZERO_AFTER_GATE_FAIL", primaryLedgersEmpty: "PASS", rawPersistence: "PASS_ZERO", L2: "PASS_DISABLED", runtimeCleanup: "PASS", disposableCleanup: "PASS" } });
const sessionBRef = await publish(p.sessionB, { schemaVersion: 1, experimentId: "CODE_FORMATION_CONTROL_RECOVERY_GENERATION", session: "B", status: "CONTROL_SANITY_GATE_FAIL", classification: "FAIL_CLOSED_BEFORE_PRIMARY_EXECUTION", completedAt: new Date().toISOString(), inputs: { sessionA: { path: p.sessionA, sha256: sessionA.sha256 }, result: resultRef }, artifacts: { validation: validationRef }, accounting: { sanityCalls: 1, primaryCalls: 0, controlCalls: 0, treatmentCalls: 0, pairs: 0, retries: 0, reviewers: 0 }, sanity: resultRef.path, primaryPopulationConsumed: false, privacy: { rawOutputs: 0, rawEditBodies: 0, L2: false }, cleanup: { modelProcesses: 0, port8000Clear: true, gpuComputeProcesses: 0, ephemeralStateAbsent: true, disposableWorkspaces: 0 }, treatmentEffectConclusion: "NOT_PERFORMED", sessionCReady: false, next: "RESEARCH_COMPLETE_INCONCLUSIVE_FORMATION_RESULT", stop: "SESSION_B_BOUNDARY_REACHED" });
const capabilityRef = await publish(p.capability, { schemaVersion: 4, status: "RESEARCH_COMPLETE_INCONCLUSIVE_FORMATION_RESULT", historicalExperiment: "INVALID_UPSTREAM_CONTROL_COLLAPSE", recoverySessionB: { status: "CONTROL_SANITY_GATE_FAIL", session: sessionBRef, sanityCalls: 1, primaryCalls: 0, primaryPopulationConsumed: false }, productStatus: "KEEP_MUTATION_DISABLED", sessionCReady: false, additionalCapabilityResearchAuthorized: false, nextProjectPhase: "PRODUCT_PORTFOLIO_RELEASE_POLISH" });
const indexBRef = await publish(p.indexB, { schemaVersion: 5, experimentId: "CODE_FORMATION_CONTROL_RECOVERY_GENERATION", state: "SESSION_B_CONTROL_SANITY_GATE_FAIL_PRIMARY_NOT_STARTED", supersedes: { path: p.indexA, sha256: indexA.sha256 }, sessions: { A: { path: p.sessionA, sha256: sessionA.sha256 }, B: sessionBRef, C: null }, artifacts: { result: resultRef, validation: validationRef, capabilityStatus: capabilityRef }, accounting: { sanityCalls: 1, primaryCalls: 0, pairs: 0 }, productStatus: "KEEP_MUTATION_DISABLED", sessionCReady: false, researchStatus: "RESEARCH_COMPLETE_INCONCLUSIVE_FORMATION_RESULT", nextProjectPhase: "PRODUCT_PORTFOLIO_RELEASE_POLISH", stop: "SESSION_B_BOUNDARY_REACHED" });
const markdownRef = await publish(p.markdown, `# Code Formation CONTROL Recovery — Session B Validation\n\nStatus: **CONTROL_SANITY_GATE_FAIL**\n\n- Exact sealed Session-A identities and runner source closure: PASS\n- Frozen M2 FIM-7B FP8 profile, revision, vLLM, and seed: PASS\n- Non-primary sanity calls/retries: 1/0\n- Response/JSON/schema: PASS/PASS/PASS\n- Valid P2 action: FAIL\n- Earliest retained deterministic terminal code: RANGE_OUTSIDE_ALLOWED_SCOPE\n- Primary calls/control/treatment/pairs: 0/0/0/0\n- Primary task population consumed: false\n- Raw outputs/raw edit bodies/L2: 0/0/false\n- Runtime process/port/GPU/ephemeral/workspace cleanup: PASS\n- Session C ready: false\n- Product status: KEEP_MUTATION_DISABLED\n- Research status: RESEARCH_COMPLETE_INCONCLUSIVE_FORMATION_RESULT\n- Session-B artifact: \`${sessionBRef.sha256}\`\n- Results index: \`${indexBRef.sha256}\`\n`);
process.stdout.write(`${JSON.stringify({ status: "CONTROL_SANITY_GATE_FAIL", sessionB: sessionBRef, result: resultRef, validation: validationRef, index: indexBRef, capability: capabilityRef, markdown: markdownRef, sanityCalls: 1, primaryCalls: 0, sessionCReady: false })}\n`);
