import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { link, lstat, mkdir, open, readFile, readdir, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { validateL1EvidenceV2 } from "../services/semantic-observability-v2/src/index";

const exec = promisify(execFile), root = path.resolve(process.cwd()), recordedAt = new Date().toISOString(), run = "docs/experiments/runs/privacy-safe-observability-v2", sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
async function regular(relative: string) { const target = path.join(root, relative), stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Not regular: ${relative}`); return readFile(target); }
async function verified<T = any>(relative: string, expected?: string) { const bytes = await regular(relative), digest = sha256(bytes), sidecar = await regular(`${relative}.sha256`); if (sidecar.toString() !== `${digest}  ${path.basename(relative)}\n` || expected && digest !== expected) throw new Error(`Artifact drift: ${relative}`); return { path: relative, sha256: digest, value: JSON.parse(bytes.toString()) as T }; }
async function publishBytes(relative: string, body: string) { const target = path.join(root, relative); await mkdir(path.dirname(target), { recursive: true }); try { const stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink() || await readFile(target, "utf8") !== body) throw new Error(`Immutable collision: ${relative}`); return; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } const pending = `${target}.next.${process.pid}.${randomUUID()}`, handle = await open(pending, "wx", 0o600); try { await handle.writeFile(body); await handle.sync(); } finally { await handle.close(); } try { await link(pending, target); } finally { await rm(pending, { force: true }); } }
async function publish(relative: string, value: unknown) { const body = `${JSON.stringify(value, null, 2)}\n`, digest = sha256(body); await publishBytes(relative, body); await publishBytes(`${relative}.sha256`, `${digest}  ${path.basename(relative)}\n`); return { path: relative, sha256: digest }; }
async function lines(relative: string) { return (await regular(relative)).toString().split("\n").filter(Boolean).map((line) => JSON.parse(line)); }
async function command(file: string, args: string[], timeout = 600_000) { const result = await exec(file, args, { cwd: root, timeout, maxBuffer: 40_000_000 }); return { command: [file, ...args].join(" "), exitCode: 0, stdoutSha256: sha256(result.stdout), stderrSha256: sha256(result.stderr) }; }

const sessionA = await verified<any>("docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V2_SESSION_A.v2.json", "c4bae265ebdac2f658a94e1032628df350810c58ba47e10dceb6e75164f7c77d");
const prereg = await verified<any>("benchmarks/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_PREREGISTRATION.v2.json", "10a830c2f24aac861de17df007c38cfb577df26136fcd1aa6c778b38e503e407");
const seal = await verified<any>("benchmarks/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V2_SESSION_B_RUNNER_SEAL.v2.json");
const dry = await verified<any>("benchmarks/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V2_SESSION_B_DRY_RUN.v2.json");
const manifest = await verified<any>("benchmarks/model-specialization/PRIVACY_SAFE_OBSERVABILITY_TASK_MANIFEST.v2.json");
if (sessionA.value.status !== "PASS" || prereg.value.state !== "SEALED_BEFORE_FIRST_V2_TARGET_MODEL_CALL" || dry.value.status !== "PASS_ZERO_TARGET_MODEL_CALLS" || manifest.value.tasks.length !== 80) throw new Error("V2 frozen inputs invalid");
for (const entry of seal.value.sourceClosure.entries) { const bytes = await regular(entry.path); if (sha256(bytes) !== entry.sha256 || bytes.length !== entry.bytes) throw new Error(`V2 source drift: ${entry.path}`); }
const eventPath = `${run}/call-events.jsonl`, checkpointPath = `${run}/observations.checkpoint.jsonl`, events = await lines(eventPath), rows = await lines(checkpointPath);
if (events.length !== 28 || rows.length !== 13 || events.filter((row) => row.event === "CALL_STARTED").length !== 14 || events.filter((row) => row.event === "CALL_COMPLETED").length !== 13 || events.filter((row) => row.event === "CALL_FAILED_PRE_RESPONSE").length !== 1) throw new Error("V2 partial accounting mismatch");
let leaks = 0, safetyViolations = 0, rollbackFailures = 0, schemaFailures = 0;
for (let index = 0; index < rows.length; index++) {
  const row = rows[index], started = events[index * 2], terminal = events[index * 2 + 1];
  if (started.event !== "CALL_STARTED" || terminal.event !== "CALL_COMPLETED" || started.index !== index || terminal.index !== index || row.index !== index || row.taskId !== manifest.value.tasks[index].task_id || row.physicalCallId !== started.physicalCallId || row.physicalCallId !== terminal.physicalCallId || row.requestSha256 !== started.requestSha256 || row.requestSha256 !== terminal.requestSha256 || terminal.observationSha256 !== sha256(JSON.stringify(row))) throw new Error(`V2 event/row lineage mismatch: ${index}`);
  const l0Bytes = await regular(row.L0.path), l1Bytes = await regular(row.L1.path), l0Sidecar = await regular(`${row.L0.path}.sha256`), l1Sidecar = await regular(`${row.L1.path}.sha256`);
  if (sha256(l0Bytes) !== row.L0.sha256 || sha256(l1Bytes) !== row.L1.sha256 || l0Sidecar.toString() !== `${row.L0.sha256}  ${path.basename(row.L0.path)}\n` || l1Sidecar.toString() !== `${row.L1.sha256}  ${path.basename(row.L1.path)}\n`) throw new Error(`V2 packet sidecar mismatch: ${index}`);
  const l0 = JSON.parse(l0Bytes.toString()), l1 = JSON.parse(l1Bytes.toString()); if (JSON.stringify(l0.identity) !== JSON.stringify(l1.identity) || l0.identity.physicalCallId !== row.physicalCallId || l0.identity.requestSha256 !== row.requestSha256 || l0.identity.actionIdentitySha256 !== row.outputSha256) throw new Error(`V2 same-call pair mismatch: ${index}`);
  try { validateL1EvidenceV2(l1.evidence); } catch { schemaFailures++; }
  const serialized = l0Bytes.toString() + l1Bytes.toString(); if (/sk-[A-Za-z0-9]{12,}|hf_[A-Za-z0-9]{12,}/u.test(serialized)) leaks++;
  if (row.execution.actualSafetyViolation) safetyViolations++; if (row.execution.rollback !== "PASS") rollbackFailures++;
}
const failure = events.at(-1); if (failure.event !== "CALL_FAILED_PRE_RESPONSE" || failure.index !== 13 || failure.taskId !== manifest.value.tasks[13].task_id || rows.some((row) => row.index >= 13)) throw new Error("V2 terminal failure boundary mismatch");
if (leaks || safetyViolations || rollbackFailures || schemaFailures || (await readdir(path.join(root, `${run}/l0`))).filter((name) => name.endsWith(".json")).length !== 13 || (await readdir(path.join(root, `${run}/restricted-l1`))).filter((name) => name.endsWith(".json")).length !== 13) throw new Error("V2 partial pair/privacy/safety validation failed");

const runtime = path.join(root, ".runtime/model"), states: Record<string, { sha256: string; bytes: number }> = {};
for (const name of ["tournament-start.json", "tournament-launch.json"]) { const relative = `.runtime/model/${name}`, bytes = await regular(relative); states[name] = { sha256: sha256(bytes), bytes: bytes.length }; await rm(path.join(runtime, name)); }
for (const name of ["tournament-api-key", "observability-v2-hmac-key", "tournament-ready.json"]) try { await lstat(path.join(runtime, name)); throw new Error(`Ephemeral state remains: ${name}`); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; }
const { stdout: processes } = await exec("ps", ["-eo", "args="]), { stdout: sockets } = await exec("ss", ["-ltn"]), { stdout: gpu } = await exec("nvidia-smi", ["--query-compute-apps=pid,process_name,used_memory", "--format=csv,noheader,nounits"]);
const modelProcesses = processes.split("\n").filter((line) => /vllm\.entrypoints|launch_model_tournament_candidate/u.test(line) && !line.includes("finalize_privacy_safe")), port8000Clear = !sockets.split("\n").some((line) => /(?:^|:)8000\s/u.test(line));
if (modelProcesses.length || !port8000Clear || gpu.trim() || (await readdir(os.tmpdir())).some((name) => name.startsWith("dca-observability-v2-"))) throw new Error("V2 cleanup incomplete");
const commands = [await command("npx", ["tsc", "--ignoreConfig", "--noEmit", "--strict", "--skipLibCheck", "--target", "ES2022", "--module", "ESNext", "--moduleResolution", "Bundler", "--allowSyntheticDefaultImports", "--types", "node", "scripts/finalize_privacy_safe_observability_v2_session_b_abort.ts"]), await command("npm", ["run", "typecheck"]), await command("npm", ["run", "test", "--", "--testTimeout=15000"]), await command("npm", ["run", "build"]), await command("npm", ["run", "validate:design"])];
const accounting = { plannedPhysicalCalls: 80, consumedPhysicalCalls: 14, completedResponses: 13, completeL0L1Pairs: 13, failedBeforePacketGeneration: 1, uncalledTasks: 66, retries: 0, reviewerCalls: 0, SessionBComplete: false, SessionBPass: false };
const abortRef = await publish("docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V2_SESSION_B_PARTIAL_ABORT.v2.json", { schemaVersion: 2, abortId: "dca-privacy-safe-semantic-observability-v2-session-b-partial-abort", status: "ABORTED_FAIL_CLOSED_AFTER_CONSUMED_CALL", classification: "RUNNER_REPORTED_PRE_RESPONSE_TRANSPORT_FAILURE_NO_RETRY", recordedAt, inputs: { sessionA: { path: sessionA.path, sha256: sessionA.sha256 }, preregistration: { path: prereg.path, sha256: prereg.sha256 }, runnerSeal: { path: seal.path, sha256: seal.sha256 }, dryRun: { path: dry.path, sha256: dry.sha256 } }, reason: { code: "MODEL_RUNTIME_CALL_ERROR_REPORTED_AS_PRE_RESPONSE", errorSha256: failure.errorSha256, rawErrorStored: false, rawOutputAvailable: false, hotPatchPerformed: false }, accounting, lineage: { callEvents: { path: eventPath, sha256: sha256(await regular(eventPath)), rows: events.length }, checkpoint: { path: checkpointPath, sha256: sha256(await regular(checkpointPath)), rows: rows.length }, lastEvent: { event: failure.event, index: failure.index, taskIdSha256: sha256(failure.taskId), physicalCallIdSha256: sha256(failure.physicalCallId) }, L0Packets: 13, L1Packets: 13, sameCallPairsValidated: 13 }, privacy: { rawModelOutputsPersisted: 0, rawEditBodiesPersisted: 0, rawIdentifiersPersisted: 0, rawLiteralsPersisted: 0, rawParserMessagesPersisted: 0, HMACKeyMaterialPersisted: false, leaks: 0, L2: false, semanticClassificationPerformed: false }, safety: { violations: 0, rollbackFailures: 0, packetSchemaFailures: 0 }, cleanup: { modelProcesses: 0, port8000Clear: true, modelGpuAllocationMiB: 0, ephemeralApiKeyAbsent: true, HMACKeyAbsent: true, servingStateRemoved: true, states }, decision: { generationPermanentlyClosed: true, resumeSameGeneration: false, retryFailedCall: false, continueRemainingTasks: false, SessionCReady: false, nextAction: "NEW_APPEND_ONLY_RECOVERY_DECISION_REQUIRED" }, protectedActions: { modelDownload: false, retry: false, reviewer: false, L2: false, commit: false, remote: false, push: false, pullRequest: false, tag: false, release: false, signing: false } });
const validationRef = await publish("docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V2_SESSION_B_ABORT_VALIDATION.v2.json", { schemaVersion: 2, validationId: "dca-privacy-safe-semantic-observability-v2-session-b-abort-validation", status: "PASS_PARTIAL_ABORT_INTEGRITY_AND_CLEANUP", validatedAt: recordedAt, input: abortRef, checks: { frozenInputs: "PASS", sourceClosure: "PASS", physicalCallAccounting: "PASS_14", completedResponses: "PASS_13", sameCallPairs: "PASS_13", duplicateCalls: 0, retries: 0, extractorCrashesOnCompletedResponses: 0, packetSchemaFailures: 0, privacyLeaks: 0, safetyViolations: 0, rollbackFailures: 0, failClosedBoundary: "PASS_INDEX_13", remainingTasksNotCalled: 66, SessionBPassClaimed: false, SessionCNotEntered: true, cleanup: "PASS" }, commands });
const sessionRef = await publish("docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V2_SESSION_B.v2.json", { schemaVersion: 2, sessionId: "dca-privacy-safe-semantic-observability-v2-session-b", session: "V2_SESSION_B", status: "ABORTED_FAIL_CLOSED", classification: "PARTIAL_EVIDENCE_COLLECTION_NOT_PRIMARY_ANALYSIS_ELIGIBLE", recordedAt, artifacts: { partialAbort: abortRef, validation: validationRef }, accounting, privacy: { leaks: 0, rawPersistence: 0, L2: false }, semanticAnalysisPerformed: false, productDecisionChanged: false, cleanup: { modelProcesses: 0, port8000Clear: true, modelGpuAllocationMiB: 0, ephemeralStateAbsent: true }, next: "RECOVERY_PROTOCOL_REQUIRED_SEPARATE_INVOCATION", stop: "SESSION_B_ABORT_BOUNDARY_REACHED" });
const indexRef = await publish("docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_RESULTS_INDEX.v4.json", { schemaVersion: 4, indexId: "dca-privacy-safe-semantic-observability-results-index-v4", status: "V2_SESSION_B_ABORTED_FAIL_CLOSED", generatedAt: recordedAt, v1: { status: "PERMANENTLY_CLOSED_PARTIAL_ABORT", consumedCalls: 4, completePairs: 3 }, v2: { A: { path: sessionA.path, sha256: sessionA.sha256, status: "PASS" }, B: { path: sessionRef.path, sha256: sessionRef.sha256, status: "ABORTED_FAIL_CLOSED" }, C: null, D: null, consumedCalls: 14, completePairs: 13, primaryAnalysisEligible: false }, artifacts: { partialAbort: abortRef, validation: validationRef }, next: "RECOVERY_PROTOCOL_REQUIRED_SEPARATE_INVOCATION" });
process.stdout.write(`${JSON.stringify({ status: "ABORTED_FAIL_CLOSED", sessionB: sessionRef, partialAbort: abortRef, validation: validationRef, resultsIndex: indexRef, accounting, cleanup: { port8000Clear: true, modelGpuAllocationMiB: 0, ephemeralStateAbsent: true }, next: "RECOVERY_PROTOCOL_REQUIRED_SEPARATE_INVOCATION" }, null, 2)}\n`);
