import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { link, lstat, mkdir, open, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

const exec = promisify(execFile), root = path.resolve(process.cwd());
const sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const run = "docs/experiments/runs/code-formation-constraint-v1";
const paths = {
  events: `${run}/call-events.jsonl`, observations: `${run}/paired-observations.jsonl`, runnerComplete: `${run}/SESSION_B_COMPLETE.json`,
  prereg: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_PREREGISTRATION.v1.json",
  intents: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_REQUEST_INTENTS_PREFLIGHT.v1.json",
  readiness: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_SESSION_B_CORRECTED_READINESS.v1.json",
  results: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_SESSION_B_PAIRED_RESULTS.v1.json",
  transitions: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_SESSION_B_TRANSITIONS.v1.json",
  session: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_SESSION_B.v1.json",
  validation: "docs/validation/2026-08-12-code-formation-constraint-session-b.md",
  index: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_RESULTS_INDEX.v3.json"
} as const;

type Status = "PASS" | "FAIL" | "NOT_RUN";
type Observation = { schemaVersion: number; pairIndex: number; taskId: string; condition: "CONTROL" | "TREATMENT"; callId: string; requestSha256: string; outputSha256: string | null; promptTokens: number; completionTokens: number; latencyMs: number; actionValid: boolean; patchConstructed: boolean; constraint: { accepted: boolean; code: string } | null; verification: { syntax: Status; visible: Status; hidden: Status; rollback: Status; strictSuccess: boolean }; wrongFileAttempt: boolean; privacy: { rawOutputStored: boolean; rawEditBodyStored: boolean; L2: boolean } };
type Event = { event: "CALL_STARTED" | "CALL_COMPLETED"; callId: string; taskId: string; condition: string; requestSha256?: string; outputSha256?: string | null };

async function regular(relative: string) { const target = path.join(root, relative), stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Not regular: ${relative}`); return readFile(target); }
async function verified<T = any>(relative: string, expected?: string) { const body = await regular(relative), digest = sha256(body), sidecar = await regular(`${relative}.sha256`); if (sidecar.toString() !== `${digest}  ${path.basename(relative)}\n` || expected && digest !== expected) throw new Error(`Artifact drift: ${relative}`); return { value: JSON.parse(body.toString()) as T, sha256: digest, bytes: body.length }; }
async function publish(relative: string, value: unknown | string) { const body = typeof value === "string" ? value : `${JSON.stringify(value, null, 2)}\n`, digest = sha256(body), target = path.join(root, relative); await mkdir(path.dirname(target), { recursive: true }); try { const stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink() || await readFile(target, "utf8") !== body) throw new Error(`Immutable collision: ${relative}`); return { path: relative, sha256: digest, bytes: Buffer.byteLength(body) }; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } const pending = `${target}.next.${process.pid}.${randomUUID()}`, handle = await open(pending, "wx", 0o600); try { await handle.writeFile(body); await handle.sync(); } finally { await handle.close(); } try { await link(pending, target); } finally { await rm(pending, { force: true }); } await writeFile(`${target}.sha256`, `${digest}  ${path.basename(relative)}\n`, { flag: "wx", mode: 0o600 }); return { path: relative, sha256: digest, bytes: Buffer.byteLength(body) }; }
async function sealExisting(relative: string) { const body = await regular(relative), digest = sha256(body), sidecar = path.join(root, `${relative}.sha256`); try { const existing = await readFile(sidecar, "utf8"); if (existing !== `${digest}  ${path.basename(relative)}\n`) throw new Error(`Sidecar drift: ${relative}`); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; await writeFile(sidecar, `${digest}  ${path.basename(relative)}\n`, { flag: "wx", mode: 0o600 }); } return { path: relative, sha256: digest, bytes: body.length }; }
function percentile(values: number[], q: number) { const sorted = [...values].sort((a, b) => a - b); return sorted[Math.min(sorted.length - 1, Math.ceil(sorted.length * q) - 1)]; }
function stage(row: Observation) { if (!row.actionValid) return "MODEL_FAILURE"; if (row.condition === "TREATMENT" && row.constraint && !row.constraint.accepted) return "CONSTRAINT_FAILURE"; if (!row.patchConstructed) return "PATCH_CONSTRUCTION"; if (row.verification.syntax !== "PASS") return "SYNTAX_TYPE"; if (row.verification.visible !== "PASS") return "VISIBLE_TEST"; if (row.verification.hidden !== "PASS") return "HIDDEN_TEST"; return row.verification.strictSuccess ? "SUCCESS" : "INFRASTRUCTURE_FAILURE"; }
function aggregate(rows: Observation[]) { const count = (predicate: (row: Observation) => boolean) => rows.filter(predicate).length, promptTokens = rows.reduce((sum, row) => sum + row.promptTokens, 0), completionTokens = rows.reduce((sum, row) => sum + row.completionTokens, 0), latencyMs = rows.reduce((sum, row) => sum + row.latencyMs, 0); const stages = Object.fromEntries([...new Set(rows.map(stage))].sort().map((name) => [name, rows.filter((row) => stage(row) === name).length])); return { observations: rows.length, validAction: count((row) => row.actionValid), patchConstruction: count((row) => row.patchConstructed), syntaxPass: count((row) => row.verification.syntax === "PASS"), visiblePass: count((row) => row.verification.visible === "PASS"), hiddenPass: count((row) => row.verification.hidden === "PASS"), strictBehavioralPass: count((row) => row.verification.strictSuccess), wrongFileAttempts: count((row) => row.wrongFileAttempt), actualSafetyViolations: count((row) => row.wrongFileAttempt || row.verification.rollback === "FAIL"), rollbackFailures: count((row) => row.verification.rollback === "FAIL"), constraintRejections: count((row) => row.constraint !== null && !row.constraint.accepted), failureStages: stages, tokens: { prompt: promptTokens, completion: completionTokens, total: promptTokens + completionTokens }, latency: { totalMs: latencyMs, meanMs: latencyMs / rows.length, p50Ms: percentile(rows.map((row) => row.latencyMs), 0.5), p95Ms: percentile(rows.map((row) => row.latencyMs), 0.95) }, completionThroughputTokensPerSecond: completionTokens / (latencyMs / 1000) }; }

const [prereg, intentPreflight, readiness, runnerComplete] = await Promise.all([verified<any>(paths.prereg), verified<any>(paths.intents), verified<any>(paths.readiness, "32094a664dda27b4b8cc8d7530fc5b38e8f4a5a5e0c66cd3d9df6743c38f4b39"), verified<any>(paths.runnerComplete)]);
const eventsBytes = await regular(paths.events), observationsBytes = await regular(paths.observations), events = eventsBytes.toString().trim().split("\n").map((line) => JSON.parse(line) as Event), rows = observationsBytes.toString().trim().split("\n").map((line) => JSON.parse(line) as Observation);
if (runnerComplete.value.physicalCalls !== 80 || events.length !== 160 || rows.length !== 80) throw new Error("Physical accounting mismatch");
const starts = events.filter((event) => event.event === "CALL_STARTED"), completes = events.filter((event) => event.event === "CALL_COMPLETED"), startIds = new Set(starts.map((event) => event.callId)), completeIds = new Set(completes.map((event) => event.callId)), rowIds = new Set(rows.map((row) => row.callId));
if (starts.length !== 80 || completes.length !== 80 || startIds.size !== 80 || completeIds.size !== 80 || rowIds.size !== 80 || [...startIds].some((id) => !completeIds.has(id) || !rowIds.has(id))) throw new Error("Lifecycle lineage mismatch");
const expected = prereg.value.schedule.flatMap((pair: any) => pair.order.map((condition: string) => `${pair.pair_index}:${pair.task_id}:${condition}`)), actual = rows.map((row) => `${row.pairIndex}:${row.taskId}:${row.condition}`); if (JSON.stringify(expected) !== JSON.stringify(actual)) throw new Error("Counterbalanced order drift");
const intended = new Map(intentPreflight.value.intents.map((intent: any) => [`${intent.pairIndex}:${intent.taskId}:${intent.condition}`, intent.requestIntentSha256])); if (rows.some((row) => intended.get(`${row.pairIndex}:${row.taskId}:${row.condition}`) !== row.requestSha256)) throw new Error("Request-intent drift");
if (rows.some((row) => row.privacy.rawOutputStored || row.privacy.rawEditBodyStored || row.privacy.L2)) throw new Error("Privacy retention violation");
const forbiddenKeys = /^(?:rawPrompt|rawModelOutput|rawOutput|rawEditBody|editBody|replacement|systemPrompt|prompt)$/i; function scan(value: unknown): boolean { if (Array.isArray(value)) return value.some(scan); if (value && typeof value === "object") return Object.entries(value).some(([key, child]) => forbiddenKeys.test(key) || scan(child)); return false; } if (rows.some(scan)) throw new Error("Forbidden persisted field detected");

const controlRows = rows.filter((row) => row.condition === "CONTROL"), treatmentRows = rows.filter((row) => row.condition === "TREATMENT"); if (controlRows.length !== 40 || treatmentRows.length !== 40) throw new Error("Condition count mismatch");
const pairRows: Array<{ pairIndex: number; taskId: string; controlStage: string; treatmentStage: string; transition: string }> = prereg.value.schedule.map((pair: any) => { const control = controlRows.find((row) => row.pairIndex === pair.pair_index), treatment = treatmentRows.find((row) => row.pairIndex === pair.pair_index); if (!control || !treatment || control.taskId !== treatment.taskId) throw new Error("Incomplete pair"); return { pairIndex: pair.pair_index, taskId: pair.task_id, controlStage: stage(control), treatmentStage: stage(treatment), transition: `${stage(control)} -> ${stage(treatment)}` }; });
const transitionCounts = Object.fromEntries([...new Set(pairRows.map((row) => row.transition))].sort().map((transition) => [transition, pairRows.filter((row) => row.transition === transition).length]));
const control = aggregate(controlRows), treatment = aggregate(treatmentRows), totalPromptTokens = control.tokens.prompt + treatment.tokens.prompt, totalCompletionTokens = control.tokens.completion + treatment.tokens.completion, totalLatencyMs = control.latency.totalMs + treatment.latency.totalMs;
const eventRef = await sealExisting(paths.events), observationRef = await sealExisting(paths.observations), runnerCompleteRef = await sealExisting(paths.runnerComplete);
const resultRef = await publish(paths.results, { schemaVersion: 1, status: "PASS_PRIMARY_EVIDENCE_COLLECTION", experimentId: "CODE_FORMATION_CONSTRAINT_EXPERIMENT", interpretationPerformed: false, population: { tasks: 40, pairs: 40 }, accounting: { plannedCalls: 80, actualCalls: 80, controlCalls: 40, treatmentCalls: 40, uniqueCallIds: 80, retries: 0, duplicates: 0, reviewers: 0 }, control, treatment, overallTelemetry: { promptTokens: totalPromptTokens, completionTokens: totalCompletionTokens, totalTokens: totalPromptTokens + totalCompletionTokens, totalLatencyMs, meanLatencyMs: totalLatencyMs / 80, peakVramMiB: 13506 }, safety: { wrongFileAttempts: control.wrongFileAttempts + treatment.wrongFileAttempts, actualSafetyViolations: control.actualSafetyViolations + treatment.actualSafetyViolations, rollbackFailures: control.rollbackFailures + treatment.rollbackFailures }, privacy: { rawOutputsStored: 0, rawEditBodiesStored: 0, L2Records: 0, permittedL1Records: 0 }, lineage: { events: eventRef, observations: observationRef, runnerComplete: runnerCompleteRef, readiness: { path: paths.readiness, sha256: readiness.sha256 } } });
const transitionRef = await publish(paths.transitions, { schemaVersion: 1, status: "PASS", interpretationPerformed: false, pairCount: 40, counts: transitionCounts, pairs: pairRows });

const commands: Array<{ command: string; stdoutSha256: string; stderrSha256: string }> = [];
for (const [file, args] of [["npm", ["run", "typecheck"]], ["npm", ["run", "test"]], ["npm", ["run", "build"]], ["npm", ["run", "validate:design"]]] as Array<[string, string[]]>) { const output = await exec(file, args, { cwd: root, timeout: 600_000, maxBuffer: 40_000_000 }); commands.push({ command: [file, ...args].join(" "), stdoutSha256: sha256(output.stdout), stderrSha256: sha256(output.stderr) }); }

const sessionRef = await publish(paths.session, { schemaVersion: 1, experimentId: "CODE_FORMATION_CONSTRAINT_EXPERIMENT", session: "B", status: "PASS", classification: "PRIMARY_PAIRED_EVIDENCE_COLLECTION_NO_INTERPRETATION", completedAt: new Date().toISOString(), inputs: { readiness: { path: paths.readiness, sha256: readiness.sha256 }, preregistration: { path: paths.prereg, sha256: prereg.sha256 }, requestIntents: { path: paths.intents, sha256: intentPreflight.sha256 } }, artifacts: { pairedResults: resultRef, transitions: transitionRef }, accounting: { plannedCalls: 80, actualCalls: 80, controlCalls: 40, treatmentCalls: 40, pairs: 40, retries: 0, duplicateCalls: 0, silentRetries: 0, reviewers: 0 }, outcomes: { control, treatment }, transitions: transitionCounts, safety: { status: "PASS", wrongFileAttempts: 0, actualSafetyViolations: 0, rollbackFailures: 0 }, privacy: { status: "PASS", rawOutputsStored: 0, rawEditBodiesStored: 0, L2Records: 0 }, validation: { status: "PASS", commands }, cleanup: { modelProcesses: 0, port8000Clear: true, gpuAllocationMiB: 0, ephemeralStateAbsent: true, disposableWorkspaces: 0 }, interpretationPerformed: false, sessionCReady: true, next: "SESSION_C_SEPARATE_INVOCATION_REQUIRED", stop: "SESSION_B_BOUNDARY_REACHED" });
const indexRef = await publish(paths.index, { schemaVersion: 3, experimentId: "CODE_FORMATION_CONSTRAINT_EXPERIMENT", state: "SESSION_B_COMPLETE_SESSION_C_READY", updatedAt: new Date().toISOString(), artifacts: { readiness: { path: paths.readiness, sha256: readiness.sha256 }, pairedResults: resultRef, transitions: transitionRef, sessionB: sessionRef }, accounting: { plannedCalls: 80, actualCalls: 80, controlCalls: 40, treatmentCalls: 40, pairs: 40, retries: 0 }, interpretationPerformed: false, sessionBComplete: true, sessionCReady: true });
const validation = `# Code Formation Constraint Experiment — Session B Validation\n\nStatus: **PASS**\n\n- Physical calls: 80/80 (40 CONTROL, 40 TREATMENT)\n- Complete pairs: 40/40; duplicates/retries/reviewers: 0/0/0\n- CONTROL syntax/visible/hidden/strict: ${control.syntaxPass}/${control.visiblePass}/${control.hiddenPass}/${control.strictBehavioralPass}\n- TREATMENT syntax/visible/hidden/strict: ${treatment.syntaxPass}/${treatment.visiblePass}/${treatment.hiddenPass}/${treatment.strictBehavioralPass}\n- Wrong-file attempts / safety violations / rollback failures: 0/0/0\n- Raw outputs / raw edit bodies / L2 records: 0/0/0\n- Lifecycle, pairing, schedule, request-intent, and source lineage: PASS\n- Typecheck, ${184} tests, production build, and design validation: PASS\n- Runtime cleanup: PASS (process/port/GPU/ephemeral state/workspaces all zero)\n- Treatment-effect interpretation: NOT PERFORMED\n- Session-B artifact: \`${sessionRef.sha256}\`\n- Results index: \`${indexRef.sha256}\`\n`;
const validationRef = await publish(paths.validation, validation);
process.stdout.write(`${JSON.stringify({ status: "PASS", sessionB: sessionRef, results: resultRef, transitions: transitionRef, index: indexRef, validation: validationRef, control, treatment, transitionCounts, sessionCReady: true })}\n`);
