import { createHash } from "node:crypto";
import { lstat, mkdir, open, readFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(process.cwd());
const sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const paths = {
  candidate: "docs/experiments/patch-interface/E_EDIT_CANDIDATE.v1.json",
  preregistration: "benchmarks/patch-interface/E_EDIT_HOLDOUT_PREREGISTRATION.v2.json",
  seal: "benchmarks/patch-interface/E_EDIT_HOLDOUT_SEAL.v2.json",
  manifest: "benchmarks/patch-interface/E_EDIT_HOLDOUT_MANIFEST.v5.json",
  oracle: "benchmarks/patch-interface/E_EDIT_HOLDOUT_ORACLE.v5.sealed.json",
  sessionA: "docs/experiments/patch-interface/E_EDIT_HOLDOUT_SESSION_A.v2.json",
  sessionB: "docs/experiments/patch-interface/E_EDIT_HOLDOUT_SESSION_B.v2.json",
  baseline: "docs/experiments/runs/e-edit-holdout-baseline-20260811T110600Z/result.json",
  eEdit: "docs/experiments/runs/e-edit-holdout-p2-20260811T111300Z/result.json",
  retry: "docs/experiments/runs/e-edit-holdout-retry-v1/result.json",
  paired: "benchmarks/patch-interface/E_EDIT_HOLDOUT_PAIRED_RESULTS.v2.json",
  promotion: "benchmarks/patch-interface/E_EDIT_HOLDOUT_PROMOTION_DECISION.v2.json",
  baselineLifecycle: "docs/experiments/runs/e-edit-holdout-baseline-20260811T110600Z/lifecycle.json",
  eEditLifecycle: "docs/experiments/runs/e-edit-holdout-p2-20260811T111300Z/lifecycle.json",
  security: "docs/experiments/patch-interface/PATCH_INTERFACE_SECURITY_REGRESSION.v3.json"
};
const outputs = {
  failure: "benchmarks/patch-interface/E_EDIT_HOLDOUT_FAILURE_DECOMPOSITION.v1.json",
  decision: "docs/experiments/patch-interface/E_EDIT_PRODUCT_DECISION.v1.json",
  tournament: "benchmarks/model-specialization/PRACTICAL_LOCAL_MODEL_TOURNAMENT_PROTOCOL.v1.json",
  ceiling: "docs/experiments/patch-interface/PATCH_CAPABILITY_CEILING.v4.json",
  release: "artifacts/release/e-edit-holdout-release-gate-supplement.v1.json",
  report: "docs/experiments/patch-interface/E_EDIT_HOLDOUT_FINAL_REPORT.v1.json",
  index: "docs/experiments/patch-interface/E_EDIT_HOLDOUT_RESULTS_INDEX.v1.json",
  session: "docs/experiments/patch-interface/E_EDIT_HOLDOUT_SESSION_C.v1.json"
};

type Ref<T> = { value: T; path: string; sha256: string };
type Observation = { observationId: string; taskId: string; repositoryId: string; category: string; difficulty: string; fileScope: string; retrieval: { exactSourceSelected: boolean; exactSourceIncluded: boolean }; modelCall: { promptTokens: number; completionTokens: number; latencyMs: number }; normalization: { classification: string }; execution: { patchApplied: boolean; syntax: string; visible: string; hidden: string; rollback: string; cleanup: string; actualSafetyViolation: boolean }; outcome: { behavioralSuccess: boolean; hiddenSuccess: boolean; wrongFileAttempt: boolean; actualSafetyViolation: boolean; firstFailureStage: string } };

async function verified<T>(relative: string): Promise<Ref<T>> { const target = path.join(root, relative), bytes = await readFile(target), digest = sha256(bytes), [metadata, sidecarMetadata] = await Promise.all([lstat(target), lstat(`${target}.sha256`)]); if (!metadata.isFile() || metadata.isSymbolicLink() || !sidecarMetadata.isFile() || sidecarMetadata.isSymbolicLink() || await readFile(`${target}.sha256`, "utf8") !== `${digest}  ${path.basename(target)}\n`) throw new Error(`Invalid artifact ${relative}`); return { value: JSON.parse(bytes.toString("utf8")) as T, path: relative, sha256: digest }; }
async function rawRef(relative: string) { const target = path.join(root, relative), bytes = await readFile(target), metadata = await lstat(target); if (!metadata.isFile() || metadata.isSymbolicLink()) throw new Error(`Unsafe evidence ${relative}`); return { path: relative, sha256: sha256(bytes) }; }
async function lines(relative: string): Promise<Observation[]> { const text = await readFile(path.join(root, relative), "utf8"); return text.trimEnd().split("\n").filter(Boolean).map((line) => JSON.parse(line) as Observation); }
async function persist(relative: string, value: unknown) { const target = path.join(root, relative); await mkdir(path.dirname(target), { recursive: true }); const body = `${JSON.stringify(value, null, 2)}\n`, digest = sha256(body); for (const [file, contents] of [[target, body], [`${target}.sha256`, `${digest}  ${path.basename(target)}\n`]] as const) { try { const handle = await open(file, "wx", 0o600); try { await handle.writeFile(contents); await handle.sync(); } finally { await handle.close(); } } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; const metadata = await lstat(file); if (!metadata.isFile() || metadata.isSymbolicLink() || await readFile(file, "utf8") !== contents) throw new Error(`Immutable collision ${relative}`); } } return { path: relative, sha256: digest }; }
function percentile(values: number[], probability: number) { const sorted = [...values].sort((a, b) => a - b), index = Math.ceil(probability * sorted.length) - 1; return sorted[Math.max(0, index)]; }
function countBy<T extends string>(values: T[]) { const result: Record<string, number> = {}; for (const value of values) result[value] = (result[value] ?? 0) + 1; return result; }
function primary(row: Observation) { if (!row.retrieval.exactSourceSelected || !row.retrieval.exactSourceIncluded) return "RETRIEVAL"; const allowed = new Set(["TASK_UNDERSTANDING", "RETRIEVAL", "EVIDENCE_COMPOSITION", "MODEL_REASONING", "ACTION_GENERATION", "ACTION_VALIDATION", "PATCH_CONSTRUCTION", "SYNTAX_TYPE", "VISIBLE_TEST", "HIDDEN_TEST", "POLICY_BLOCK", "TOOL_INFRASTRUCTURE", "OTHER"]); return allowed.has(row.outcome.firstFailureStage) ? row.outcome.firstFailureStage : "OTHER"; }
function secondary(row: Observation, cause: string) { const values: string[] = []; if (cause === "RETRIEVAL" && row.outcome.firstFailureStage !== "COMPLETE") values.push(row.outcome.firstFailureStage); if (["SYNTAX_TYPE", "VISIBLE_TEST", "HIDDEN_TEST"].includes(row.outcome.firstFailureStage)) values.push("MODEL_REASONING"); if (row.outcome.firstFailureStage === "ACTION_VALIDATION" && row.normalization.classification === "REPORT_ONLY") values.push("UNNECESSARY_REFUSAL"); return [...new Set(values)]; }
function performanceMetrics(rows: Observation[]) { const latencies = rows.map((row) => row.modelCall.latencyMs), inputTokens = rows.reduce((sum, row) => sum + row.modelCall.promptTokens, 0), outputTokens = rows.reduce((sum, row) => sum + row.modelCall.completionTokens, 0), totalLatencyMs = latencies.reduce((sum, value) => sum + value, 0); return { calls: rows.length, inputTokens, outputTokens, totalTokens: inputTokens + outputTokens, totalLatencyMs, medianEndToEndLatencyMs: percentile(latencies, 0.5), p95EndToEndLatencyMs: percentile(latencies, 0.95), effectiveOutputTokensPerSecond: outputTokens / (totalLatencyMs / 1000), ttftMs: "NOT_MEASURED_BY_SESSION_B_RUNNER", idleVramMiB: "NOT_MEASURED_BY_SESSION_B_RUNNER", peakVramMiB: "NOT_MEASURED_BY_SESSION_B_RUNNER", cleanupVramMiB: 0 }; }
function breakdown(records: Array<{ category: string; primaryCause: string }>) { const result: Record<string, { failures: number; causes: Record<string, number> }> = {}; for (const record of records) { result[record.category] ??= { failures: 0, causes: {} }; result[record.category].failures += 1; result[record.category].causes[record.primaryCause] = (result[record.category].causes[record.primaryCause] ?? 0) + 1; } return result; }

const [candidate, preregistration, seal, manifest, oracle, sessionA, sessionB, baseline, eEdit, retry, paired, promotion, baselineLifecycle, eEditLifecycle, security, uiPerformance, uiExtended, releaseGate, adr] = await Promise.all([
  verified<any>(paths.candidate), verified<any>(paths.preregistration), verified<any>(paths.seal), verified<any>(paths.manifest), verified<any>(paths.oracle), verified<any>(paths.sessionA), verified<any>(paths.sessionB), verified<any>(paths.baseline), verified<any>(paths.eEdit), verified<any>(paths.retry), verified<any>(paths.paired), verified<any>(paths.promotion), verified<any>(paths.baselineLifecycle), verified<any>(paths.eEditLifecycle), verified<any>(paths.security),
  rawRef("docs/experiments/runs/m8-ui-performance-2026-08-11T03-21-35-154Z/result.json"), rawRef("docs/experiments/runs/m8-extended-ui-qa-2026-08-11T03-21-36-001Z/result.json"), rawRef("artifacts/release/release-gate.json"), rawRef("adrs/0015-keep-mutation-disabled-after-e-edit-holdout.md")
]);
if (candidate.sha256 !== "7abdcd7cfe84b3e3e6844ecc81c8a4c783a9af53e45dcbb0489fa0e157a32fbc" || sessionA.value.status !== "PASS" || sessionB.value.status !== "PASS" || promotion.value.outcome !== "E_EDIT_HOLDOUT_GATE_FAIL" || retry.value.status !== "NOT_ELIGIBLE_ZERO_CALLS" || security.value.status !== "PASS") throw new Error("Session-C sealed input gate failed");
for (const [relative, expected] of Object.entries(seal.value.executionSourceClosure as Record<string, string>)) if (sha256(await readFile(path.join(root, relative))) !== expected) throw new Error(`Session-A source closure drift ${relative}`);

const [baselineRows, eEditRows] = await Promise.all([lines(`${path.dirname(paths.baseline)}/observations.checkpoint.jsonl`), lines(`${path.dirname(paths.eEdit)}/observations.checkpoint.jsonl`)]);
if (baselineRows.length !== 95 || eEditRows.length !== 95) throw new Error("Session-B observation count changed");
const failureRecords = (condition: "baseline" | "e-edit", rows: Observation[]) => rows.filter((row) => !row.outcome.behavioralSuccess).map((row) => { const primaryCause = primary(row); return { condition, taskId: row.taskId, repositoryId: row.repositoryId, category: row.category, difficulty: row.difficulty, fileScope: row.fileScope, primaryCause, secondaryCauses: secondary(row, primaryCause), recordedRuntimeStage: row.outcome.firstFailureStage, retrievalExactSourceSelected: row.retrieval.exactSourceSelected, retrievalExactSourceIncluded: row.retrieval.exactSourceIncluded, normalizationClassification: row.normalization.classification, rawModelOutputStored: false }; });
const baselineFailures = failureRecords("baseline", baselineRows), eEditFailures = failureRecords("e-edit", eEditRows), derivedAt = sessionB.value.completedAt;
const retrieval = { baseline: { selected: baselineRows.filter((row) => row.retrieval.exactSourceSelected).length, included: baselineRows.filter((row) => row.retrieval.exactSourceIncluded).length, misses: baselineRows.filter((row) => !row.retrieval.exactSourceSelected || !row.retrieval.exactSourceIncluded).length }, eEdit: { selected: eEditRows.filter((row) => row.retrieval.exactSourceSelected).length, included: eEditRows.filter((row) => row.retrieval.exactSourceIncluded).length, misses: eEditRows.filter((row) => !row.retrieval.exactSourceSelected || !row.retrieval.exactSourceIncluded).length }, pairedMissTaskIdsSha256: sha256(eEditRows.filter((row) => !row.retrieval.exactSourceSelected || !row.retrieval.exactSourceIncluded).map((row) => row.taskId).sort().join("\n")) };
const failure = { schemaVersion: 1, decompositionId: "dca-e-edit-untouched-holdout-failure-decomposition-v1", status: "PASS", derivedAt, inputs: { baseline: { path: baseline.path, sha256: baseline.sha256 }, eEdit: { path: eEdit.path, sha256: eEdit.sha256 }, paired: { path: paired.path, sha256: paired.sha256 } }, population: { baselineFailures: baselineFailures.length, eEditFailures: eEditFailures.length }, retrieval, aggregate: { baseline: countBy(baselineFailures.map((row) => row.primaryCause)), eEdit: countBy(eEditFailures.map((row) => row.primaryCause)) }, percentages: { baseline: Object.fromEntries(Object.entries(countBy(baselineFailures.map((row) => row.primaryCause))).map(([key, value]) => [key, 100 * value / baselineFailures.length])), eEdit: Object.fromEntries(Object.entries(countBy(eEditFailures.map((row) => row.primaryCause))).map(([key, value]) => [key, 100 * value / eEditFailures.length])) }, categoryBreakdown: { baseline: breakdown(baselineFailures), eEdit: breakdown(eEditFailures) }, interpretation: { actionInterfaceFrictionReduced: "P0 had 95 action-validation failures; P2 produced 89 valid actions.", dominantPostInterfaceCeiling: "Among P2 calls, 66 accepted edits failed syntax or strict behavior; five tasks also had exact-source retrieval misses.", causalLimit: "MODEL_REASONING is a secondary inference for accepted edits failing syntax/behavior, not a directly observed hidden chain-of-thought label." }, records: [...baselineFailures, ...eEditFailures], privacy: { rawPromptsStored: false, rawOutputsStored: false, rawPatchesStored: false, hiddenOracleStored: false } };
const failureRef = await persist(outputs.failure, failure);

const tournament = { schemaVersion: 1, protocolId: "dca-practical-local-model-tournament-v1", state: "PROTOCOL_ONLY_NOT_AUTHORIZED", classification: "PRACTICAL_LOCAL_MODEL_TOURNAMENT", preparedAt: derivedAt, scientificJustification: { eEditValidActions: 89, eEditStrictSuccesses: 23, acceptedEditsFailingStrictBehavior: 66, exactSourceRetrievalMisses: 5, conclusion: "Stronger coding-model capability is justified for controlled study, while retrieval remains a separately measured secondary limitation." }, candidates: [{ modelId: "Qwen/Qwen2.5-Coder-7B-Instruct", role: "GENERIC_CODER_CONTROL", revision: "NOT_SELECTED" }, { modelId: "FIM-7B", role: "FIM_AGENTIC_CANDIDATE", revision: "NOT_SELECTED" }, { modelId: "SWE-agent-LM-7B", role: "SWE_TRAJECTORY_CANDIDATE", revision: "NOT_SELECTED" }], fixedVariables: ["E-EDIT-P2-V1 interface", "E-MIN-V2 retrieval", "C1 context", "same deterministic safety and patch runtime", "same verification and behavioral scoring", "same frozen 95-task screening set"], disclosure: { existingHoldoutNoLongerUntouchedForFutureModels: true, productPromotionRequiresNewRepositoryDisjointHoldout: true, reducedPrecisionLikelyOn16GiBGpu: true, pureScaleOnlyClaimAllowed: false }, prerequisites: ["separate preregistration before acquisition", "exact revision and license review", "explicit model-download approval", "equal or explicitly practical precision profiles", "zero-call runtime/safety preflight", "new untouched holdout before product claim"], acquisitionAuthorized: false, modelDownloaded: false, modelExecuted: false, protectedActions: { dependencyInstall: false, sudo: false, commit: false, remote: false, push: false, pullRequest: false, tag: false, release: false, signing: false } };
const tournamentRef = await persist(outputs.tournament, tournament);

const decision = { schemaVersion: 1, decisionId: "dca-e-edit-untouched-holdout-product-decision-v1", status: "PASS", decidedAt: derivedAt, productMutationDecision: "KEEP_MUTATION_DISABLED", eEditCapabilityStatus: "RESEARCH_ONLY_MUTATION_INTERFACE", eEditIsSkill: false, runtimeInterfaceRetainedForResearch: true, basis: { strictBehavioralSuccess: "23/95 (24.21%)", holdoutPromotionMinimum: "57/95", assistedOnlyFloor: "29/95", adr0014ReconsiderationThreshold: "25%", wrongFileAttempts: 0, actualSafetyViolations: 0, rollbackFailures: 0, retry: "NOT_ELIGIBLE_ZERO_CALLS" }, modelScaleGate: "JUSTIFIED_PROTOCOL_ONLY_NO_ACQUISITION", tournamentProtocol: tournamentRef, adr, productMutationEnabled: false, thresholdsLowered: false };
const decisionRef = await persist(outputs.decision, decision);

const performance = { baseline: performanceMetrics(baselineRows), eEdit: performanceMetrics(eEditRows), retry: { status: "NOT_ELIGIBLE_ZERO_CALLS", calls: 0, inputTokens: 0, outputTokens: 0, totalLatencyMs: 0, ttftMs: "NOT_APPLICABLE", throughputTokensPerSecond: "NOT_APPLICABLE", medianEndToEndLatencyMs: "NOT_APPLICABLE", p95EndToEndLatencyMs: "NOT_APPLICABLE", idleVramMiB: "NOT_APPLICABLE", peakVramMiB: "NOT_APPLICABLE" }, measurementLimit: "Session-B rows contain end-to-end latency and token counts but not TTFT or inference-time VRAM samples. Cleanup GPU=0 is reported only as cleanup evidence." };
const ceiling = { schemaVersion: 4, reportId: "dca-patch-capability-ceiling-v4", status: "PASS", generatedAt: derivedAt, supersedes: { path: "docs/experiments/patch-interface/PATCH_CAPABILITY_CEILING.v3.json", reason: "Fresh repository-disjoint E-EDIT holdout evidence" }, immutableEvidence: { paired: { path: paired.path, sha256: paired.sha256 }, failureDecomposition: failureRef, promotion: { path: promotion.path, sha256: promotion.sha256 } }, capabilityCeiling: { interface: "P2 substantially improves action validity", strictBehavior: "23/95 remains below assisted and promotion thresholds", retrieval: "90/95 exact-source selected/included", safetyRuntime: "zero wrong-file, safety and rollback failures", retry: "not eligible" }, productRecommendation: "KEEP_MUTATION_DISABLED", eEditStatus: "RESEARCH_ONLY_MUTATION_INTERFACE", nextScientificGate: "Separately approved practical local 7B tournament protocol, followed by a new untouched holdout if a candidate qualifies", tournamentProtocol: tournamentRef };
const ceilingRef = await persist(outputs.ceiling, ceiling);

const release = { schemaVersion: 1, supplementId: "dca-e-edit-holdout-release-gate-supplement-v1", status: "STOP_SHIP_MUTATION_QUALITY", generatedAt: derivedAt, priorReleaseGate: releaseGate, evidence: { sessionB: { path: sessionB.path, sha256: sessionB.sha256 }, promotion: { path: promotion.path, sha256: promotion.sha256 }, productDecision: decisionRef, security: { path: security.path, sha256: security.sha256 } }, gates: { untouchedHoldoutExecuted: "PASS", deterministicSafety: "PASS", autonomousPatchQuality: "BLOCKED_23_OF_95", assistedPatchQuality: "BLOCKED_BELOW_29_OF_95", retry: "NOT_ELIGIBLE", releaseMutation: "DISABLED", sourceRevision: "BLOCKED_APPROVAL", nativeWindows: "BLOCKED_EXTERNAL", signingAndPublication: "BLOCKED_APPROVAL" }, stopShip: ["E-EDIT strict success 23/95 is below existing product thresholds", "No authorized source commit", "Native Windows and signing evidence remain absent", "Root-license and external dependency metadata blockers remain"] };
const releaseRef = await persist(outputs.release, release);

const report = { schemaVersion: 1, reportId: "dca-e-edit-untouched-holdout-final-report-v1", status: "PASS", generatedAt: derivedAt, experimentIdentity: { candidate: { path: candidate.path, sha256: candidate.sha256 }, preregistration: { path: preregistration.path, sha256: preregistration.sha256 }, seal: { path: seal.path, sha256: seal.sha256 } }, holdout: manifest.value.corpus, results: { baseline: baseline.value.summary, eEdit: eEdit.value.summary, paired: paired.value.paired, statistics: paired.value.statistics, promotionOutcome: promotion.value.outcome }, hiddenTests: { baseline: baseline.value.summary.hiddenSuccesses, eEdit: eEdit.value.summary.hiddenSuccesses }, retrievalGeneralization: retrieval, retry: retry.value, failureDecomposition: failureRef, safety: { wrongFileAttempts: baseline.value.summary.wrongFileAttempts + eEdit.value.summary.wrongFileAttempts, actualSafetyViolations: baseline.value.summary.actualSafetyViolations + eEdit.value.summary.actualSafetyViolations, rollbackFailures: baseline.value.summary.rollbackFailures + eEdit.value.summary.rollbackFailures, securityRegression: { path: security.path, sha256: security.sha256, instances: 1540, templates: 77 } }, performance, productDecision: decisionRef, capabilityCeiling: ceilingRef, tournamentProtocol: tournamentRef, regressionValidation: { repositoryCheck: "PASS_DESIGN_TYPECHECK_130_TESTS_PRODUCTION_BUILD", uiPerformance, uiExtended, security: { path: security.path, sha256: security.sha256 }, secretScan: "PASS_BOUNDARY_AWARE_PATTERNS", artifactChecksums: "PASS", modelWeightGitExclusion: "PASS", worktreeCount: 1 }, runtimeCleanup: { baseline: { path: baselineLifecycle.path, sha256: baselineLifecycle.sha256 }, eEdit: { path: eEditLifecycle.path, sha256: eEditLifecycle.sha256 }, processAbsent: true, port8000Clear: true, gpuMemoryMiB: 0, apiKeyAbsent: true, temporaryStateAbsent: true }, remainingProtectedOrExternalBlockers: ["Any model acquisition, including 7B or quantized snapshots", "Git commit/remote/push/PR/tag/release/signing", "Windows native installer, screen-reader and signing QA", "Root license and remaining authoritative dependency metadata"], lineage: sessionB.value.lineage, privacy: { rawPromptsStored: false, rawOutputsStored: false, rawPatchesStored: false, hiddenOracleStoredOutsideSealedOracle: false } };
const reportRef = await persist(outputs.report, report);
const index = { schemaVersion: 1, indexId: "dca-e-edit-untouched-holdout-results-index-v1", status: "PASS_COMPLETE", generatedAt: derivedAt, artifacts: { candidate: { path: candidate.path, sha256: candidate.sha256 }, preregistration: { path: preregistration.path, sha256: preregistration.sha256 }, seal: { path: seal.path, sha256: seal.sha256 }, sessionA: { path: sessionA.path, sha256: sessionA.sha256 }, sessionB: { path: sessionB.path, sha256: sessionB.sha256 }, baseline: { path: baseline.path, sha256: baseline.sha256 }, eEdit: { path: eEdit.path, sha256: eEdit.sha256 }, retry: { path: retry.path, sha256: retry.sha256 }, paired: { path: paired.path, sha256: paired.sha256 }, promotion: { path: promotion.path, sha256: promotion.sha256 }, failureDecomposition: failureRef, productDecision: decisionRef, capabilityCeiling: ceilingRef, tournamentProtocol: tournamentRef, releaseSupplement: releaseRef, finalReport: reportRef }, conclusions: { oneShotGate: "E_EDIT_HOLDOUT_GATE_FAIL", productMutationDecision: "KEEP_MUTATION_DISABLED", eEditStatus: "RESEARCH_ONLY_MUTATION_INTERFACE", retry: "NOT_ELIGIBLE_ZERO_CALLS", modelScaleGate: "JUSTIFIED_PROTOCOL_ONLY_NO_ACQUISITION" }, physicalLineageTotal: 1169 };
const indexRef = await persist(outputs.index, index);
const session = { schemaVersion: 1, sessionId: "dca-e-edit-untouched-holdout-session-c-v1", session: "C", status: "PASS", completedAt: derivedAt, phases: { failureDecomposition: "PASS", productDecision: "KEEP_MUTATION_DISABLED", capabilityStatus: "RESEARCH_ONLY_MUTATION_INTERFACE", modelScaleGate: "JUSTIFIED_PROTOCOL_ONLY", tournamentProtocol: "PREPARED_NOT_AUTHORIZED", performance: "PASS_WITH_TTFT_AND_INFERENCE_VRAM_NOT_MEASURED", security: "PASS", uiRuntime: "PASS_HEADLESS_WINDOWS_NOT_RUN", finalValidation: "PASS_WITH_EXISTING_EXTERNAL_AND_APPROVAL_BLOCKERS", durableState: "PASS" }, artifacts: { report: reportRef, index: indexRef, failureDecomposition: failureRef, productDecision: decisionRef, capabilityCeiling: ceilingRef, tournamentProtocol: tournamentRef, releaseSupplement: releaseRef }, gate: { sessionAPass: true, sessionBPass: true, sessionCPass: true, allSessionsComplete: true, modelCallsAddedInSessionC: 0, productMutationEnabled: false }, protectedActions: { modelDownload: false, dependencyInstall: false, sudo: false, commit: false, remote: false, push: false, pullRequest: false, tag: false, release: false, signing: false } };
const sessionRef = await persist(outputs.session, session);
process.stdout.write(`${JSON.stringify({ status: "PASS_SESSION_C_ALL_SESSIONS_COMPLETE", report: reportRef, index: indexRef, session: sessionRef, decision: "KEEP_MUTATION_DISABLED", eEditStatus: "RESEARCH_ONLY_MUTATION_INTERFACE", modelScaleGate: "JUSTIFIED_PROTOCOL_ONLY_NO_ACQUISITION", modelCalls: 0 }, null, 2)}\n`);
