import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { link, lstat, mkdir, open, readFile, readdir, rm } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

const exec = promisify(execFile), root = path.resolve(process.cwd()), now = new Date().toISOString();
const run = "docs/experiments/runs/privacy-safe-observability-v3", sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
async function regular(relative: string) { const target = path.join(root, relative), stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Not regular: ${relative}`); return readFile(target); }
async function verified<T = any>(relative: string, expected?: string) { const bytes = await regular(relative), digest = sha256(bytes), sidecar = await regular(`${relative}.sha256`); if (sidecar.toString() !== `${digest}  ${path.basename(relative)}\n` || expected && digest !== expected) throw new Error(`Artifact drift: ${relative}`); return { path: relative, sha256: digest, value: JSON.parse(bytes.toString()) as T }; }
async function publishBytes(relative: string, body: string) { const target = path.join(root, relative); await mkdir(path.dirname(target), { recursive: true }); try { const stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink() || await readFile(target, "utf8") !== body) throw new Error(`Immutable collision: ${relative}`); return; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } const pending = `${target}.next.${process.pid}.${randomUUID()}`, handle = await open(pending, "wx", 0o600); try { await handle.writeFile(body); await handle.sync(); } finally { await handle.close(); } try { await link(pending, target); } finally { await rm(pending, { force: true }); } }
async function publish(relative: string, value: unknown) { const body = `${JSON.stringify(value, null, 2)}\n`, digest = sha256(body); await publishBytes(relative, body); await publishBytes(`${relative}.sha256`, `${digest}  ${path.basename(relative)}\n`); return { path: relative, sha256: digest }; }
async function command(file: string, args: string[], timeout = 600_000) { const result = await exec(file, args, { cwd: root, timeout, maxBuffer: 40_000_000 }); return { command: [file, ...args].join(" "), exitCode: 0, stdoutSha256: sha256(result.stdout), stderrSha256: sha256(result.stderr) }; }
async function jsonLines(relative: string) { const text = (await regular(relative)).toString(); if (!text.endsWith("\n")) throw new Error(`JSONL framing: ${relative}`); return text.slice(0, -1).split("\n").map((line) => JSON.parse(line)); }

const [sessionA, prereg, seal, dry, manifest, totality] = await Promise.all([
  verified("docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V3_SESSION_A.v3.json", "5e6a60de68bd36602f4f0e8e328ee149e6e1cbcc78483dfc867850b37647bfaf"),
  verified<any>("benchmarks/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_PREREGISTRATION.v3.json", "edf0ea732bbb235d10e6d898b15089bc4d1f053f54510e99e58bc63b76a42cb9"),
  verified<any>("benchmarks/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V3_SESSION_B_RUNNER_SEAL.v3.json"),
  verified<any>("benchmarks/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V3_SESSION_B_DRY_RUN.v3.json"),
  verified<any>("benchmarks/model-specialization/PRIVACY_SAFE_OBSERVABILITY_TASK_MANIFEST.v3.json"),
  verified<any>("docs/experiments/model-specialization/PRIVACY_SAFE_OBSERVABILITY_V3_TOTALITY_VALIDATION.v3.json"),
]);
if (prereg.value.state !== "SEALED_BEFORE_FIRST_V3_TARGET_MODEL_CALL" || seal.value.state !== "SEALED_BEFORE_FIRST_V3_TARGET_MODEL_CALL" || dry.value.status !== "PASS_ZERO_TARGET_MODEL_CALLS" || manifest.value.tasks.length !== 80 || totality.value.results.completedSyntheticResponses !== 1019) throw new Error("Frozen V3 gate invalid");
for (const entry of seal.value.sourceClosure.entries) { const bytes = await regular(entry.path); if (sha256(bytes) !== entry.sha256 || bytes.length !== entry.bytes) throw new Error(`Source closure drift: ${entry.path}`); }

const eventPath = `${run}/call-events.jsonl`, checkpointPath = `${run}/observations.checkpoint.jsonl`, events = await jsonLines(eventPath), observations = await jsonLines(checkpointPath);
if (events.length !== 160 || observations.length !== 80) throw new Error("V3 call accounting mismatch");
const taskIds = manifest.value.tasks.map((task: any) => task.task_id), seenCalls = new Set<string>(), parsing = new Map<string, number>(), validation = new Map<string, number>(), parserFailures = new Map<string, number>();
const execution = { patchApplied: 0, syntaxPass: 0, visiblePass: 0, hiddenPass: 0, behavioralSuccess: 0, safetyViolations: 0, rollbackFailures: 0, cleanupFailures: 0 };
let minimumFreeBytes = Number.MAX_SAFE_INTEGER, maximumRequiredFreeBytes = 0, privacyLeaks = 0;
for (let index = 0; index < 80; index++) {
  const started = events[index * 2], completed = events[index * 2 + 1], observation = observations[index];
  if (started.event !== "CALL_STARTED" || completed.event !== "CALL_COMPLETED" || started.index !== index || completed.index !== index || observation.index !== index || started.taskId !== taskIds[index] || completed.taskId !== taskIds[index] || observation.taskId !== taskIds[index] || started.physicalCallId !== completed.physicalCallId || started.physicalCallId !== observation.physicalCallId || started.requestSha256 !== completed.requestSha256 || started.requestSha256 !== observation.requestSha256 || completed.outputSha256 !== observation.outputSha256 || completed.observationSha256 !== sha256(JSON.stringify(observation)) || observation.pairing !== "PASS") throw new Error(`V3 lineage mismatch at ${index}`);
  if (seenCalls.has(started.physicalCallId)) throw new Error("Duplicate physical call"); seenCalls.add(started.physicalCallId);
  if (started.storage.previousCleanup !== "PASS" || started.storage.freeBytes < started.storage.requiredFreeBytes) throw new Error(`Storage guard bypass at ${index}`);
  minimumFreeBytes = Math.min(minimumFreeBytes, started.storage.freeBytes); maximumRequiredFreeBytes = Math.max(maximumRequiredFreeBytes, started.storage.requiredFreeBytes);
  const [l0, l1] = await Promise.all([verified<any>(observation.L0.path, observation.L0.sha256), verified<any>(observation.L1.path, observation.L1.sha256)]);
  for (const packet of [l0.value, l1.value]) if (packet.identity.taskId !== observation.taskId || packet.identity.repositoryRevision === undefined || packet.identity.physicalCallId !== observation.physicalCallId) throw new Error(`Packet identity mismatch at ${index}`);
  if (l1.value.evidence.requestSha256 !== observation.requestSha256 || l0.value.evidence.actionIdentitySha256 !== l1.value.evidence.actionIdentitySha256 || l1.value.evidence.modelResponseStatus !== "COMPLETED") throw new Error(`Same-call evidence mismatch at ${index}`);
  const serialized = JSON.stringify({ observation, l0: l0.value, l1: l1.value }); if (/rawPromptStored":true|rawModelOutputStored":true|rawEditBodyStored":true|rawIdentifiersStored":true|rawLiteralsStored":true|rawParserMessageStored":true|hashKeyStored":true|"L2":true/u.test(serialized)) privacyLeaks++;
  parsing.set(l1.value.evidence.actionParseStatus, (parsing.get(l1.value.evidence.actionParseStatus) ?? 0) + 1); validation.set(l1.value.evidence.actionValidationStatus, (validation.get(l1.value.evidence.actionValidationStatus) ?? 0) + 1); parserFailures.set(l1.value.evidence.parserFailureCategory, (parserFailures.get(l1.value.evidence.parserFailureCategory) ?? 0) + 1);
  if (observation.execution.patchApplied) execution.patchApplied++; if (observation.execution.syntax === "PASS") execution.syntaxPass++; if (observation.execution.visible === "PASS") execution.visiblePass++; if (observation.execution.hidden === "PASS") execution.hiddenPass++; if (observation.execution.syntax === "PASS" && observation.execution.visible === "PASS" && observation.execution.hidden === "PASS") execution.behavioralSuccess++; if (observation.execution.actualSafetyViolation) execution.safetyViolations++; if (observation.execution.rollback !== "PASS") execution.rollbackFailures++; if (observation.execution.cleanup !== "PASS") execution.cleanupFailures++;
}
if (privacyLeaks || execution.safetyViolations || execution.rollbackFailures || execution.cleanupFailures) throw new Error("V3 safety/privacy completion gate failed");
if ((await readdir(path.join(root, run, "l0"))).filter((name) => name.endsWith(".json")).length !== 80 || (await readdir(path.join(root, run, "restricted-l1"))).filter((name) => name.endsWith(".json")).length !== 80) throw new Error("Packet count mismatch");
if ((await readdir("/tmp")).filter((name) => name.startsWith("dca-observability-v3-")).length) throw new Error("Disposable isolation remains");

const runtime = path.join(root, ".runtime/model"), servingState: Record<string, unknown> = {};
for (const name of ["tournament-start.json", "tournament-launch.json"]) { const target = path.join(runtime, name), bytes = await readFile(target); servingState[name] = { sha256: sha256(bytes), bytes: bytes.length }; await rm(target); }
for (const name of ["tournament-api-key", "observability-v3-hmac-key", "tournament-ready.json"]) try { await lstat(path.join(runtime, name)); throw new Error(`Ephemeral state remains: ${name}`); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; }
const [{ stdout: processes }, { stdout: sockets }, { stdout: gpu }, { stdout: worktrees }] = await Promise.all([exec("ps", ["-eo", "args="]), exec("ss", ["-ltn"]), exec("nvidia-smi", ["--query-compute-apps=pid,process_name,used_memory", "--format=csv,noheader,nounits"]), exec("git", ["worktree", "list", "--porcelain"])]);
const modelProcesses = processes.split("\n").filter((line) => /vllm\.entrypoints|launch_model_tournament_candidate/u.test(line) && !line.includes("finalize_privacy_safe")), port8000Clear = !sockets.split("\n").some((line) => /(?:^|:)8000\s/u.test(line)), worktreeCount = worktrees.split("\n").filter((line) => line.startsWith("worktree ")).length;
if (modelProcesses.length || !port8000Clear || gpu.trim() || worktreeCount !== 1) throw new Error("Runtime cleanup incomplete");
const commands = [
  await command("npx", ["tsc", "--ignoreConfig", "--noEmit", "--strict", "--skipLibCheck", "--target", "ES2022", "--module", "ESNext", "--moduleResolution", "Bundler", "--allowSyntheticDefaultImports", "--types", "node", "scripts/finalize_privacy_safe_observability_v3_session_b.ts"]),
  await command("npx", ["vitest", "run", "tests/observability-storage-guard.test.ts", "tests/semantic-observability-v2.test.ts", "tests/semantic-observability.test.ts", "tests/patch-interface-runtime.test.ts", "tests/tool-runtime.test.ts", "--testTimeout=15000"]),
  await command("npm", ["run", "typecheck"]), await command("npm", ["run", "test", "--", "--testTimeout=15000"]), await command("npm", ["run", "build"]), await command("npm", ["run", "validate:design"]),
];
const eventBytes = await regular(eventPath), checkpointBytes = await regular(checkpointPath), summary = { plannedCalls: 80, consumedCalls: 80, completedResponses: 80, L0Packets: 80, L1Packets: 80, sameCallPairs: 80, retries: 0, reviewerCalls: 0, invalidJson: parsing.get("JSON_INVALID") ?? 0, invalidActions: 80 - (validation.get("PASS") ?? 0), malformedOutputs: 80 - (parserFailures.get("NONE") ?? 0), actionParseStatus: Object.fromEntries(parsing), actionValidationStatus: Object.fromEntries(validation), parserFailureCategory: Object.fromEntries(parserFailures), execution };
const resultRef = await publish(`${run}/result.json`, { schemaVersion: 3, resultId: "dca-privacy-safe-semantic-observability-v3-session-b-result", status: "PASS", completedAt: now, inputs: { sessionA: { path: sessionA.path, sha256: sessionA.sha256 }, preregistration: { path: prereg.path, sha256: prereg.sha256 }, runnerSeal: { path: seal.path, sha256: seal.sha256 }, dryRun: { path: dry.path, sha256: dry.sha256 } }, lineage: { callEvents: { path: eventPath, sha256: sha256(eventBytes), bytes: eventBytes.length, rows: 160 }, checkpoint: { path: checkpointPath, sha256: sha256(checkpointBytes), bytes: checkpointBytes.length, rows: 80 }, uniquePhysicalCalls: seenCalls.size, alternatingStartedCompleted: true, duplicateCalls: 0, orphanPackets: 0 }, summary, storage: { formula: prereg.value.storageGuard.formula, maximumLiveDisposableIsolations: 1, observedPeakLiveDisposableIsolations: 1, minimumFreeBytesAtCallStart: minimumFreeBytes, maximumRequiredFreeBytes, capacityFailures: 0, cleanupFailures: 0, staleIsolations: 0, remainingIsolations: 0 }, privacy: { leaks: privacyLeaks, rawPromptPersisted: false, rawModelOutputPersisted: false, rawEditBodyPersisted: false, rawIdentifiersPersisted: false, rawLiteralsPersisted: false, rawParserMessagesPersisted: false, HMACKeyPersisted: false, L2: false }, semanticAnalysisPerformed: false, servingState, cleanup: { modelProcesses: 0, port8000Clear, modelGpuAllocationMiB: 0, ephemeralStateAbsent: true, worktrees: worktreeCount, disposableIsolations: 0 }, protectedActions: { modelDownload: false, retry: false, reviewer: false, L2: false, sudo: false, commit: false, remote: false, push: false, pullRequest: false, tag: false, release: false, signing: false } });
const validationRef = await publish("docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V3_SESSION_B_VALIDATION.v3.json", { schemaVersion: 3, validationId: "dca-privacy-safe-semantic-observability-v3-session-b-validation", status: "PASS", validatedAt: now, inputs: { result: resultRef, runnerSeal: { path: seal.path, sha256: seal.sha256 } }, checks: { exactCalls: "PASS_80", completedResponses: "PASS_80", L0: "PASS_80", L1: "PASS_80", sameCallPairs: "PASS_80", duplicateCalls: 0, retries: 0, responseStateClassification: "PASS", storageGuard: "PASS_80", maximumLiveDisposableIsolations: 1, extractorCrashes: 0, privacyLeaks: 0, rawPersistence: 0, safetyViolations: 0, rollbackFailures: 0, cleanupFailures: 0, lineage: "PASS", sourceClosure: "PASS", runtimeCleanup: "PASS" }, commands });
const sessionRef = await publish("docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V3_SESSION_B.v3.json", { schemaVersion: 3, sessionId: "dca-privacy-safe-semantic-observability-v3-session-b", session: "V3_SESSION_B", status: "PASS", classification: "ONE_SHOT_EVIDENCE_COLLECTION_WITH_TOTAL_PRIVACY_SAFE_L0_L1_PAIRING", completedAt: now, inputs: { sessionA: { path: sessionA.path, sha256: sessionA.sha256 }, preregistration: { path: prereg.path, sha256: prereg.sha256 }, result: resultRef }, artifacts: { validation: validationRef }, summary, storage: { maximumLiveDisposableIsolations: 1, capacityFailures: 0, cleanupFailures: 0 }, privacy: { leaks: 0, rawPersistence: 0, L2: false }, semanticAnalysisPerformed: false, productDecisionChanged: false, cleanup: { modelProcesses: 0, port8000Clear: true, modelGpuAllocationMiB: 0, ephemeralStateAbsent: true, disposableIsolations: 0 }, protectedActions: { modelDownload: false, retry: false, reviewer: false, L2: false, sudo: false, commit: false, remote: false, push: false, pullRequest: false, tag: false, release: false, signing: false }, next: "V3_SESSION_C_SEPARATE_INVOCATION_REQUIRED", stop: "V3_SESSION_B_BOUNDARY_REACHED" });
const indexRef = await publish("docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_RESULTS_INDEX.v6.json", { schemaVersion: 6, indexId: "dca-privacy-safe-semantic-observability-results-index-v6", status: "PASS_V3_SESSION_B_COMPLETE", generatedAt: now, v2: { status: "PERMANENTLY_CLOSED_ABORTED_INFRASTRUCTURE_GENERATION", primaryEligiblePairs: 0 }, v3: { sessions: { A: { path: sessionA.path, sha256: sessionA.sha256 }, B: sessionRef, C: null, D: null }, result: resultRef, validation: validationRef, calls: { planned: 80, consumed: 80, completedResponses: 80, retries: 0, reviewerCalls: 0 }, evidence: { L0: 80, L1: 80, pairs: 80, privacyLeaks: 0 } }, next: "V3_SESSION_C_SEPARATE_INVOCATION_REQUIRED" });
process.stdout.write(`${JSON.stringify({ status: "PASS", sessionB: sessionRef, result: resultRef, validation: validationRef, resultsIndex: indexRef, summary, next: "V3_SESSION_C_SEPARATE_INVOCATION_REQUIRED" }, null, 2)}\n`);
