import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { link, lstat, mkdir, open, readFile, readdir, rm } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import { PRIMARY_TAXONOMY, applyFrozenDecisionGates } from "../services/semantic-failure-decomposition/src/index";

const exec = promisify(execFile), root = path.resolve(process.cwd()), completedAt = new Date().toISOString();
const sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
async function regular(relative: string) { const target = path.join(root, relative), stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Not regular: ${relative}`); return readFile(target); }
async function verified(relative: string, expected?: string) { const bytes = await regular(relative), digest = sha256(bytes), sidecar = await regular(`${relative}.sha256`); if (sidecar.toString("utf8") !== `${digest}  ${path.basename(relative)}\n` || expected && digest !== expected) throw new Error(`Artifact mismatch: ${relative}`); return { path: relative, sha256: digest, value: JSON.parse(bytes.toString("utf8")) as any }; }
async function publishBytes(relative: string, body: string) { const target = path.join(root, relative); await mkdir(path.dirname(target), { recursive: true }); try { const stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink() || await readFile(target, "utf8") !== body) throw new Error(`Immutable collision: ${relative}`); return; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } const pending = `${target}.next.${process.pid}.${randomUUID()}`, handle = await open(pending, "wx", 0o600); try { await handle.writeFile(body); await handle.sync(); } finally { await handle.close(); } try { await link(pending, target); } finally { await rm(pending, { force: true }); } }
async function publish(relative: string, value: unknown) { const body = `${JSON.stringify(value, null, 2)}\n`, digest = sha256(body); await publishBytes(relative, body); await publishBytes(`${relative}.sha256`, `${digest}  ${path.basename(relative)}\n`); return { path: relative, sha256: digest }; }
async function command(file: string, args: string[], timeout = 600_000) { const result = await exec(file, args, { cwd: root, timeout, maxBuffer: 40 * 1024 * 1024 }); return { command: [file, ...args].join(" "), exitCode: 0, stdoutSha256: sha256(result.stdout), stderrSha256: sha256(result.stderr) }; }
const percent = (numerator: number, denominator: number) => 100 * numerator / denominator;

const prereg = await verified("benchmarks/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_PREREGISTRATION.v1.json", "6851a9a2a2fd25757413f71c0b331e5899a397c1928b59259f3cc6606123ed47");
const sessionA = await verified("docs/experiments/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_SESSION_A.v1.json", "368ba02473ef7baf09f7c3927b969c579c1848c8c362c2be12f27cacd36535eb");
const sessionB = await verified("docs/experiments/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_SESSION_B.v1.json", "7dea90719a08855d18145530e5cc84b281ce1cc0ab7777845a8210d6a7ee88d0");
const priorIndex = await verified("docs/experiments/model-specialization/semantic-failure-decomposition-session-b/SEMANTIC_FAILURE_DECOMPOSITION_RESULTS_INDEX.v1.json", "f0f020501898aed91c64c6f2c8d8ffd71dc8ec437e975546b9fc6bdd90edb978");
const classification = await verified("docs/experiments/model-specialization/semantic-failure-decomposition-session-b/SEMANTIC_FAILURE_CLASSIFICATION_MATRIX.v1.json");
const controls = await verified("docs/experiments/model-specialization/semantic-failure-decomposition-session-b/SEMANTIC_FAILURE_SUCCESS_CONTROLS.v1.json");
const evidence = await verified("docs/experiments/model-specialization/semantic-failure-decomposition-session-b/SEMANTIC_FAILURE_EVIDENCE_SUFFICIENCY.v1.json");
const comparison = await verified("docs/experiments/model-specialization/semantic-failure-decomposition-session-b/SEMANTIC_FAILURE_SUCCESS_FAILURE_COMPARISON.v1.json");
const retry = await verified("docs/experiments/model-specialization/semantic-failure-decomposition-session-b/SEMANTIC_FAILURE_RETRY_BY_CATEGORY.v1.json");
const t14 = await verified("docs/experiments/model-specialization/semantic-failure-decomposition-session-b/SEMANTIC_FAILURE_T14_OBSERVABILITY.v1.json");
const priorCeiling = await verified("docs/experiments/patch-interface/PATCH_CAPABILITY_CEILING.v6.json", "920700a606ccbaa6fe15476c808f11a4a0275d3870ef74f9c6a838c428aad59f");
if (prereg.value.state !== "SEALED_BEFORE_DEEP_TASK_CLASSIFICATION" || sessionA.value.status !== "PASS" || sessionB.value.status !== "PASS" || priorIndex.value.gatesG1ToG5Applied !== false) throw new Error("Session lineage drift");
if (classification.value.rows.length !== 66 || controls.value.rows.length !== 29 || sessionB.value.population.total !== 95) throw new Error("Population drift");

const primaryCounts = Object.fromEntries(PRIMARY_TAXONOMY.map((category) => [category, classification.value.rows.filter((row: any) => row.primaryCategory === category).length])) as Record<(typeof PRIMARY_TAXONOMY)[number], number>;
const sufficientEvidenceFailures = classification.value.rows.filter((row: any) => row.evidenceSufficiency === "SUFFICIENT").length;
const gates = applyFrozenDecisionGates({ denominator: 66, primaryCounts, sufficientEvidenceFailures });
if (primaryCounts.T11_RETRIEVAL_FAILURE !== 5 || primaryCounts.T12_ACTION_OR_PATCH_REPRESENTATION !== 2 || primaryCounts.T13_SYNTAX_CODE_FORMATION !== 6 || primaryCounts.T14_AMBIGUOUS_OR_INCONCLUSIVE !== 53 || sufficientEvidenceFailures !== 0 || gates.G5.result !== "APPLIED") throw new Error("Frozen gate inputs drift");

const immutableInputs = {
  preregistration: { path: prereg.path, sha256: prereg.sha256 }, sessionA: { path: sessionA.path, sha256: sessionA.sha256 }, sessionB: { path: sessionB.path, sha256: sessionB.sha256 }, priorResultsIndex: { path: priorIndex.path, sha256: priorIndex.sha256 }, classificationMatrix: { path: classification.path, sha256: classification.sha256 }, successControls: { path: controls.path, sha256: controls.sha256 }, evidenceSufficiency: { path: evidence.path, sha256: evidence.sha256 }, successFailureComparison: { path: comparison.path, sha256: comparison.sha256 }, retryByCategory: { path: retry.path, sha256: retry.sha256 }, t14Observability: { path: t14.path, sha256: t14.sha256 }, priorCapabilityCeiling: { path: priorCeiling.path, sha256: priorCeiling.sha256 },
};
const quantified = {
  failures: 66, controls: 29, total: 95,
  supportedSpecificPrimary: { count: 13, percent: percent(13, 66) },
  supportedProgramSemanticT1ToT9: { count: 0, percent: 0 },
  ambiguousT14: { count: 53, percent: percent(53, 66) },
  confidence: { HIGH: 13, MEDIUM: 0, LOW: 53 },
  evidenceSufficiencyFailures: { SUFFICIENT: 0, PARTIALLY_SUFFICIENT: 61, MISSING_REQUIRED_EVIDENCE: 5 },
  evidenceSufficiencyControls: { SUFFICIENT: 0, PARTIALLY_SUFFICIENT: 29, MISSING_REQUIRED_EVIDENCE: 0 },
  objectiveReferenceScope: { SINGLE_RANGE: 95, interpretation: "Reference repair representability only; actual model mutation scope was not persisted." },
  reasoningHorizon: {
    LOCAL: { failures: 32, controls: 11, combined: 43, descriptiveSuccessPercent: percent(11, 43) },
    CROSS_FILE: { failures: 13, controls: 7, combined: 20, descriptiveSuccessPercent: 35 },
    STATEFUL_OR_API_LEVEL: { failures: 21, controls: 11, combined: 32, descriptiveSuccessPercent: percent(11, 32) },
  },
  t14LimitationReasons: { RAW_EDIT_CONTENT_NOT_PERSISTED: 53, FAILURE_STAGE_NON_IDENTIFYING: 53, REQUIRED_STRUCTURED_MUTATION_METADATA_ABSENT: 0, MULTIPLE_SEMANTIC_CAUSES_EQUIVALENTLY_PLAUSIBLE: 0, OTHER_INSUFFICIENT_OBSERVABLE_EVIDENCE: 0 },
};

const gateRef = await publish("docs/experiments/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_GATE_DECISION.v1.json", {
  schemaVersion: 1, decisionId: "dca-semantic-failure-decomposition-gate-decision-v1", status: "PASS_FROZEN_GATES_APPLIED", generatedAt: completedAt, immutableInputs, denominator: 66, primaryCounts, sufficientEvidenceFailures, gates,
  interpretation: { G1: "5/66 retrievable context failures do not reach 30%; T14 is not added.", G2: "No supported T7/T8 row and no SUFFICIENT failure evidence; reference SINGLE_RANGE does not reveal model scope.", G3: "No supported T2/T3/T4/T5/T6/T9 row and zero SUFFICIENT failure evidence. Failure does not prove model semantics adequate.", G4: "T13 is 6/66 and is not the unique largest primary family because T14 is 53/66.", G5: gates.G5.preciseInterpretation, labelDoesNotProveDemonstratedMixture: true },
  selectedNextExperiment: "PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_EXPERIMENT", selectedExperimentCount: 1, targetModelCalls: 0,
});

const observabilityRef = await publish("docs/experiments/model-specialization/SEMANTIC_OBSERVABILITY_CEILING.v1.json", {
  schemaVersion: 1, reportId: "dca-semantic-observability-ceiling-v1", status: "PASS_CEILING_QUANTIFIED", generatedAt: completedAt, immutableInputs, quantified,
  executionObservability: { patchApplication: "AUDITABLE", syntax: "AUDITABLE", visibleTests: "AUDITABLE", hiddenTests: "AUDITABLE", safety: "AUDITABLE", rollback: "AUDITABLE" },
  semanticObservability: { historicalRetention: "HASHES_AND_BOUNDED_METADATA_WITHOUT_RAW_EDIT_BODY", supportedT1ToT9CoveragePercent: 0, t14RatePercent: percent(53, 66), highOrMediumConfidencePercent: percent(13, 66), ceiling: "POST_HOC_EDIT_SEMANTICS_NOT_OBSERVABLE_FOR_53_OF_66_FAILURES" },
  portfolioFinding: "The runtime made patch application, syntax, visible/hidden tests, safety, and rollback auditable. Its privacy-preserving persistence intentionally omitted raw edits, limiting post-hoc semantic diagnosis and exposing an observability ceiling distinct from demonstrated model, retrieval, or action-interface causes.",
  privacyTradeoff: "The historical policy minimized retained source-like model output and secret exposure. The cost is that an edit digest proves identity but not semantic intent or fault.",
  prohibitedInference: ["No semantic meaning from hashes", "No reassignment of T14 to T1-T10", "No claim that T14 is one shared cause", "No claim that model semantic capability is adequate or dominant"], targetModelCalls: 0,
});

const protocol = {
  schemaVersion: 1, protocolId: "dca-privacy-safe-semantic-observability-experiment-v1", state: "PREPARED_NOT_PREREGISTERED_NOT_EXECUTED", classification: "NEW_REPOSITORY_DISJOINT_DIAGNOSTIC_PROTOCOL_ONLY", preparedAt: completedAt, ownerDecision: { frozenGate: "G5_MIXED_SEMANTIC_CEILING__NO_SINGLE_INTERVENTION", selectedExperiment: "PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_EXPERIMENT", exactlyOneExperiment: true },
  researchQuestion: "Can privacy-minimized structured mutation features materially increase supported T1-T9 failure-cause classification coverage without retaining raw model output or weakening local-first privacy?",
  hypothesis: "Level-1 deterministic derived edit features increase supported semantic classification coverage and reduce T14 relative to Level-0 hash-only views, without raw-output persistence or secret leakage.",
  population: { tasks: 80, minimumSatisfied: true, source: "NEW_REPOSITORY_DISJOINT_TASKS", overlapWithAnalysisExposed95: 0, difficultyAndCategoryBalance: "PREREGISTER_BEFORE_CALLS", mutationRequired: true },
  fixedVariables: { model: "TIGER-Lab/FIM-7B", revision: "5a1d4294185e4fa0bbd40750c87d0beab7e67a3a", modelStatus: "BEST_RESEARCH_MODEL__STRONGEST_SCORED_RESEARCH_CANDIDATE_ASSISTED_FLOOR_ONLY", patchInterface: "E-EDIT_P2_RESEARCH_ONLY", retrieval: "E-MIN-V2", contextPackaging: "C1", servingAndDecoding: "USE_EXISTING_FROZEN_FIM_PROFILE_EXACTLY", verificationHarness: "EXISTING_FROZEN_HARNESS", candidateSpecificTuning: false },
  independentVariable: "SEMANTIC_EVIDENCE_RETENTION",
  design: { unit: "FIRST_ATTEMPT_FAILURE", modelCallsPerTask: 1, retentionViewsFromSameCall: ["L0_HASH_ONLY", "L1_STRUCTURED_DERIVED_EDIT_FEATURES"], extraModelCallsForRetentionComparison: 0, pairing: "Each transient edit deterministically yields both L0 and L1 analyst views; analysts are blinded to the alternate view.", objectiveIsModelSuccessImprovement: false },
  level1Schema: { taskId: "string", repositoryRevision: "sha256", selectedFile: "normalized repo-relative path after secret scan", range: { startLine: "positive integer", endLine: "positive integer" }, targetSymbol: "hash plus kind or null", replacementLength: "integer only", changedAstNodeTypes: "sorted enum/counts", identifiersReferencedOrModified: "salted hashes plus role/count; never raw names", literalChanges: "literal type, length and salted hash; never raw literal", operatorChanges: "bounded operator enums", controlFlowChanges: "AST node enum/count deltas", apiCallChanges: "salted callee hashes and add/remove counts", importChanges: "module-specifier hash and add/remove counts", canonicalEditDigest: "sha256", verificationFailure: "frozen stage/status/code and bounded diagnostic hash", visibleBehavioralEffect: "PASS/FAIL/NOT_RUN plus bounded assertion category/hash" },
  extraction: { producer: "DETERMINISTIC_TRANSIENT_LOCAL_EXTRACTOR", method: "Parse before/after source with pinned Tree-sitter; compute feature deltas before deleting replacement bytes.", rawModelOutputPersisted: false, rawEditBodyPersisted: false, sourceRepersisted: false, hiddenOracleExposedToModel: false, secretScanningBeforePersistence: true, featureAllowlistExact: true, transientDeletionRequiredBeforeNextTask: true },
  privacyTiers: { L0_HASH_ONLY: { authorizedForFuturePreregisteredRun: true, purpose: "matched historical baseline" }, L1_STRUCTURED_DERIVED_EDIT_FEATURES: { authorizedForFuturePreregisteredRun: true, preferred: true, rawIdentifiersOrLiterals: false }, L2_BOUNDED_LOCAL_ONLY_EDIT_BODY: { authorized: false, status: "REQUIRES_SEPARATE_EXPLICIT_PRIVACY_APPROVAL", prerequisites: ["local-only ignored storage", "0600 or stronger access control", "no surrounding context", "bounded replacement only", "redaction", "fixed TTL and verified deletion", "never uploaded"] } },
  privacyDecisionGate: { evaluateAfterL1: true, L2MayBeProposedOnlyIf: ["L1 supported T1-T9 coverage remains below 0.30", "L1 raw/derived privacy checks all pass", "written necessity analysis shows which causes cannot be distinguished", "separate owner approval is obtained"], automaticL2Authorization: false },
  frozenTaxonomy: { source: { path: prereg.path, sha256: prereg.sha256 }, categories: prereg.value.taxonomy.categories, precedence: prereg.value.taxonomy.precedence, changeAllowedAfterCallsStart: false },
  analysisPlan: { primaryDenominator: "all first-attempt failures among 80 tasks", l0AndL1Classification: "Apply the same frozen T1-T14 rules independently to paired views", audits: "Two independent passes; disagreements preserved and adjudicated fail-closed to T14/LOW", noPrivateReasoningPersistence: true, noSemanticInferenceFromDigest: true },
  successCriteria: { supportedT1ToT9Coverage: { L1Minimum: 0.30, L1MinusL0MinimumAbsolute: 0.20 }, highOrMediumConfidenceRateL1Minimum: 0.50, t14RateL1Maximum: 0.60, interAuditAgreement: { rawAgreementMinimum: 0.80, cohensKappaMinimum: 0.60 }, privacyAndSafety: { rawModelOutputsPersisted: 0, rawEditBodiesPersisted: 0, secretFindings: 0, hiddenOracleLeaks: 0, unauthorizedL2Records: 0, wrongFileMutations: 0, safetyViolations: 0 } },
  interpretation: { passMeaning: "L1 is a viable privacy-preserving diagnostic evidence tier.", failMeaning: "L1 did not establish adequate observability; it does not authorize L2 or prove model semantics adequate.", futureTreatmentExperiment: "Separate and selected only after the dominant supported cause is observed." },
  executionGate: { executedInSessionC: false, futureRequirements: ["separate immutable preregistration", "owner authorization for target-model calls", "sealed 80-task manifest/oracle", "deterministic extractor security regression", "source/serving closure", "clean runtime preflight"], protectedActionsNotAuthorizedHere: ["model call", "model download", "retry", "L2 retention", "product promotion"] },
};
const protocolRef = await publish("benchmarks/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_PROTOCOL.v1.json", protocol);

const productRef = await publish("docs/experiments/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_PRODUCT_DECISION.v1.json", { schemaVersion: 1, decisionId: "dca-semantic-failure-decomposition-product-decision-v1", status: "PRESERVE_EXISTING_PRODUCT_STATE", decidedAt: completedAt, inputs: { gateDecision: gateRef, observabilityCeiling: observabilityRef, nextProtocol: protocolRef }, decisions: { mutation: "KEEP_MUTATION_DISABLED", FIM: "BEST_RESEARCH_MODEL__STRONGEST_SCORED_RESEARCH_CANDIDATE_ASSISTED_FLOOR_ONLY", EEDITP2: "RESEARCH_ONLY", semanticPostHocAnalysisIsPromotionEvidence: false, retentionArchitectureChanged: false, adrRequired: false }, rationale: "Session C diagnoses an evidence-retention limitation and prepares an experiment; it does not validate a product mutation path or adopt a durable raw-edit retention policy.", targetModelCalls: 0 });
const ceilingRef = await publish("docs/experiments/patch-interface/PATCH_CAPABILITY_CEILING.v7.json", { schemaVersion: 7, reportId: "dca-patch-capability-ceiling-v7", status: "PASS", generatedAt: completedAt, supersedes: { path: priorCeiling.path, sha256: priorCeiling.sha256, reason: "Append-only Session-C correction of causal-claim boundary" }, immutableEvidence: { gateDecision: gateRef, observabilityCeiling: observabilityRef, productDecision: productRef }, observedCeiling: { executionStageFindingPreserved: "Behavioral verification remains where most failures became visible.", causalAttributionCorrection: "Historical artifacts cannot reliably distinguish the semantic cause for 53/66 failures.", dominantDiagnosableLimitation: "SEMANTIC_OBSERVABILITY", notEstablished: ["retrieval as dominant", "P2 representation as dominant", "syntax/code formation as dominant", "model semantic capability as dominant or adequate"] }, conclusion: gates.G5.preciseInterpretation, productRecommendation: "KEEP_MUTATION_DISABLED", nextScientificExperiment: protocolRef });
const reportRef = await publish("docs/experiments/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_FINAL_REPORT.v1.json", { schemaVersion: 1, reportId: "dca-semantic-failure-decomposition-final-report-v1", status: "PASS_INTERPRETATION_COMPLETE", generatedAt: completedAt, immutableInputs, artifacts: { gateDecision: gateRef, observabilityCeiling: observabilityRef, protocol: protocolRef, productDecision: productRef, capabilityCeiling: ceilingRef }, quantified, questions: { Q1: "No. T14/LOW is 53/66 and supported T1-T9 coverage is 0/66.", Q2: "No. Retrieval is directly supported for 5/66 and G1 fails.", Q3: "No. P2 action/representation is directly supported for 2/66.", Q4: "No. Syntax/code formation is 6/66 and fails the unique-largest G4 rule.", Q5: "No. Model semantic capacity is neither conclusively dominant nor proven adequate because semantic edit evidence is unavailable.", Q6: gates.G5.preciseInterpretation }, retry: { decision: "RETRY_NO_MATERIAL_GAIN", T11Recovered: 0, T12Recovered: 0, T13Recovered: 0, T14Recovered: 1, limitation: "Repeated T14 edits do not identify the repeated semantic cause." }, selectedNextExperiment: "PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_EXPERIMENT", selectedExperimentCount: 1, targetModelCalls: 0 });

const coreRefs = [gateRef, observabilityRef, protocolRef, productRef, ceilingRef, reportRef];
const sourcePaths = ["services/semantic-failure-decomposition/src/index.ts", "tests/semantic-failure-decomposition.test.ts", "scripts/finalize_semantic_failure_decomposition_session_c.ts", "package.json", "package-lock.json", "CONTEXT.md", "docs/exec-plans/active/MASTER_EXECUTION_PLAN.md"];
const sourceEntries = await Promise.all(sourcePaths.map(async (relative) => { const bytes = await regular(relative); return { path: relative, sha256: sha256(bytes), bytes: bytes.byteLength }; }));
const sourceClosure = { entries: sourceEntries, sha256: sha256(sourceEntries.map((entry) => `${entry.path}\0${entry.sha256}\0${entry.bytes}`).join("\n")) };
const commands = [
  await command("npx", ["tsc", "--ignoreConfig", "--noEmit", "--strict", "--skipLibCheck", "--target", "ES2022", "--module", "ESNext", "--moduleResolution", "Bundler", "--types", "node", ...sourcePaths.filter((item) => item.endsWith(".ts"))]),
  await command("npm", ["run", "typecheck"]), await command("npm", ["run", "test"]), await command("npm", ["run", "build"]), await command("npm", ["run", "validate:design"]),
  await command("npx", ["vitest", "run", "tests/patch-interface-runtime.test.ts", "tests/tool-runtime.test.ts"]),
];
for (const ref of coreRefs) if ((await verified(ref.path)).sha256 !== ref.sha256) throw new Error(`Published artifact drift: ${ref.path}`);
const secretPattern = /(hf_[A-Za-z0-9]{20,}|sk-[A-Za-z0-9]{20,}|Bearer\s+[A-Za-z0-9._-]{20,})/;
for (const ref of coreRefs) if (secretPattern.test((await regular(ref.path)).toString("utf8"))) throw new Error(`Secret-shaped output: ${ref.path}`);
const { stdout: processes } = await exec("ps", ["-eo", "args="], { cwd: root }), { stdout: sockets } = await exec("ss", ["-ltn"], { cwd: root }), { stdout: apps } = await exec("nvidia-smi", ["--query-compute-apps=pid,process_name,used_memory", "--format=csv,noheader,nounits"], { cwd: root }), { stdout: ambient } = await exec("nvidia-smi", ["--query-gpu=memory.used", "--format=csv,noheader,nounits"], { cwd: root }), { stdout: worktrees } = await exec("git", ["worktree", "list", "--porcelain"], { cwd: root });
const modelProcessCount = processes.split("\n").filter((line) => /vllm\.entrypoints|launch_model_tournament_candidate\.py|run_best_7b_bounded_retry/.test(line) && !line.includes("finalize_semantic_failure")).length;
const port8000Clear = !sockets.split("\n").some((line) => /(?:^|:)8000\s/.test(line)), computeProcesses = apps.split("\n").filter(Boolean).length, ambientGpuMemoryMiB = Number(ambient.trim()), worktreeCount = worktrees.split("\n").filter((line) => line.startsWith("worktree ")).length;
const stateEntries = await readdir(path.join(root, ".runtime/model")).catch(() => []), ephemeralState = stateEntries.filter((name) => /api-key|start|launch|ready/i.test(name)), tempEntries = (await readdir("/tmp")).filter((name) => /^dca-(semantic-failure|model-tournament|best-7b)/.test(name));
if (modelProcessCount || computeProcesses || !port8000Clear || ephemeralState.length || tempEntries.length || worktreeCount !== 1) throw new Error("Runtime cleanup failed");
const cleanup = { targetModelCalls: 0, vllmOrModelProcesses: modelProcessCount, modelComputeProcesses: computeProcesses, modelGpuAllocationMiB: 0, ambientGpuMemoryMiB, port8000Clear, ephemeralStateAbsent: ephemeralState.length === 0, temporaryDirectories: tempEntries.length, worktrees: worktreeCount };
const validationRef = await publish("docs/experiments/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_SESSION_C_VALIDATION.v1.json", { schemaVersion: 1, validationId: "dca-semantic-failure-decomposition-session-c-validation-v1", status: "PASS", validatedAt: completedAt, inputs: { report: reportRef, gateDecision: gateRef, observabilityCeiling: observabilityRef, protocol: protocolRef }, checks: { primaryDistribution: "PASS_66", observabilityQuantification: "PASS", frozenGates: "PASS_G1_G2_G3_G4_FAIL_G5_APPLIED", exactlyOneNextExperiment: "PASS", protocolPreparedNotExecuted: "PASS", productStatePreserved: "PASS", strictTypeScript: "PASS", projectTypecheck: "PASS", completeTests: "PASS", productionBuild: "PASS", designValidation: "PASS", securityRegression: "PASS_PATCH_AND_TOOL_RUNTIME", secretScan: "PASS", classificationArtifacts: "PASS", checksums: "PASS", sourceClosure: "PASS", lineage: "PASS", worktreeCleanup: "PASS" }, commands, sourceClosure, cleanup });
const sessionRef = await publish("docs/experiments/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_SESSION_C.v1.json", { schemaVersion: 1, sessionId: "dca-semantic-failure-decomposition-session-c-v1", session: "C", status: "PASS", classification: "ZERO_TARGET_MODEL_CALL_INTERPRETATION_GATE_APPLICATION_AND_PROTOCOL_PREPARATION", completedAt, inputs: immutableInputs, artifacts: { finalReport: reportRef, gateDecision: gateRef, observabilityCeiling: observabilityRef, nextProtocol: protocolRef, productDecision: productRef, capabilityCeiling: ceilingRef, validation: validationRef }, gates, strongestConclusion: gates.G5.preciseInterpretation, selectedNextExperiment: "PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_EXPERIMENT", selectedExperimentCount: 1, nextExperimentExecuted: false, historicalDecisions: { retry: "RETRY_NO_MATERIAL_GAIN", mutation: "KEEP_MUTATION_DISABLED", FIM: "BEST_RESEARCH_MODEL__STRONGEST_SCORED_RESEARCH_CANDIDATE_ASSISTED_FLOOR_ONLY", EEDITP2: "RESEARCH_ONLY", changed: false }, closedHoldout: "ANALYSIS_EXPOSED_NOT_FRESH_PROMOTION_EVIDENCE", cleanup, protectedActions: { targetModelInference: false, modelDownload: false, FIMExecution: false, retry: false, unrestrictedRawOutputPersistence: false, L2RetentionAuthorization: false, sudo: false, commit: false, remote: false, push: false, pullRequest: false, tag: false, release: false, signing: false }, stop: "SESSION_C_BOUNDARY_REACHED" });
const reviewRef = await publish("docs/experiments/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_SESSION_C_REVIEW.v1.json", { schemaVersion: 1, reviewId: "dca-semantic-failure-decomposition-session-c-dual-axis-review-v1", status: "PASS", reviewedAt: completedAt, inputs: { sessionC: sessionRef, validation: validationRef }, specReview: { status: "PASS", checks: ["G1-G5 applied literally", "T14 not reassigned", "exactly one next protocol", "zero calls", "product state preserved", "Session-C stop boundary"] }, standardsReview: { status: "PASS", checks: ["append-only artifacts", "atomic no-clobber publication", "privacy-tiered protocol", "secret scan", "source closure", "runtime cleanup"] }, synthesisSkill: { D02: "Protocol includes actor-independent fields, acceptance thresholds, dependencies, privacy levels, execution gate and traceable outputs.", D07: "Spec and standards axes were evaluated separately before aggregate PASS." } });
const indexRef = await publish("docs/experiments/model-specialization/semantic-failure-decomposition-session-b/SEMANTIC_FAILURE_DECOMPOSITION_RESULTS_INDEX.v2.json", { schemaVersion: 2, indexId: "dca-semantic-failure-decomposition-results-index-v2", status: "PASS_SESSION_C_COMPLETE", generatedAt: completedAt, supersedes: { path: priorIndex.path, sha256: priorIndex.sha256 }, sessions: { A: { path: sessionA.path, sha256: sessionA.sha256 }, B: { path: sessionB.path, sha256: sessionB.sha256 }, C: sessionRef }, artifacts: { classificationMatrix: { path: classification.path, sha256: classification.sha256 }, finalReport: reportRef, gateDecision: gateRef, observabilityCeiling: observabilityRef, nextProtocol: protocolRef, productDecision: productRef, capabilityCeiling: ceilingRef, validation: validationRef, review: reviewRef }, population: { failures: 66, controls: 29, total: 95 }, primaryCounts, quantified, gates, selectedNextExperiment: "PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_EXPERIMENT", selectedExperimentCount: 1, nextExperimentExecuted: false, targetModelCallsSessionC: 0 });
for (const ref of [validationRef, sessionRef, reviewRef, indexRef]) await verified(ref.path, ref.sha256);
process.stdout.write(`${JSON.stringify({ status: "PASS", sessionC: sessionRef, resultsIndex: indexRef, validation: validationRef, review: reviewRef, gates, selectedNextExperiment: "PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_EXPERIMENT", cleanup }, null, 2)}\n`);
