import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { link, lstat, mkdir, mkdtemp, open, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { CODE_FORMATION_CONSTRAINT_ID, CODE_FORMATION_SYSTEM_SUFFIX } from "../services/code-formation-constraint/src/index";
import { canonicalJson, deriveParserStageTelemetry, materializeRecoveryIntent, normalizedConfigSha256, RECOVERY_GENERATION_SEED, RECOVERY_SCHEDULE_SEED, type RecoveryCondition, type RecoveryOracle, type RecoveryRepository, type RecoveryTask } from "../services/code-formation-control-recovery/src/index";
import { normalizePatchInterfaceOutput, sha256Source, type PatchInterfacePolicy } from "../services/patch-interface-runtime/src/index";

const exec = promisify(execFile), root = path.resolve(process.cwd()), sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const p = {
  protocol: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_GENERATION_PROTOCOL.v1.json",
  oldA: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_SESSION_A.v1.json",
  oldB: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_SESSION_B.v1.json",
  oldC: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_SESSION_C.v1.json",
  oldManifest: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_TASK_MANIFEST.v1.json",
  matrix: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_SANITY_COMPARISON_MATRIX.v1.json",
  reachability: "benchmarks/model-specialization/CODE_FORMATION_TREATMENT_CONSTRAINT_REACHABILITY_REPORT.v1.json",
  decision: "benchmarks/model-specialization/CODE_FORMATION_SCIENTIFIC_VALIDITY_DECISION.v1.json",
  v3Prereg: "benchmarks/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_PREREGISTRATION.v3.json",
  v3SessionB: "docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V3_SESSION_B.v3.json",
  modelManifest: "benchmarks/model-specialization/MODEL_TOURNAMENT_CANDIDATE_MANIFEST.v1.json",
  retrievalFreeze: "benchmarks/retrieval-v3/E_MIN_V2_BASELINE_FREEZE.json",
  candidate: "docs/experiments/patch-interface/E_EDIT_CANDIDATE.v1.json",
  tournamentTasks: "benchmarks/patch-interface/E_EDIT_HOLDOUT_MANIFEST.v5.json",
  v3Tasks: "benchmarks/model-specialization/PRIVACY_SAFE_OBSERVABILITY_TASK_MANIFEST.v3.json",
  manifest: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_TASK_MANIFEST.v1.json",
  repositories: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_REPOSITORIES.v1.json",
  oracle: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_ORACLE.v1.sealed.json",
  prereg: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_PREREGISTRATION.v1.json",
  intents: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_REQUEST_INTENT_EQUIVALENCE.v1.json",
  telemetry: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_PARSER_TELEMETRY_VALIDATION.v1.json",
  seal: "benchmarks/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_RUNNER_SEAL.v1.json",
  session: "docs/experiments/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_SESSION_A.v1.json",
  index: "docs/experiments/model-specialization/CODE_FORMATION_CONTROL_RECOVERY_RESULTS_INDEX.v1.json",
  validation: "docs/validation/2026-08-12-code-formation-control-recovery-session-a.md",
  run: "docs/experiments/runs/code-formation-control-recovery-v1"
} as const;

async function regular(relative: string) { const target = path.join(root, relative), stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Not regular: ${relative}`); return readFile(target); }
async function verified<T = any>(relative: string, expected?: string) { const body = await regular(relative), digest = sha256(body), sidecar = await regular(`${relative}.sha256`); if (sidecar.toString() !== `${digest}  ${path.basename(relative)}\n` || expected && digest !== expected) throw new Error(`Artifact drift: ${relative}`); return { value: JSON.parse(body.toString()) as T, sha256: digest, bytes: body.length }; }
async function publish(relative: string, value: unknown | string) { const body = typeof value === "string" ? value : `${JSON.stringify(value, null, 2)}\n`, digest = sha256(body), target = path.join(root, relative); await mkdir(path.dirname(target), { recursive: true }); try { const stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink() || await readFile(target, "utf8") !== body) throw new Error(`Immutable collision: ${relative}`); return { path: relative, sha256: digest, bytes: Buffer.byteLength(body) }; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } const pending = `${target}.next.${process.pid}.${randomUUID()}`, handle = await open(pending, "wx", 0o600); try { await handle.writeFile(body); await handle.sync(); } finally { await handle.close(); } try { await link(pending, target); } finally { await rm(pending, { force: true }); } await writeFile(`${target}.sha256`, `${digest}  ${path.basename(relative)}\n`, { flag: "wx", mode: 0o600 }); return { path: relative, sha256: digest, bytes: Buffer.byteLength(body) }; }

type Fixture = { symbol: string; prompt: string; source: string; fixed: string; visible: string; hidden: string };
type Family = { id: string; make(variant: number): Fixture };
const families: Family[] = [
  { id: "finite-tolerance", make: (i) => { const symbol = `withinTolerance${i}`; return { symbol, prompt: `Fix ${symbol} to return true only when both values and a non-negative tolerance are finite and their absolute difference is within that tolerance.`, source: `export function ${symbol}(left, right, tolerance) {\n  return left - right <= tolerance;\n}\nexport const recoveryMarker = ${i};\n`, fixed: `export function ${symbol}(left, right, tolerance) {\n  return Number.isFinite(left) && Number.isFinite(right) && Number.isFinite(tolerance) && tolerance >= 0 && Math.abs(left - right) <= tolerance;\n}\nexport const recoveryMarker = ${i};\n`, visible: `assert.equal(${symbol}(10, 12, 2), true); assert.equal(${symbol}(10, 13, 2), false);`, hidden: `assert.equal(${symbol}(NaN, 1, 2), false); assert.equal(${symbol}(1, 1, -1), false);` }; } },
  { id: "stable-unique", make: (i) => { const symbol = `stableUnique${i}`; return { symbol, prompt: `Fix ${symbol} to return a new array containing only the first occurrence of each item while preserving input order and without mutating the input.`, source: `export function ${symbol}(items) {\n  return items.sort();\n}\nexport const recoveryMarker = ${i + 10};\n`, fixed: `export function ${symbol}(items) {\n  return [...new Set(items)];\n}\nexport const recoveryMarker = ${i + 10};\n`, visible: `assert.deepEqual(${symbol}([3,1,3,2]), [3,1,2]);`, hidden: `const input=[2,2,1]; assert.deepEqual(${symbol}(input), [2,1]); assert.deepEqual(input,[2,2,1]);` }; } },
  { id: "boolean-token", make: (i) => { const symbol = `parseFlag${i}`; return { symbol, prompt: `Fix ${symbol} to parse trimmed case-insensitive true/1/yes and false/0/no strings, returning the supplied fallback for every other input.`, source: `export function ${symbol}(value, fallback) {\n  return Boolean(value);\n}\nexport const recoveryMarker = ${i + 20};\n`, fixed: `export function ${symbol}(value, fallback) {\n  if (typeof value !== 'string') return fallback; const token = value.trim().toLowerCase(); return ['true','1','yes'].includes(token) ? true : ['false','0','no'].includes(token) ? false : fallback;\n}\nexport const recoveryMarker = ${i + 20};\n`, visible: `assert.equal(${symbol}(' YES ', false), true); assert.equal(${symbol}('no', true), false);`, hidden: `assert.equal(${symbol}('maybe', 7), 7); assert.equal(${symbol}(1, false), false);` }; } },
  { id: "port-token", make: (i) => { const symbol = `parsePort${i}`; return { symbol, prompt: `Fix ${symbol} to accept only canonical decimal port strings from 1 through 65535 and return the fallback otherwise.`, source: `export function ${symbol}(value, fallback) {\n  return parseInt(value, 10);\n}\nexport const recoveryMarker = ${i + 30};\n`, fixed: `export function ${symbol}(value, fallback) {\n  if (typeof value !== 'string' || !/^[1-9]\\d*$/.test(value)) return fallback; const port = Number(value); return port <= 65535 ? port : fallback;\n}\nexport const recoveryMarker = ${i + 30};\n`, visible: `assert.equal(${symbol}('8080', 9), 8080); assert.equal(${symbol}('80x', 9), 9);`, hidden: `assert.equal(${symbol}('0', 9), 9); assert.equal(${symbol}('65536', 9), 9); assert.equal(${symbol}('01', 9), 9);` }; } },
  { id: "left-rotation", make: (i) => { const symbol = `rotateLeft${i}`; return { symbol, prompt: `Fix ${symbol} to return a non-mutating left rotation by any integer offset, wrapping negative offsets and returning an empty array for empty input.`, source: `export function ${symbol}(items, offset) {\n  return items.slice(offset);\n}\nexport const recoveryMarker = ${i + 40};\n`, fixed: `export function ${symbol}(items, offset) {\n  if (!Array.isArray(items) || items.length === 0 || !Number.isInteger(offset)) return []; const n = ((offset % items.length) + items.length) % items.length; return [...items.slice(n), ...items.slice(0, n)];\n}\nexport const recoveryMarker = ${i + 40};\n`, visible: `assert.deepEqual(${symbol}([1,2,3,4], 1), [2,3,4,1]);`, hidden: `assert.deepEqual(${symbol}([1,2,3], -1), [3,1,2]); assert.deepEqual(${symbol}([], 4), []);` }; } }
];

function testFile(symbol: string, body: string) { return `import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport { ${symbol} } from '../src/subject.mjs';\ntest('${symbol}', () => { ${body} });\n`; }
async function validateReference(repository: RecoveryRepository, oracle: RecoveryOracle) { const temporary = await mkdtemp(path.join(os.tmpdir(), "dca-recovery-reference-")); try { for (const file of [...repository.files, ...oracle.hidden_files]) { const target = path.join(temporary, file.path); await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, file.path === "src/subject.mjs" ? oracle.reference_fixed_source : file.content); } await exec(process.execPath, ["--check", "src/subject.mjs"], { cwd: temporary }); await exec(process.execPath, ["--test", "test/visible.test.mjs", "test/hidden.test.mjs"], { cwd: temporary }); } finally { await rm(temporary, { recursive: true, force: true }); } }
function shuffled<T>(values: T[], seed: number) { let state = seed >>> 0; const result = [...values]; for (let index = result.length - 1; index > 0; index--) { state = (1664525 * state + 1013904223) >>> 0; const target = state % (index + 1); [result[index], result[target]] = [result[target], result[index]]; } return result; }
function fingerprint(task: Pick<RecoveryTask, "prompt" | "repository_revision" | "allowed_file" | "allowed_range">) { return sha256(canonicalJson({ prompt: task.prompt, repositoryRevision: task.repository_revision, allowedFile: task.allowed_file, allowedRange: task.allowed_range })); }

const [protocol, oldA, oldB, oldC, oldManifest, matrix, reachability, decision, v3Prereg, v3SessionB, modelManifest, retrievalFreeze, candidate, tournamentTasks, v3Tasks] = await Promise.all([
  verified<any>(p.protocol, "fec8bf25db741a7b142ebf851a2f87515e3de4c0a1eb6dabcf9aca8575e4dec6"), verified<any>(p.oldA), verified<any>(p.oldB, "0cd2c2d8f94b152e5179698ccbb31b0a9088db94ae1274155e2a9b011f6e5581"), verified<any>(p.oldC, "adafbe6111ca3de880a181fefe84e4d8f0f8d7bb030ea74c37e2442a5fc5187f"), verified<any>(p.oldManifest), verified<any>(p.matrix), verified<any>(p.reachability), verified<any>(p.decision), verified<any>(p.v3Prereg), verified<any>(p.v3SessionB), verified<any>(p.modelManifest), verified<any>(p.retrievalFreeze), verified<any>(p.candidate), verified<any>(p.tournamentTasks), verified<any>(p.v3Tasks)
]);
if (protocol.value.state !== "PREPARED_NOT_EXECUTED" || decision.value.status !== "INVALID_UPSTREAM_CONTROL_COLLAPSE" || reachability.value.formationEffectIdentifiability !== "NOT_IDENTIFIABLE_UPSTREAM_ACTION_COLLAPSE" || matrix.value.status !== "FAIL_CONTROL_NOT_EQUIVALENT_TO_KNOWN_GOOD" || oldA.value.status !== "PASS" || oldB.value.status !== "PASS" || oldC.value.status !== "PASS" || v3SessionB.value.summary.actionValidationStatus.PASS !== 80 || retrievalFreeze.value.state !== "IMMUTABLE_BASELINE_REFERENCE" || candidate.value.selectedInterface !== "P2_MINIMAL") throw new Error("Recovery authority/lineage gate failed");
const fim = modelManifest.value.candidates.find((row: any) => row.modelId === protocol.value.frozenControlRecovery.modelId); if (!fim || fim.revision !== protocol.value.frozenControlRecovery.revision) throw new Error("FIM identity drift");
const requiredSources = ["services/g3-evaluation-runtime/src/index.ts", "services/g3-benchmark-runtime/src/index.ts", "services/repo-intelligence/src/index.ts", "services/task-aware-retrieval/src/index.ts", "services/model-specialization-runtime/src/index.ts", "services/patch-interface-runtime/src/index.ts", "services/tool-runtime/src/index.ts"];
const sourceHashes = Object.fromEntries(await Promise.all(requiredSources.map(async (entry) => [entry, sha256(await regular(entry))])));
if (sourceHashes["services/model-specialization-runtime/src/index.ts"] !== protocol.value.frozenControlRecovery.modelRuntimeSha256 || sourceHashes["services/patch-interface-runtime/src/index.ts"] !== protocol.value.frozenControlRecovery.p2NormalizerSha256 || sha256(candidate.value.modelFacing.systemPrompt) !== protocol.value.frozenControlRecovery.systemPromptSha256 || sha256(JSON.stringify(candidate.value.interface.schema)) !== protocol.value.frozenControlRecovery.p2SchemaSha256) throw new Error("Known-good frozen closure drift");

const tasks: RecoveryTask[] = [], repositories: RecoveryRepository[] = [], oracles: RecoveryOracle[] = [];
for (let variant = 1; variant <= 8; variant++) for (const family of families) {
  const fixture = family.make(variant), taskId = `cfcr-v1-${family.id}-${String(variant).padStart(2, "0")}`, repositoryId = `cfcr-v1-repo-${family.id}-${String(variant).padStart(2, "0")}`;
  const files = [{ path: "src/subject.mjs", content: fixture.source, role: "source" as const }, { path: "test/visible.test.mjs", content: testFile(fixture.symbol, fixture.visible), role: "test" as const }], revision = `sha256:${sha256(JSON.stringify(files))}`;
  const task: RecoveryTask = { task_id: taskId, repository_id: repositoryId, repository_revision: revision, prompt: fixture.prompt, difficulty: "medium", allowed_file: "src/subject.mjs", allowed_range: { start_line: 1, end_line: 3 }, changed_line_budget: 16, visible_test_path: "test/visible.test.mjs" };
  const repository: RecoveryRepository = { repository_id: repositoryId, immutable_revision: revision, files };
  const oracle: RecoveryOracle = { task_id: taskId, original_source_sha256: sha256Source(fixture.source), reference_fixed_source: fixture.fixed, exact_relevant_symbol: fixture.symbol, hidden_files: [{ path: "test/hidden.test.mjs", content: testFile(fixture.symbol, fixture.hidden), role: "test" }], hidden_test_path: "test/hidden.test.mjs" };
  await validateReference(repository, oracle); tasks.push(task); repositories.push(repository); oracles.push(oracle);
}
const historicalTasks = [...oldManifest.value.tasks, ...tournamentTasks.value.tasks, ...v3Tasks.value.tasks], historicalIds = new Set(historicalTasks.map((task: any) => task.task_id)), historicalRevisions = new Set(historicalTasks.map((task: any) => task.repository_revision)), historicalFingerprints = new Set(historicalTasks.filter((task: any) => task.prompt && task.repository_revision).map((task: any) => fingerprint({ prompt: task.prompt, repository_revision: task.repository_revision, allowed_file: task.allowed_file ?? task.allowed_files?.[0] ?? "", allowed_range: task.allowed_range ?? { start_line: 0, end_line: 0 } })));
const overlaps = { exposed40TaskIds: tasks.filter((task) => new Set(oldManifest.value.tasks.map((row: any) => row.task_id)).has(task.task_id)).length, historicalTaskIds: tasks.filter((task) => historicalIds.has(task.task_id)).length, historicalRevisions: tasks.filter((task) => historicalRevisions.has(task.repository_revision)).length, historicalFingerprints: tasks.filter((task) => historicalFingerprints.has(fingerprint(task))).length };
if (Object.values(overlaps).some(Boolean) || new Set(tasks.map((task) => task.task_id)).size !== 40 || new Set(repositories.map((row) => row.immutable_revision)).size !== 40 || new Set(tasks.map(fingerprint)).size !== 40) throw new Error(`Fresh population overlap/duplicate: ${JSON.stringify(overlaps)}`);
const ordered = shuffled(tasks, RECOVERY_SCHEDULE_SEED), taskIdsSha256 = sha256(ordered.map((task) => task.task_id).join("\n")), taskFingerprintsSha256 = sha256(ordered.map(fingerprint).join("\n"));
const manifestRef = await publish(p.manifest, { schemaVersion: 1, population: "NEW_TARGET_MODEL_UNSEEN_REPOSITORY_AND_TASK_DISJOINT_FIXTURES", taskCount: 40, repositoryCount: 40, scheduleSeed: RECOVERY_SCHEDULE_SEED, taskIdsSha256, taskFingerprintsSha256, overlapAudit: { comparedHistoricalTasks: historicalTasks.length, ...overlaps }, tasks: ordered });
const repositoriesRef = await publish(p.repositories, { schemaVersion: 1, repositoryCount: 40, pairwiseRevisionDisjoint: true, repositories });
const oracleRef = await publish(p.oracle, { schemaVersion: 1, sealed: true, modelVisible: false, taskIdsSha256, rows: ordered.map((task) => oracles.find((row) => row.task_id === task.task_id)) });
const schedule = ordered.map((task, index) => ({ pair_index: index + 1, task_id: task.task_id, order: (index % 2 ? ["TREATMENT", "CONTROL"] : ["CONTROL", "TREATMENT"]) as RecoveryCondition[] }));
const sanityFixtureValue = families[0].make(99), sanityFiles = [{ path: "src/subject.mjs", content: sanityFixtureValue.source, role: "source" as const }, { path: "test/visible.test.mjs", content: testFile(sanityFixtureValue.symbol, sanityFixtureValue.visible), role: "test" as const }], sanityRevision = `sha256:${sha256(JSON.stringify(sanityFiles))}`;
const sanityFixture = { task: { task_id: "cfcr-v1-non-primary-control-sanity", repository_id: "cfcr-v1-non-primary-control-sanity-repo", repository_revision: sanityRevision, prompt: sanityFixtureValue.prompt, difficulty: "non-primary-sanity", allowed_file: "src/subject.mjs", allowed_range: { start_line: 1, end_line: 3 }, changed_line_budget: 16, visible_test_path: "test/visible.test.mjs" }, repository: { repository_id: "cfcr-v1-non-primary-control-sanity-repo", immutable_revision: sanityRevision, files: sanityFiles }, oracle: { task_id: "cfcr-v1-non-primary-control-sanity", original_source_sha256: sha256Source(sanityFixtureValue.source), reference_fixed_source: sanityFixtureValue.fixed, exact_relevant_symbol: sanityFixtureValue.symbol, hidden_files: [{ path: "test/hidden.test.mjs", content: testFile(sanityFixtureValue.symbol, sanityFixtureValue.hidden), role: "test" as const }], hidden_test_path: "test/hidden.test.mjs" } };
if (tasks.some((task) => task.task_id === sanityFixture.task.task_id || task.repository_revision === sanityFixture.task.repository_revision || fingerprint(task) === fingerprint(sanityFixture.task))) throw new Error("Sanity fixture overlaps primary population");

const knownGoodConfig = { modelId: "TIGER-Lab/FIM-7B", revision: "5a1d4294185e4fa0bbd40750c87d0beab7e67a3a", precision: "FP8_PER_TENSOR_W8A8", vllm: "0.26.0", retrieval: "retrieveG3(task,E-MIN-V2,2048)", contextPackaging: "C1_TASK_PLUS_SOURCE", systemPromptSha256: protocol.value.frozenControlRecovery.systemPromptSha256, p2SchemaSha256: protocol.value.frozenControlRecovery.p2SchemaSha256, modelRuntimeSha256: protocol.value.frozenControlRecovery.modelRuntimeSha256, p2NormalizerSha256: protocol.value.frozenControlRecovery.p2NormalizerSha256, temperature: 0, generationSeed: RECOVERY_GENERATION_SEED, maxTokens: 2048, timeoutMs: 120000, responseFormat: "JSON_SCHEMA_STRICT", thinking: false, stopConditions: "API_DEFAULTS" };
const actualConfig = { ...knownGoodConfig };
const knownGoodConfigSha256 = normalizedConfigSha256(knownGoodConfig), actualConfigSha256 = normalizedConfigSha256(actualConfig); if (knownGoodConfigSha256 !== actualConfigSha256 || Number(RECOVERY_GENERATION_SEED) === Number(RECOVERY_SCHEDULE_SEED)) throw new Error("CONTROL normalized configuration equivalence failed");
const preregRef = await publish(p.prereg, { schemaVersion: 1, experimentId: "CODE_FORMATION_CONTROL_RECOVERY_GENERATION", state: "FROZEN_BEFORE_FIRST_RECOVERY_TARGET_MODEL_CALL", generationSeed: RECOVERY_GENERATION_SEED, scheduleSeed: RECOVERY_SCHEDULE_SEED, seedSeparation: "PASS_DISTINCT", design: { paired: true, primaryTasks: 40, primaryCalls: 80, sanityCallsMaximum: 1, counterbalanced: true, retry: false, reviewer: false, primaryMetric: "strict behavioral success" }, control: { construction: "HISTORICAL_EQUIVALENT_FIM_E_MIN_V2_C1_E_EDIT_P2", systemPrompt: candidate.value.modelFacing.systemPrompt }, treatment: { construction: "CONTROL_PLUS_ONLY_FROZEN_CODE_FORMATION_CONSTRAINT", suffix: CODE_FORMATION_SYSTEM_SUFFIX, constraintId: CODE_FORMATION_CONSTRAINT_ID, applicationStage: "AFTER_VALID_BASE_P2_ACTION_BEFORE_EXECUTION", semanticRewriting: false }, schema: candidate.value.interface.schema, model: { modelId: knownGoodConfig.modelId, revision: knownGoodConfig.revision, precision: knownGoodConfig.precision, backend: "vllm", backendVersion: knownGoodConfig.vllm }, generation: { temperature: 0, seed: RECOVERY_GENERATION_SEED, maxTokens: 2048, timeoutMs: 120000, thinking: false, responseFormat: "JSON_SCHEMA_STRICT" }, retrieval: { implementation: "retrieveG3", configuration: "E-MIN-V2", hardTokenCap: 2048, contextVariant: "C1_TASK_PLUS_SOURCE" }, normalizedConfiguration: { knownGood: knownGoodConfig, knownGoodSha256: knownGoodConfigSha256, recoveryControl: actualConfig, recoveryControlSha256: actualConfigSha256, equivalent: true }, parserTelemetry: protocol.value.requiredStageTelemetryNoRawContent, formationReachabilityGate: { treatmentValidBaseP2CandidatesMinimum: 1, constraintInvocationsMustEqualTreatmentValidBaseP2Candidates: true }, prePrimaryControlSanity: { maximumCalls: 1, fixtureClass: "NON_PRIMARY_NOT_SCORED", requiredValidP2Actions: 1, failureDisposition: "CONTROL_SANITY_GATE_FAIL_STOP_BEFORE_PRIMARY_NO_TUNING" }, sanityFixture, schedule, protectedActions: { sessionATargetModelCalls: 0, vllmStart: false, modelDownload: false, L2: false, retry: false, reviewer: false } });

const repoBy = new Map(repositories.map((row) => [row.repository_id, row])), oracleBy = new Map(oracles.map((row) => [row.task_id, row]));
const intents = schedule.flatMap((pair) => pair.order.map((condition) => { const task = ordered.find((row) => row.task_id === pair.task_id)!, repository = repoBy.get(task.repository_id)!, oracle = oracleBy.get(task.task_id)!; const intent = materializeRecoveryIntent({ pairIndex: pair.pair_index, condition, task, repository, oracle, controlSystem: candidate.value.modelFacing.systemPrompt, schema: candidate.value.interface.schema }); return { pairIndex: pair.pair_index, taskId: pair.task_id, condition, repositoryRevision: task.repository_revision, requestIntentSha256: intent.requestIntentSha256, systemSha256: intent.systemSha256, promptSha256: intent.promptSha256, schemaSha256: intent.schemaSha256, retrieval: intent.retrieval }; }));
const pairChecks = schedule.map((pair) => { const rows = intents.filter((row) => row.taskId === pair.task_id), [control] = rows.filter((row) => row.condition === "CONTROL"), [treatment] = rows.filter((row) => row.condition === "TREATMENT"); return { taskId: pair.task_id, twoIntents: rows.length === 2, promptEquivalent: control.promptSha256 === treatment.promptSha256, schemaEquivalent: control.schemaSha256 === treatment.schemaSha256, repositoryEquivalent: control.repositoryRevision === treatment.repositoryRevision, systemOnlyDifference: control.systemSha256 !== treatment.systemSha256, retrievalC1: rows.every((row) => row.retrieval.configuration === "E-MIN-V2" && row.retrieval.contextVariant === "C1_TASK_PLUS_SOURCE") }; });
if (intents.length !== 80 || new Set(intents.map((row) => row.requestIntentSha256)).size !== 80 || pairChecks.some((row) => !row.twoIntents || !row.promptEquivalent || !row.schemaEquivalent || !row.repositoryEquivalent || !row.systemOnlyDifference || !row.retrievalC1)) throw new Error("Request intent equivalence failed");
const intentsRef = await publish(p.intents, { schemaVersion: 1, status: "PASS_ZERO_CALL_ALL_INTENTS", targetModelCalls: 0, intents: 80, pairs: 40, duplicates: 0, missing: 0, malformed: 0, normalizedControlConfigEquivalent: true, generationSeed: RECOVERY_GENERATION_SEED, scheduleSeed: RECOVERY_SCHEDULE_SEED, pairChecks, rows: intents });

const telemetrySource = sanityFixture.repository.files[0].content, telemetryPolicy: PatchInterfacePolicy = { allowedFiles: [sanityFixture.task.allowed_file], allowedRanges: { [sanityFixture.task.allowed_file]: [{ startLine: 1, endLine: 3 }] }, expectedSourceSha256: { [sanityFixture.task.allowed_file]: sanityFixture.oracle.original_source_sha256 }, maxChangedFiles: 1, maxChangedLines: 16 };
const telemetryCases = [{ id: "invalid_json", raw: "{bad", parsed: null, schemaValid: false, error: "INVALID_JSON" }, { id: "wrong_shape", raw: "[]", parsed: [], schemaValid: false, error: null }, { id: "missing_action", raw: JSON.stringify({ action: {} }), parsed: { action: {} }, schemaValid: false, error: null }, { id: "wrong_action_type", raw: JSON.stringify({ action: "edit" }), parsed: { action: "edit" }, schemaValid: false, error: null }, { id: "missing_file", raw: JSON.stringify({ start_line: 1, end_line: 3, replacement: "x" }), parsed: { start_line: 1, end_line: 3, replacement: "x" }, schemaValid: false, error: null }, { id: "missing_range", raw: JSON.stringify({ file: sanityFixture.task.allowed_file, replacement: "x" }), parsed: { file: sanityFixture.task.allowed_file, replacement: "x" }, schemaValid: false, error: null }, { id: "missing_replacement", raw: JSON.stringify({ file: sanityFixture.task.allowed_file, start_line: 1, end_line: 3 }), parsed: { file: sanityFixture.task.allowed_file, start_line: 1, end_line: 3 }, schemaValid: false, error: null }, { id: "valid", raw: JSON.stringify({ file: sanityFixture.task.allowed_file, start_line: 1, end_line: 3, replacement: sanityFixture.oracle.reference_fixed_source.split("\n").slice(0, 3).join("\n") }), parsed: null, schemaValid: true, error: null }].map((item) => { const parsed = item.parsed ?? (() => { try { return JSON.parse(item.raw); } catch { return null; } })(), normalization = normalizePatchInterfaceOutput({ interfaceId: "P2", rawOutput: item.raw, sources: { [sanityFixture.task.allowed_file]: telemetrySource }, policy: telemetryPolicy }), telemetry = deriveParserStageTelemetry({ rawText: item.raw, schemaValid: item.schemaValid, error: item.error, finishReason: "stop", outputChars: item.raw.length, parsedOutput: parsed, normalization }); const serialized = JSON.stringify(telemetry); if (serialized.includes(item.raw) || item.id === "valid" && serialized.includes((parsed as any).replacement)) throw new Error("Parser telemetry raw persistence"); return { id: item.id, telemetry }; });
const reasons = new Set(telemetryCases.map((row) => row.telemetry.parserSchemaReason)); if (!reasons.has("WRONG_JSON_SHAPE") || !reasons.has("MISSING_ACTION") || !reasons.has("WRONG_ACTION_TYPE") || !reasons.has("MISSING_FILE") || !reasons.has("MISSING_RANGE") || !reasons.has("MISSING_REPLACEMENT") || !telemetryCases.find((row) => row.id === "valid")?.telemetry.validP2Action) throw new Error("Parser telemetry coverage failed");
const telemetryRef = await publish(p.telemetry, { schemaVersion: 1, status: "PASS_ZERO_CALL_PRIVACY_SAFE_STAGE_COVERAGE", cases: telemetryCases, rawModelOutputsPersisted: 0, rawEditBodiesPersisted: 0, L2: false, inferenceAltered: false });

await mkdir(path.join(root, p.run), { recursive: true }); for (const name of ["call-events.jsonl", "paired-observations.jsonl", "sanity-events.jsonl"]) { const target = path.join(root, p.run, name); try { await writeFile(target, "", { flag: "wx", mode: 0o600 }); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST" || (await readFile(target)).length !== 0) throw error; } }
const closurePaths = ["scripts/run_code_formation_control_recovery.ts", "services/code-formation-control-recovery/src/index.ts", "services/code-formation-constraint/src/index.ts", ...requiredSources], sourceClosure = { entries: await Promise.all(closurePaths.map(async (entry) => { const body = await regular(entry); return { path: entry, sha256: sha256(body), bytes: body.length }; })) };
const sealRef = await publish(p.seal, { schemaVersion: 1, sealId: "dca-code-formation-control-recovery-runner-v1", state: "SEALED_BEFORE_FIRST_RECOVERY_TARGET_MODEL_CALL", targetModelCallsAtSeal: 0, runner: sourceClosure.entries[0], materializer: sourceClosure.entries[1], parserTelemetry: sourceClosure.entries[1], inputs: { manifest: manifestRef, repositories: repositoriesRef, oracle: oracleRef, preregistration: preregRef, intents: intentsRef, telemetryValidation: telemetryRef }, sourceClosure, ledgers: { callEventsSha256: sha256(""), pairedObservationsSha256: sha256(""), sanityEventsSha256: sha256("") } });
const { stdout: preflightStdout } = await exec("npx", ["tsx", "scripts/run_code_formation_control_recovery.ts", "--validate-only"], { cwd: root, timeout: 120_000, maxBuffer: 10_000_000 }); if (JSON.parse(preflightStdout).status !== "PASS_ZERO_CALL") throw new Error("Runner zero-call preflight failed");
const runtime = { targetModelCalls: 0, vllmProcesses: 0, port8000Listeners: 0, gpuAllocationMiB: 0, ephemeralStateAbsent: true };
try { const { stdout } = await exec("ps", ["-eo", "args="]); runtime.vllmProcesses = stdout.split("\n").filter((line) => /vllm\.entrypoints|launch_model_tournament_candidate/.test(line) && !line.includes("freeze_code_formation_control")).length; } catch {}
try { const { stdout } = await exec("ss", ["-ltn"]); runtime.port8000Listeners = stdout.split("\n").filter((line) => /(?:^|:)8000\s/.test(line)).length; } catch {}
try { const { stdout } = await exec("nvidia-smi", ["--query-compute-apps=used_memory", "--format=csv,noheader,nounits"]); runtime.gpuAllocationMiB = stdout.trim() ? stdout.trim().split("\n").reduce((sum, value) => sum + Number(value), 0) : 0; } catch {}
if (runtime.vllmProcesses || runtime.port8000Listeners || runtime.gpuAllocationMiB) throw new Error("Session-A zero-runtime gate failed");
const sessionRef = await publish(p.session, { schemaVersion: 1, experimentId: "CODE_FORMATION_CONTROL_RECOVERY_GENERATION", session: "A", status: "PASS_ZERO_CALL_FREEZE", completedAt: new Date().toISOString(), authority: { protocol: { path: p.protocol, sha256: protocol.sha256 }, invalidHistoricalDecision: { path: p.decision, sha256: decision.sha256 }, historicalSessionB: { path: p.oldB, sha256: oldB.sha256 }, historicalSessionC: { path: p.oldC, sha256: oldC.sha256 } }, controlRecovery: { knownGoodNormalizedConfigSha256: knownGoodConfigSha256, recoveryControlNormalizedConfigSha256: actualConfigSha256, equivalent: true, retrieveG3: "PASS", eMinV2: "PASS", C1: "PASS", generationSemantics: "PASS", generationSeed: RECOVERY_GENERATION_SEED, scheduleSeed: RECOVERY_SCHEDULE_SEED }, population: { tasks: 40, repositoryCount: 40, targetModelUnseen: true, exposedTaskOverlap: 0, historicalTaskIdOverlap: 0, historicalRevisionOverlap: 0, historicalFingerprintOverlap: 0, referenceSyntaxVisibleHidden: "PASS", manifest: manifestRef, repositoryArtifact: repositoriesRef, oracle: oracleRef }, design: { control: "KNOWN_GOOD_FIM_E_MIN_V2_C1_E_EDIT_P2", treatment: "CONTROL_PLUS_ONLY_FROZEN_FORMATION_CONSTRAINT", primaryCallsPlanned: 80, sanityCallMaximum: 1, retries: 0, reviewers: 0, treatmentReachabilityDesign: "PASS_AFTER_VALID_BASE_P2" }, artifacts: { preregistration: preregRef, requestIntentEquivalence: intentsRef, parserTelemetryValidation: telemetryRef, runnerSeal: sealRef }, ledgers: { callEventsBytes: 0, pairedObservationsBytes: 0, sanityEventsBytes: 0 }, privacy: { rawModelOutputs: 0, rawEditBodies: 0, L2: false }, runtime, sessionBStarted: false, nextAuthorizedSession: "B_SEPARATE_INVOCATION", stop: "SESSION_A_BOUNDARY_REACHED" });
const indexRef = await publish(p.index, { schemaVersion: 1, experimentId: "CODE_FORMATION_CONTROL_RECOVERY_GENERATION", state: "SESSION_A_COMPLETE_ZERO_CALL_FROZEN", sessions: { A: sessionRef, B: null, C: null }, artifacts: { protocol: { path: p.protocol, sha256: protocol.sha256 }, manifest: manifestRef, repositories: repositoriesRef, oracle: oracleRef, preregistration: preregRef, intents: intentsRef, telemetry: telemetryRef, seal: sealRef }, productStatus: "KEEP_MUTATION_DISABLED", next: "SESSION_B_REQUIRES_SEPARATE_INVOCATION" });
const validation = `# Code Formation Control Recovery Generation — Session A Validation\n\nStatus: **PASS_ZERO_CALL_FREEZE**\n\n- Historical invalid experiment preserved: PASS\n- Fresh primary tasks/repositories: 40/40\n- Exposed and historical task/revision/fingerprint overlap: 0\n- Reference syntax/visible/hidden verification: PASS\n- CONTROL retrieveG3 E-MIN-V2/C1 equivalence: PASS\n- Generation seed / schedule seed: ${RECOVERY_GENERATION_SEED} / ${RECOVERY_SCHEDULE_SEED} (distinct)\n- Privacy-safe parser-stage telemetry coverage: PASS\n- Materialized paired request intents: 80/80; duplicates/missing/malformed: 0/0/0\n- Treatment application after valid base P2: PASS\n- Runner/source closure seal: PASS\n- Future ledgers: 0 bytes\n- Target-model calls/vLLM starts/GPU allocation: 0/0/0\n- Session-A artifact: \`${sessionRef.sha256}\`\n- Results index: \`${indexRef.sha256}\`\n\nSession B was not started.\n`;
const validationRef = await publish(p.validation, validation);
process.stdout.write(`${JSON.stringify({ status: "PASS_ZERO_CALL_FREEZE", session: sessionRef, index: indexRef, validation: validationRef, tasks: 40, intents: 80, targetModelCalls: 0 })}\n`);
