import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { link, lstat, mkdir, mkdtemp, open, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { applyCodeFormationConstraint, CODE_FORMATION_CONSTRAINT_ID, CODE_FORMATION_SYSTEM_SUFFIX } from "../services/code-formation-constraint/src/index";
import { sha256Source, type PatchInterfacePolicy } from "../services/patch-interface-runtime/src/index";

const exec = promisify(execFile), root = path.resolve(process.cwd()), seed = 20260812;
const sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const rel = {
  protocol: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_PROTOCOL.v1.json",
  candidate: "docs/experiments/patch-interface/E_EDIT_CANDIDATE.v1.json",
  model: "benchmarks/model-specialization/MODEL_TOURNAMENT_CANDIDATE_MANIFEST.v1.json",
  paired: "docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_V3_PAIRED_OBSERVABILITY_REPORT.v3.json",
  manifest: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_TASK_MANIFEST.v1.json",
  repositories: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_REPOSITORIES.v1.json",
  oracle: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_ORACLE.v1.sealed.json",
  prereg: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_PREREGISTRATION.v1.json",
  robustness: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_ROBUSTNESS.v1.json",
  session: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_SESSION_A.v1.json",
  validation: "docs/validation/2026-08-12-code-formation-constraint-session-a.md",
  run: "docs/experiments/runs/code-formation-constraint-v1"
} as const;

async function regular(relative: string) { const target = path.join(root, relative), stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Not regular: ${relative}`); return readFile(target); }
async function verified<T = any>(relative: string) { const body = await regular(relative), digest = sha256(body), sidecar = await regular(`${relative}.sha256`); if (sidecar.toString() !== `${digest}  ${path.basename(relative)}\n`) throw new Error(`Artifact drift: ${relative}`); return { value: JSON.parse(body.toString()) as T, sha256: digest }; }
async function publish(relative: string, value: unknown | string) { const body = typeof value === "string" ? value : `${JSON.stringify(value, null, 2)}\n`, digest = sha256(body), target = path.join(root, relative); await mkdir(path.dirname(target), { recursive: true }); try { const stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink() || await readFile(target, "utf8") !== body) throw new Error(`Immutable collision: ${relative}`); return { path: relative, sha256: digest, bytes: Buffer.byteLength(body) }; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } const pending = `${target}.next.${process.pid}.${randomUUID()}`, handle = await open(pending, "wx", 0o600); try { await handle.writeFile(body); await handle.sync(); } finally { await handle.close(); } try { await link(pending, target); } finally { await rm(pending, { force: true }); } await writeFile(`${target}.sha256`, `${digest}  ${path.basename(relative)}\n`, { flag: "wx", mode: 0o600 }); return { path: relative, sha256: digest, bytes: Buffer.byteLength(body) }; }

type Family = { id: string; make(index: number): { name: string; prompt: string; source: string; fixed: string; visible: string; hidden: string } };
const families: Family[] = [
  { id: "bounded-number", make: (i) => { const name = `boundValue${i}`; return { name, prompt: `Fix ${name} so it clamps finite values inclusively between min and max, returning min for non-finite input.`, source: `export function ${name}(value, min, max) {\n  return Math.min(max, value);\n}\nexport const fixtureTag = ${i};\n`, fixed: `export function ${name}(value, min, max) {\n  return Number.isFinite(value) ? Math.min(max, Math.max(min, value)) : min;\n}\nexport const fixtureTag = ${i};\n`, visible: `assert.equal(${name}(-3, 0, 8), 0);`, hidden: `assert.equal(${name}(99, 0, 8), 8); assert.equal(${name}(NaN, 2, 8), 2);` }; } },
  { id: "label-normalization", make: (i) => { const name = `normalizeLabel${i}`; return { name, prompt: `Fix ${name} to trim, lowercase, collapse non-alphanumeric runs to one dash, and remove edge dashes.`, source: `export function ${name}(value) {\n  return String(value).replace(/\\s+/g, '-');\n}\nexport const fixtureTag = ${i};\n`, fixed: `export function ${name}(value) {\n  return String(value).trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');\n}\nexport const fixtureTag = ${i};\n`, visible: `assert.equal(${name}(' Hello World '), 'hello-world');`, hidden: `assert.equal(${name}('A__B!!!'), 'a-b'); assert.equal(${name}('---'), '');` }; } },
  { id: "window-selection", make: (i) => { const name = `selectWindow${i}`; return { name, prompt: `Fix ${name} to return items from inclusive start through exclusive end without mutating input; invalid bounds yield an empty array.`, source: `export function ${name}(items, start, end) {\n  return items.slice(start, end + 1);\n}\nexport const fixtureTag = ${i};\n`, fixed: `export function ${name}(items, start, end) {\n  return Number.isInteger(start) && Number.isInteger(end) && start >= 0 && end >= start ? items.slice(start, end) : [];\n}\nexport const fixtureTag = ${i};\n`, visible: `assert.deepEqual(${name}([1,2,3,4], 1, 3), [2,3]);`, hidden: `assert.deepEqual(${name}([1,2], -1, 2), []); assert.deepEqual(${name}([1,2], 2, 1), []);` }; } },
  { id: "token-rendering", make: (i) => {
    const name = `renderToken${i}`;
    const source = [`export function ${name}(key, value) {`, "  return key + '=' + value;", "}", `export const fixtureTag = ${i};`, ""].join("\n");
    const fixed = `export function ${name}(key, value) {\n  const escaped = String(value).replace(/\\\\/g, '\\\\\\\\').replace(/\\n/g, '\\\\n').replace(/"/g, '\\\\"'); return key + '=\"' + escaped + '\"';\n}\nexport const fixtureTag = ${i};\n`;
    return { name, prompt: `Fix ${name} to render key=value, escaping backslash, newline, and double quote in the value.`, source, fixed, visible: `assert.equal(${name}('x', 'a"b'), 'x="a\\\\"b"');`, hidden: `assert.equal(${name}('p', 'a\\\\b\\nc'), 'p="a\\\\\\\\b\\\\nc"');` };
  } },
  { id: "count-parsing", make: (i) => { const name = `parseCount${i}`; return { name, prompt: `Fix ${name} to accept only canonical non-negative decimal integer strings and otherwise return the fallback.`, source: `export function ${name}(value, fallback) {\n  return parseInt(value, 10);\n}\nexport const fixtureTag = ${i};\n`, fixed: `export function ${name}(value, fallback) {\n  return typeof value === 'string' && /^(0|[1-9]\\d*)$/.test(value) ? Number(value) : fallback;\n}\nexport const fixtureTag = ${i};\n`, visible: `assert.equal(${name}('12', 7), 12); assert.equal(${name}('12x', 7), 7);`, hidden: `assert.equal(${name}('-1', 9), 9); assert.equal(${name}('01', 9), 9);` }; } }
];

function testFile(name: string, test: string) { return `import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport { ${name} } from '../src/subject.mjs';\ntest('${name}', () => { ${test} });\n`; }
function shuffled<T>(values: T[]) { let state = seed >>> 0; const copy = [...values]; for (let i = copy.length - 1; i > 0; i--) { state = (1664525 * state + 1013904223) >>> 0; const j = state % (i + 1); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; }

async function validateReference(repo: any, oracle: any) { const temp = await mkdtemp(path.join(os.tmpdir(), "dca-formation-ref-")); try { for (const file of [...repo.files, ...oracle.hidden_files]) { const target = path.join(temp, file.path); await mkdir(path.dirname(target), { recursive: true }); await writeFile(target, file.path === "src/subject.mjs" ? oracle.reference_fixed_source : file.content); } await exec(process.execPath, ["--check", "src/subject.mjs"], { cwd: temp }); await exec(process.execPath, ["--test", "test/visible.test.mjs", "test/hidden.test.mjs"], { cwd: temp }); } finally { await rm(temp, { recursive: true, force: true }); } }

const protocol = await verified<any>(rel.protocol), candidate = await verified<any>(rel.candidate), modelManifest = await verified<any>(rel.model), paired = await verified<any>(rel.paired);
if (protocol.value.state !== "PREPARED_NOT_EXECUTED" || protocol.value.protectedBoundaries.modelCallsNow !== 0 || candidate.value.selectedInterface !== "P2_MINIMAL" || paired.value.observabilityGate?.decision !== "L1_OBSERVABILITY_JUSTIFIED" || paired.value.selectedNextExperiment !== "CODE_FORMATION_CONSTRAINT_EXPERIMENT") throw new Error("Authoritative protocol lineage failed");
const fim = modelManifest.value.candidates.find((row: any) => row.modelId === "TIGER-Lab/FIM-7B"); if (!fim || fim.revision !== "5a1d4294185e4fa0bbd40750c87d0beab7e67a3a") throw new Error("FIM manifest entry missing or drifted");

const tasks: any[] = [], repositories: any[] = [], oracleRows: any[] = [];
for (let variant = 1; variant <= 8; variant++) for (const family of families) {
  const data = family.make(variant), taskId = `cfc-v1-${family.id}-${String(variant).padStart(2, "0")}`, repositoryId = `cfc-v1-repo-${family.id}-${String(variant).padStart(2, "0")}`;
  const files = [{ path: "src/subject.mjs", content: data.source, role: "source" }, { path: "test/visible.test.mjs", content: testFile(data.name, data.visible), role: "test" }], revision = sha256(JSON.stringify(files));
  const task = { task_id: taskId, repository_id: repositoryId, repository_revision: revision, category: family.id, difficulty: "medium", prompt: data.prompt, allowed_file: "src/subject.mjs", allowed_range: { start_line: 1, end_line: 3 }, changed_line_budget: 12, visible_test_path: "test/visible.test.mjs" };
  const truth = { task_id: taskId, original_source_sha256: sha256Source(data.source), reference_fixed_source: data.fixed, hidden_files: [{ path: "test/hidden.test.mjs", content: testFile(data.name, data.hidden), role: "test" }], hidden_test_path: "test/hidden.test.mjs" };
  const repo = { repository_id: repositoryId, immutable_revision: revision, files }; await validateReference(repo, truth); tasks.push(task); repositories.push(repo); oracleRows.push(truth);
}
if (new Set(repositories.map((row) => row.repository_id)).size !== 40 || new Set(repositories.map((row) => row.immutable_revision)).size !== 40) throw new Error("Fresh repositories are not pairwise disjoint");
const ordered = shuffled(tasks), taskIdsSha256 = sha256(ordered.map((row) => row.task_id).join("\n"));
const manifestArtifact = await publish(rel.manifest, { schemaVersion: 1, population: "NEW_TARGET_MODEL_UNSEEN_REPOSITORY_DISJOINT", taskCount: 40, repositoryCount: 40, historicalPopulationsExcluded: ["PRIVACY_SAFE_OBSERVABILITY_V3_80", "MODEL_TOURNAMENT_95"], taskIdsSha256, tasks: ordered });
const repoArtifact = await publish(rel.repositories, { schemaVersion: 1, repositoryCount: 40, repositories });
const oracleArtifact = await publish(rel.oracle, { schemaVersion: 1, sealed: true, taskIdsSha256, rows: ordered.map((task) => oracleRows.find((row) => row.task_id === task.task_id)) });
const schedule = ordered.map((task, index) => ({ pair_index: index + 1, task_id: task.task_id, order: (index % 2 === 0 ? ["CONTROL", "TREATMENT"] : ["TREATMENT", "CONTROL"]) as string[] }));
const preregArtifact = await publish(rel.prereg, { schemaVersion: 1, experimentId: "CODE_FORMATION_CONSTRAINT_EXPERIMENT", state: "FROZEN_BEFORE_FIRST_TARGET_MODEL_CALL", seed, design: { paired: true, taskCount: 40, conditions: ["CONTROL", "TREATMENT"], physicalCalls: 80, counterbalanced: true, retry: false }, control: { systemPrompt: candidate.value.modelFacing.systemPrompt, interface: "P2_MINIMAL" }, treatment: { systemPromptConstruction: "CONTROL_SYSTEM_PROMPT + TWO_NEWLINES + CODE_FORMATION_SYSTEM_SUFFIX", suffix: CODE_FORMATION_SYSTEM_SUFFIX, constraintId: CODE_FORMATION_CONSTRAINT_ID, mode: "STATIC_INSTRUCTION_PLUS_REJECTION_ONLY_PRE_EXECUTION_GATE", semanticRewriting: false }, allowedChanges: ["append the frozen static formation instruction", "reject the unchanged candidate before execution when the whole spliced source does not parse or violates a mechanical formation boundary"], forbiddenChanges: ["task semantics", "retrieval", "context evidence", "model identity", "P2 schema", "file or range", "candidate repair or rewriting", "retry", "reviewer", "oracle or test injection"], model: { modelId: "TIGER-Lab/FIM-7B", revision: "5a1d4294185e4fa0bbd40750c87d0beab7e67a3a", precision: "FP8", backend: "vllm", backendVersion: "0.26.0" }, retrieval: "E-MIN-V2", context: "C1_TASK_PLUS_SOURCE", schema: candidate.value.interface.schema, verification: ["syntax/type", "visible test", "hidden test", "wrong file", "rollback", "safety"], metrics: ["strict behavioral success", "syntax/type pass", "visible-test pass", "hidden-test pass", "valid action", "patch construction", "safety violations", "wrong-file attempts", "rollback failures", "failure-stage migration", "latency", "tokens", "throughput", "peak VRAM", "constraint rejection count"], gates: protocol.value.gates, schedule });

const fixtureSource = "export function x(v) {\n  return v;\n}\nexport const marker = 1;\n", fixturePolicy: PatchInterfacePolicy = { allowedFiles: ["src/x.mjs"], allowedRanges: { "src/x.mjs": [{ startLine: 2, endLine: 2 }] }, expectedSourceSha256: { "src/x.mjs": sha256Source(fixtureSource) }, maxChangedFiles: 1, maxChangedLines: 12 };
const raw = (replacement: string, extra = {}) => JSON.stringify({ file: "src/x.mjs", start_line: 2, end_line: 2, replacement, ...extra });
const cases = [
  ["valid", raw("  return v + 1;"), "ACCEPTED"], ["malformed", "{bad", "BASE_P2_REJECTED"], ["indentation", raw("    return ({ value: v\n      ok: true });"), "AFTER_SOURCE_PARSE_ERROR"], ["delimiter", raw("  return (v + 1;"), "AFTER_SOURCE_PARSE_ERROR"], ["incomplete_expression", raw("  return v +;"), "AFTER_SOURCE_PARSE_ERROR"], ["empty", raw(""), "EMPTY_REPLACEMENT"], ["whitespace", raw(" \n\t"), "WHITESPACE_ONLY_REPLACEMENT"], ["parser_edge_regex", raw("  return /[(){}]/u.test(String(v));"), "ACCEPTED"], ["parser_edge_template", raw("  return `${v ?? ''}`;"), "ACCEPTED"], ["wrong_file", raw("  return v;", { file: "src/y.mjs" }), "BASE_P2_REJECTED"]
] as const;
const robustnessRows = cases.map(([id, output, expected]) => { const first = applyCodeFormationConstraint({ rawOutput: output, sources: { "src/x.mjs": fixtureSource }, policy: fixturePolicy }), second = applyCodeFormationConstraint({ rawOutput: output, sources: { "src/x.mjs": fixtureSource }, policy: fixturePolicy }); if (first.code !== expected || JSON.stringify(first) !== JSON.stringify(second) || !first.replacementUnchanged) throw new Error(`Robustness case failed: ${id}`); return { id, expected, observed: first.code, deterministic: true, crashed: false, replacementRewritten: false }; });
const robustnessArtifact = await publish(rel.robustness, { schemaVersion: 1, status: "PASS", cases: robustnessRows, crashes: 0, nondeterminism: 0, semanticRewrites: 0, privacyLeaks: 0, unsafeFileExpansions: 0 });

await mkdir(path.join(root, rel.run), { recursive: true });
for (const name of ["call-events.jsonl", "paired-observations.jsonl"]) { const target = path.join(root, rel.run, name); try { await writeFile(target, "", { flag: "wx", mode: 0o600 }); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST" || (await readFile(target)).length !== 0) throw error; } }
const sourcePaths = ["scripts/run_code_formation_constraint_experiment.ts", "services/code-formation-constraint/src/index.ts", "services/patch-interface-runtime/src/index.ts", "services/tool-runtime/src/index.ts", "services/model-specialization-runtime/src/index.ts"];
const sourceClosure = { entries: await Promise.all(sourcePaths.map(async (entry) => ({ path: entry, sha256: sha256(await regular(entry)) }))) };
const runtime = { targetModelCalls: 0, vllmProcesses: 0, port8000Listeners: 0, gpuAllocatedBytes: 0, checkedAt: new Date().toISOString() };
try { const { stdout } = await exec("bash", ["-lc", "pgrep -af 'vllm|api_server' || true"]); runtime.vllmProcesses = stdout.trim() ? stdout.trim().split("\n").filter((line) => !line.includes("pgrep -af")).length : 0; } catch {}
try { const { stdout } = await exec("ss", ["-ltn", "sport = :8000"]); runtime.port8000Listeners = stdout.split("\n").filter((line) => line.includes(":8000")).length; } catch {}
try { const { stdout } = await exec("nvidia-smi", ["--query-compute-apps=used_memory", "--format=csv,noheader,nounits"]); runtime.gpuAllocatedBytes = stdout.trim() ? stdout.trim().split("\n").reduce((sum, value) => sum + Number(value) * 1024 * 1024, 0) : 0; } catch {}
if (runtime.vllmProcesses || runtime.port8000Listeners || runtime.gpuAllocatedBytes) throw new Error("Zero-runtime gate failed");
const sessionArtifact = await publish(rel.session, { schemaVersion: 1, session: "A", status: "PASS", completedAt: new Date().toISOString(), protocol: { path: rel.protocol, sha256: protocol.sha256 }, upstream: { p2: { path: rel.candidate, sha256: candidate.sha256 }, fim: { path: rel.model, sha256: modelManifest.sha256 }, observability: { path: rel.paired, sha256: paired.sha256 } }, intervention: { constraintId: CODE_FORMATION_CONSTRAINT_ID, frozen: true, semanticInformationAdded: false, candidateRewriting: false }, population: { taskCount: 40, repositoryCount: 40, targetModelUnseen: true, repositoryDisjoint: true, referenceSyntaxVisibleHidden: "PASS", manifest: manifestArtifact, repositoryArtifact: repoArtifact, oracle: oracleArtifact }, pairing: { physicalCallsPlanned: 80, seed, counterbalanced: true, preregistration: preregArtifact }, gates: protocol.value.gates, runner: { path: "scripts/run_code_formation_constraint_experiment.ts", sha256: sourceClosure.entries[0].sha256, validateOnly: "PASS", executeNow: false }, robustness: robustnessArtifact, privacy: { status: "PASS", rawOutputs: 0, rawEditBodies: 0, L2: false }, safety: { status: "PASS", wrongFileExpansion: 0, semanticRewrite: 0 }, ledgers: { callEventsBytes: 0, pairedObservationsBytes: 0 }, runtime, sourceClosure, nextAuthorizedSession: "B", sessionBStarted: false });
const validationBody = `# Code Formation Constraint Experiment — Session A Validation\n\nStatus: PASS\n\n- Session: A (zero-call freeze)\n- Fresh tasks / repositories: 40 / 40\n- Planned paired calls: 80 (not executed)\n- Reference syntax/visible/hidden checks: PASS\n- Constraint robustness, privacy, and safety: PASS\n- Future ledgers: empty\n- Target-model calls: 0\n- vLLM processes / port 8000 listeners / GPU allocation: 0 / 0 / 0\n- Session artifact: \`${sessionArtifact.sha256}\`\n- Manifest: \`${manifestArtifact.sha256}\`\n- Preregistration: \`${preregArtifact.sha256}\`\n\nSession B was not started.\n`;
await publish(rel.validation, validationBody);
process.stdout.write(`${JSON.stringify({ status: "PASS", session: "A", tasks: 40, targetModelCalls: 0, sessionSha256: sessionArtifact.sha256 })}\n`);
