import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { link, lstat, mkdir, open, readFile, readdir, rm } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

const exec=promisify(execFile),root=path.resolve(process.cwd()),run="docs/experiments/runs/privacy-safe-observability-v1",sha256=(v:string|Buffer)=>createHash("sha256").update(v).digest("hex");
async function regular(rel:string){const t=path.join(root,rel),s=await lstat(t);if(!s.isFile()||s.isSymbolicLink())throw new Error(`Not regular ${rel}`);return readFile(t);} async function publishBytes(rel:string,body:string){const t=path.join(root,rel);await mkdir(path.dirname(t),{recursive:true});try{const s=await lstat(t);if(!s.isFile()||s.isSymbolicLink()||await readFile(t,"utf8")!==body)throw new Error(`Collision ${rel}`);return;}catch(e){if((e as NodeJS.ErrnoException).code!=="ENOENT")throw e;}const p=`${t}.next.${process.pid}.${randomUUID()}`,h=await open(p,"wx",0o600);try{await h.writeFile(body);await h.sync();}finally{await h.close();}try{await link(p,t);}finally{await rm(p,{force:true});}} async function publish(rel:string,v:unknown){const body=`${JSON.stringify(v,null,2)}\n`,h=sha256(body);await publishBytes(rel,body);await publishBytes(`${rel}.sha256`,`${h}  ${path.basename(rel)}\n`);return{path:rel,sha256:h};}
const sealPath="benchmarks/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_SESSION_B_SEAL.v1.json",dryPath="benchmarks/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_SESSION_B_DRY_RUN.v1.json",eventsPath=`${run}/call-events.jsonl`,checkpointPath=`${run}/observations.checkpoint.jsonl`,seal=await regular(sealPath),dry=await regular(dryPath),events=await regular(eventsPath),checkpoint=await regular(checkpointPath),eventRows=events.toString().split("\n").filter(Boolean).map((line)=>JSON.parse(line)),rows=checkpoint.toString().split("\n").filter(Boolean).map((line)=>JSON.parse(line));
if(eventRows.length!==7||rows.length!==3||eventRows.filter(x=>x.event==="CALL_STARTED").length!==4||eventRows.filter(x=>x.event==="CALL_COMPLETED").length!==3||eventRows.at(-1)?.index!==3||eventRows.at(-1)?.event!=="CALL_STARTED")throw new Error("Unexpected partial ledger");
const l0=(await readdir(path.join(root,run,"l0"))).filter(x=>x.endsWith(".json")),l1=(await readdir(path.join(root,run,"restricted-l1"))).filter(x=>x.endsWith(".json"));if(l0.length!==3||l1.length!==3)throw new Error("Unexpected packet counts");for(const rel of[eventsPath,checkpointPath]){const b=await regular(rel),h=sha256(b);await publishBytes(`${rel}.sha256`,`${h}  ${path.basename(rel)}\n`);}for(const row of rows){for(const ref of[row.L0,row.L1]){const b=await regular(ref.path);if(sha256(b)!==ref.sha256)throw new Error("Packet drift");}}
const runtime=path.join(root,".runtime/model"),stateEvidence:any={};for(const name of["tournament-start.json","tournament-launch.json","tournament-ready.json"]){try{const b=await readFile(path.join(runtime,name));stateEvidence[name]={sha256:sha256(b),bytes:b.length};await rm(path.join(runtime,name));}catch(e){if((e as NodeJS.ErrnoException).code!=="ENOENT")throw e;}}for(const name of["tournament-api-key","observability-hmac-key"])await rm(path.join(runtime,name),{force:true});
const{stdout:ps}=await exec("ps",["-eo","args="]),{stdout:ss}=await exec("ss",["-ltn"]),{stdout:gpu}=await exec("nvidia-smi",["--query-compute-apps=pid,process_name,used_memory","--format=csv,noheader,nounits"]);const models=ps.split("\n").filter(x=>/vllm\.entrypoints|launch_model_tournament_candidate/.test(x)&&!x.includes("record_privacy_observability")),portClear=!ss.split("\n").some(x=>/(?:^|:)8000\s/.test(x));if(models.length||!portClear||gpu.trim())throw new Error("Cleanup incomplete");
const artifact={schemaVersion:1,abortId:"dca-privacy-safe-semantic-observability-session-b-partial-abort-v1",status:"ABORTED_FAIL_CLOSED_AFTER_CONSUMED_CALL",classification:"INFRASTRUCTURE_EXTRACTOR_REJECTED_MODEL_EDIT_NO_RETRY",recordedAt:new Date().toISOString(),inputs:{seal:{path:sealPath,sha256:sha256(seal)},dryRun:{path:dryPath,sha256:sha256(dry)}},reason:{code:"L1_AFTER_SOURCE_PARSE_FAILED",messageSha256:sha256("Source parse failed"),behaviorChangingSourceEditAfterCallAllowed:false,hotPatchPerformed:false},accounting:{plannedPhysicalCalls:80,consumedPhysicalCalls:4,completedObservations:3,pairedL0L1:3,unmatchedStartedCalls:1,unstartedTasks:76,retries:0,reviewerCalls:0,sessionBComplete:false,sessionBPass:false},lineage:{callEvents:{path:eventsPath,sha256:sha256(events),rows:7,started:4,completed:3},checkpoint:{path:checkpointPath,sha256:sha256(checkpoint),rows:3},lastEvent:{index:3,taskIdSha256:sha256(eventRows.at(-1).taskId),event:"CALL_STARTED"},L0Packets:3,L1Packets:3,packetPairsValidated:3},privacy:{rawModelOutputsPersisted:0,rawEditBodiesPersisted:0,HMACKeyMaterialPersisted:false,L2:false,semanticClassificationPerformed:false},cleanup:{modelProcesses:0,port8000Clear:true,modelGpuAllocationMiB:0,ephemeralApiKeyAbsent:true,HMACKeyAbsent:true,servingStateRemoved:true,stateEvidence},decision:{generationPermanentlyClosed:true,resumeSameSeal:false,rerunConsumedCalls:false,nextAction:"NEW_APPEND_ONLY_PROTOCOL_REQUIRED_BEFORE_ANY_FUTURE_EXECUTION"},protectedActions:{modelDownload:false,retry:false,reviewer:false,commit:false,remote:false,push:false,pullRequest:false,tag:false,release:false,signing:false}};
const ref=await publish("docs/experiments/model-specialization/PRIVACY_SAFE_SEMANTIC_OBSERVABILITY_SESSION_B_PARTIAL_ABORT.v1.json",artifact);process.stdout.write(JSON.stringify({status:artifact.status,artifact:ref,accounting:artifact.accounting,cleanup:artifact.cleanup},null,2)+"\n");
