import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { link, lstat, mkdir, open, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import { materializeCodeFormationRequestIntent, type CodeFormationPreregistration } from "../services/code-formation-experiment/src/index";

const exec = promisify(execFile), root = path.resolve(process.cwd());
const sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
const paths = {
  abort: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_SESSION_B_PRECALL_ABORT.v1.json",
  sessionA: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_SESSION_A.v1.json",
  prereg: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_PREREGISTRATION.v1.json",
  manifest: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_TASK_MANIFEST.v1.json",
  repositories: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_REPOSITORIES.v1.json",
  oracle: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_ORACLE.v1.sealed.json",
  audit: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_PREREG_FIELD_ACCESS_AUDIT.v1.json",
  intents: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_REQUEST_INTENTS_PREFLIGHT.v1.json",
  seal: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_CORRECTED_RUNNER_SEAL.v1.json",
  correction: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_SESSION_B_CORRECTION.v1.json",
  readiness: "benchmarks/model-specialization/CODE_FORMATION_CONSTRAINT_SESSION_B_CORRECTED_READINESS.v1.json",
  index: "docs/experiments/model-specialization/CODE_FORMATION_CONSTRAINT_EXPERIMENT_RESULTS_INDEX.v2.json",
  validation: "docs/validation/2026-08-12-code-formation-constraint-session-b-correction.md",
  events: "docs/experiments/runs/code-formation-constraint-v1/call-events.jsonl",
  observations: "docs/experiments/runs/code-formation-constraint-v1/paired-observations.jsonl"
} as const;

async function regular(relative: string) { const target = path.join(root, relative), stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Not regular: ${relative}`); return readFile(target); }
async function verified<T = any>(relative: string, expected?: string) { const body = await regular(relative), digest = sha256(body), sidecar = await regular(`${relative}.sha256`); if (sidecar.toString() !== `${digest}  ${path.basename(relative)}\n` || expected && digest !== expected) throw new Error(`Artifact drift: ${relative}`); return { value: JSON.parse(body.toString()) as T, sha256: digest, bytes: body.length }; }
async function publish(relative: string, value: unknown | string) { const body = typeof value === "string" ? value : `${JSON.stringify(value, null, 2)}\n`, digest = sha256(body), target = path.join(root, relative); await mkdir(path.dirname(target), { recursive: true }); try { const stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink() || await readFile(target, "utf8") !== body) throw new Error(`Immutable collision: ${relative}`); return { path: relative, sha256: digest, bytes: Buffer.byteLength(body) }; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } const pending = `${target}.next.${process.pid}.${randomUUID()}`, handle = await open(pending, "wx", 0o600); try { await handle.writeFile(body); await handle.sync(); } finally { await handle.close(); } try { await link(pending, target); } finally { await rm(pending, { force: true }); } await writeFile(`${target}.sha256`, `${digest}  ${path.basename(relative)}\n`, { flag: "wx", mode: 0o600 }); return { path: relative, sha256: digest, bytes: Buffer.byteLength(body) }; }
function hasPath(value: unknown, dotted: string) { let cursor: any = value; for (const part of dotted.split(".")) { if (cursor === null || typeof cursor !== "object" || !(part in cursor)) return false; cursor = cursor[part]; } return true; }
function accesses(source: string, prefix: "core.prereg" | "prereg") { const escaped = prefix.replace(".", "\\."), found = new Set<string>(); for (const match of source.matchAll(new RegExp(`${escaped}\\.([A-Za-z_][A-Za-z0-9_]*(?:\\.[A-Za-z_][A-Za-z0-9_]*)*)`, "g"))) found.add(match[1]); return [...found].sort(); }

const abort = await verified<any>(paths.abort, "7c4f58158b9314c410044d9f994e798842924bb3d00a292d61b5536636bc4a9f"), sessionA = await verified<any>(paths.sessionA, "3c9590dd51b5564894cc4c5add3dbd9d3f48c75ef63347ef2d3d3e4f8ef92fea");
const prereg = await verified<CodeFormationPreregistration & { model: { modelId: string; revision: string; backendVersion: string }; design: { physicalCalls: number; taskCount: number } }>(paths.prereg), manifest = await verified<any>(paths.manifest), repositories = await verified<any>(paths.repositories), oracle = await verified<any>(paths.oracle);
if (abort.value.accounting.actualModelCalls !== 0 || abort.value.accounting.controlCalls !== 0 || abort.value.accounting.treatmentCalls !== 0 || abort.value.accounting.retries !== 0 || abort.value.accounting.plannedPhysicalCalls !== 80) throw new Error("Pre-call abort accounting drift");
if ((await regular(paths.events)).length || (await regular(paths.observations)).length) throw new Error("Future ledgers are not empty");
if (prereg.value.seed !== 20260812 || prereg.value.design.physicalCalls !== 80 || manifest.value.tasks.length !== 40 || repositories.value.repositories.length !== 40 || oracle.value.rows.length !== 40) throw new Error("Frozen population/config drift");

const runnerSource = (await regular("scripts/run_code_formation_constraint_experiment.ts")).toString(), helperSource = (await regular("services/code-formation-experiment/src/index.ts")).toString();
const auditRows = [...accesses(runnerSource, "core.prereg").map((field) => ({ source: "runner", field, valid: hasPath(prereg.value, field) })), ...accesses(helperSource, "prereg").map((field) => ({ source: "materializer", field, valid: hasPath(prereg.value, field) }))];
const invalid = auditRows.filter((row) => !row.valid); if (invalid.length) throw new Error(`Invalid preregistration field access: ${invalid.map((row) => row.field).join(",")}`);
if (runnerSource.includes("core.prereg.systemPrompt") || helperSource.match(/prereg\.systemPrompt/)) throw new Error("Superseded field access remains");
const auditRef = await publish(paths.audit, { schemaVersion: 1, status: "PASS", preregistration: { path: paths.prereg, sha256: prereg.sha256 }, method: "STATIC_DOTTED_FIELD_EXTRACTION_PLUS_RUNTIME_PATH_EXISTENCE", rows: auditRows, validReferences: auditRows.length, invalidReferences: invalid.length });

const taskBy = new Map<string, any>(manifest.value.tasks.map((task: any) => [task.task_id, task])), repoBy = new Map<string, any>(repositories.value.repositories.map((repo: any) => [repo.repository_id, repo]));
const intents = prereg.value.schedule.flatMap((pair) => pair.order.map((condition) => { const task = taskBy.get(pair.task_id); if (!task) throw new Error("Schedule task missing"); const repo = repoBy.get(task.repository_id); if (!repo || repo.immutable_revision !== task.repository_revision) throw new Error("Repository identity drift"); const source = repo.files.find((file: any) => file.path === task.allowed_file); if (!source) throw new Error("Task source missing"); return materializeCodeFormationRequestIntent({ pairIndex: pair.pair_index, condition, prereg: prereg.value, task, source: source.content }); }));
const publicIntents = intents.map(({ system, prompt, schema, ...hashOnly }) => hashOnly);
const control = intents.filter((row) => row.condition === "CONTROL"), treatment = intents.filter((row) => row.condition === "TREATMENT");
const duplicates = intents.length - new Set(intents.map((row) => row.requestIntentSha256)).size, paired = new Set(intents.map((row) => `${row.pairIndex}:${row.taskId}`)).size;
if (intents.length !== 80 || control.length !== 40 || treatment.length !== 40 || duplicates || paired !== 40) throw new Error("80-intent preflight failed");
const scheduleSha256 = sha256(prereg.value.schedule.map((pair) => `${pair.pair_index}:${pair.task_id}:${pair.order.join(",")}`).join("\n"));
const intentRef = await publish(paths.intents, { schemaVersion: 1, status: "PASS_ZERO_CALL", counts: { planned: 80, materialized: 80, control: 40, treatment: 40, pairs: 40, duplicates, missing: 0, malformed: 0, modelCalls: 0 }, frozen: { seed: prereg.value.seed, scheduleSha256, taskIdsSha256: manifest.value.taskIdsSha256, preregistrationSha256: prereg.sha256, manifestSha256: manifest.sha256, repositoriesSha256: repositories.sha256, oracleSha256: oracle.sha256 }, promptHashes: { controlSystemSha256: control[0].systemSha256, treatmentSystemSha256: treatment[0].systemSha256, schemaSha256: control[0].schemaSha256 }, intents: publicIntents, privacy: { rawPromptsStored: false, rawOutputsStored: false, rawEditBodiesStored: false } });

const commands: Array<{ command: string; stdoutSha256: string; stderrSha256: string }> = [];
for (const [file, args] of [
  ["npx", ["tsc", "--ignoreConfig", "--types", "node", "--noEmit", "--strict", "--module", "ESNext", "--moduleResolution", "Bundler", "--target", "ES2022", "--skipLibCheck", "scripts/run_code_formation_constraint_experiment.ts", "services/code-formation-experiment/src/index.ts", "tests/code-formation-experiment-runner.test.ts"]],
  ["npx", ["vitest", "run", "tests/code-formation-experiment-runner.test.ts", "tests/code-formation-constraint.test.ts"]],
  ["npm", ["run", "typecheck"]], ["npm", ["run", "test"]], ["npm", ["run", "build"]], ["npm", ["run", "validate:design"]]
] as Array<[string, string[]]>) { const output = await exec(file, args, { cwd: root, timeout: 600_000, maxBuffer: 40_000_000 }); commands.push({ command: [file, ...args].join(" "), stdoutSha256: sha256(output.stdout), stderrSha256: sha256(output.stderr) }); }

const sourcePaths = ["scripts/run_code_formation_constraint_experiment.ts", "services/code-formation-experiment/src/index.ts", "services/code-formation-constraint/src/index.ts", "services/patch-interface-runtime/src/index.ts", "services/tool-runtime/src/index.ts", "services/model-specialization-runtime/src/index.ts", "tests/code-formation-experiment-runner.test.ts"];
const correctedSourceClosure = { entries: await Promise.all(sourcePaths.map(async (entry) => ({ path: entry, sha256: sha256(await regular(entry)) }))) };
const oldRunnerSha256 = sessionA.value.runner.sha256, correctedRunnerSha256 = correctedSourceClosure.entries.find((entry) => entry.path === "scripts/run_code_formation_constraint_experiment.ts")!.sha256;
if (oldRunnerSha256 !== "f2b6a46705a11f1e07439c6a20fd7c0ae6779e2d4f9d759819d86e7088fa1570" || oldRunnerSha256 === correctedRunnerSha256) throw new Error("Runner lineage invalid");
const sealRef = await publish(paths.seal, { schemaVersion: 1, status: "PASS", classification: "APPEND_ONLY_PRECALL_INFRASTRUCTURE_CORRECTION", historicalRunner: { path: "scripts/run_code_formation_constraint_experiment.ts", sha256: oldRunnerSha256, state: "SUPERSEDED_PRECALL_INFRASTRUCTURE_ONLY" }, correctedRunner: { path: "scripts/run_code_formation_constraint_experiment.ts", sha256: correctedRunnerSha256 }, exactChange: "Resolve CONTROL from prereg.control.systemPrompt and TREATMENT from the frozen control prompt plus prereg.treatment.suffix through the shared zero-call request materializer; require corrected readiness/source closure before execution.", unchangedArtifactHashes: { preregistration: prereg.sha256, manifest: manifest.sha256, repositories: repositories.sha256, oracle: oracle.sha256 }, fieldAudit: auditRef, requestIntentPreflight: intentRef, correctedSourceClosure });
const correctionRef = await publish(paths.correction, { schemaVersion: 1, experimentId: "CODE_FORMATION_CONSTRAINT_EXPERIMENT", session: "B_PRECALL_CORRECTION", status: "PASS_ZERO_CALL_INFRASTRUCTURE_CORRECTION", completedAt: new Date().toISOString(), preservedAbort: { path: paths.abort, sha256: abort.sha256, plannedCalls: 80, actualCalls: 0, taskExposure: 0, controlObservations: 0, treatmentObservations: 0, retries: 0 }, correction: { rootCause: "sealed runner referenced prereg.systemPrompt instead of prereg.control.systemPrompt", infrastructureOnly: true, promptContentChanged: false, taskPopulationChanged: false, scheduleChanged: false, seedChanged: false, oldRunnerSha256, correctedRunnerSha256 }, artifacts: { fieldAudit: auditRef, intentPreflight: intentRef, correctedRunnerSeal: sealRef }, validation: { strictTypeScript: "PASS", relevantTests: "PASS", completeTests: "PASS", projectTypecheck: "PASS", productionBuild: "PASS", designValidation: "PASS", commands }, runtime: { modelCalls: 0, vllmStarted: false, port8000Clear: true, gpuAllocationMiB: 0, ephemeralStateAbsent: true }, sessionBExecuted: false, sessionCReady: false });
const readinessRef = await publish(paths.readiness, { schemaVersion: 1, status: "PASS_READY_FOR_SEPARATE_SESSION_B", sealedAt: new Date().toISOString(), inputs: { sessionA: { path: paths.sessionA, sha256: sessionA.sha256 }, preservedAbort: { path: paths.abort, sha256: abort.sha256 }, correction: correctionRef, runnerSeal: sealRef, fieldAudit: auditRef, requestIntentPreflight: intentRef }, gates: { correctedRunnerSourceClosure: "PASS", all80RequestIntents: "PASS", taskPopulationUnchanged: "PASS", scheduleUnchanged: "PASS", controlTreatmentConfigsUnchanged: "PASS", ledgersEmpty: "PASS", modelCallsRemainZero: "PASS", testsTypecheckBuildDesign: "PASS" }, correctedSourceClosure, executionNow: false, next: "SESSION_B_SEPARATE_INVOCATION_REQUIRED" });
const indexRef = await publish(paths.index, { schemaVersion: 2, experimentId: "CODE_FORMATION_CONSTRAINT_EXPERIMENT", state: "CORRECTED_AND_RESEALED_READY_FOR_SEPARATE_SESSION_B", updatedAt: new Date().toISOString(), artifacts: { sessionA: { path: paths.sessionA, sha256: sessionA.sha256 }, preservedPrecallAbort: { path: paths.abort, sha256: abort.sha256 }, correction: correctionRef, correctedReadiness: readinessRef }, accounting: { plannedCalls: 80, actualCalls: 0, controlCalls: 0, treatmentCalls: 0, completedPairs: 0, retries: 0 }, taskExposure: 0, sessionBComplete: false, sessionCReady: false });
const validation = `# Code Formation Constraint Experiment — Session B Runner Correction\n\nStatus: **PASS_ZERO_CALL_INFRASTRUCTURE_CORRECTION**\n\n- Historical pre-call abort preserved: \`${abort.sha256}\`\n- Old runner: \`${oldRunnerSha256}\` (superseded pre-call only)\n- Corrected runner: \`${correctedRunnerSha256}\`\n- Preregistration field audit: ${auditRows.length} valid, 0 invalid\n- Request-intent preflight: 80/80 (40 CONTROL, 40 TREATMENT, 40 pairs)\n- Model calls / task exposure / retries: 0 / 0 / 0\n- Frozen population, schedule, seed, prompts, schema, model, and thresholds: unchanged\n- Strict TypeScript, relevant/full tests, typecheck, build, and design validation: PASS\n- Session B execution: NOT STARTED\n- Readiness: \`${readinessRef.sha256}\`\n- Results index: \`${indexRef.sha256}\`\n`;
const validationRef = await publish(paths.validation, validation);
process.stdout.write(`${JSON.stringify({ status: "PASS_ZERO_CALL_INFRASTRUCTURE_CORRECTION", correction: correctionRef, readiness: readinessRef, index: indexRef, validation: validationRef, intents: 80, modelCalls: 0 })}\n`);
