import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { link, lstat, mkdir, open, readFile, readdir, rm } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import { retrieveG3 } from "../services/g3-evaluation-runtime/src/index";
import { auditFailureIndependently, classifyFailure, structuralDimensions, type ClassificationInput } from "../services/semantic-failure-decomposition/src/index";

const exec = promisify(execFile), root = path.resolve(process.cwd()), completedAt = new Date().toISOString();
const sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
async function regular(relative: string) { const target = path.join(root, relative), stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Not regular: ${relative}`); return readFile(target); }
async function verified(relative: string, expected?: string) { const bytes = await regular(relative), digest = sha256(bytes), sidecar = await regular(`${relative}.sha256`); if (sidecar.toString("utf8") !== `${digest}  ${path.basename(relative)}\n` || (expected && digest !== expected)) throw new Error(`Artifact mismatch: ${relative}`); return { path: relative, sha256: digest, value: JSON.parse(bytes.toString("utf8")) as any }; }
async function jsonl(relative: string) { const bytes = await regular(relative), digest = sha256(bytes), sidecar = await regular(`${relative}.sha256`); if (sidecar.toString("utf8") !== `${digest}  ${path.basename(relative)}\n`) throw new Error(`JSONL mismatch: ${relative}`); return { path: relative, sha256: digest, rows: bytes.toString("utf8").split("\n").filter(Boolean).map((line) => JSON.parse(line)) }; }
async function publishBytes(relative: string, body: string) { const target = path.join(root, relative); await mkdir(path.dirname(target), { recursive: true }); try { const stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink() || await readFile(target, "utf8") !== body) throw new Error(`Immutable collision: ${relative}`); return; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } const pending = `${target}.next.${process.pid}.${randomUUID()}`, handle = await open(pending, "wx", 0o600); try { await handle.writeFile(body); await handle.sync(); } finally { await handle.close(); } try { await link(pending, target); } finally { await rm(pending, { force: true }); } }
async function publish(relative: string, value: unknown) { const body = `${JSON.stringify(value, null, 2)}\n`, digest = sha256(body); await publishBytes(relative, body); await publishBytes(`${relative}.sha256`, `${digest}  ${path.basename(relative)}\n`); return { path: relative, sha256: digest }; }
async function command(file: string, args: string[], timeout = 300_000) { const result = await exec(file, args, { cwd: root, timeout, maxBuffer: 30 * 1024 * 1024 }); return { command: [file, ...args].join(" "), exitCode: 0, stdoutSha256: sha256(result.stdout), stderrSha256: sha256(result.stderr) }; }
const counts = (values: string[]) => Object.fromEntries([...new Set(values)].sort().map((value) => [value, values.filter((candidate) => candidate === value).length]));
const cross = (rows: any[], field: (row: any) => string) => ({ total: rows.length, counts: counts(rows.map(field)), ratesPercent: Object.fromEntries(Object.entries(counts(rows.map(field))).map(([key, value]) => [key, 100 * Number(value) / rows.length])) });

const prereg = await verified("benchmarks/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_PREREGISTRATION.v1.json", "6851a9a2a2fd25757413f71c0b331e5899a397c1928b59259f3cc6606123ed47");
const sessionA = await verified("docs/experiments/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_SESSION_A.v1.json", "368ba02473ef7baf09f7c3927b969c579c1848c8c362c2be12f27cacd36535eb");
const sessionAReview = await verified("docs/experiments/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_SESSION_A_REVIEW.v1.json", "fcc3a6b930d909ab88f13e14d8883c7aae61b1efffaf9d4aa361e03056478539");
const manifest = await verified("benchmarks/patch-interface/E_EDIT_HOLDOUT_MANIFEST.v5.json", prereg.value.inputs.holdoutManifest.sha256);
const oracle = await verified("benchmarks/patch-interface/E_EDIT_HOLDOUT_ORACLE.v5.sealed.json", prereg.value.inputs.sealedOracle.sha256);
const repositories = await verified("benchmarks/patch-interface/E_EDIT_HOLDOUT_REPOSITORIES.v1.json", prereg.value.inputs.repositories.sha256);
const original = await jsonl("docs/experiments/runs/model-tournament-session-c-m2-v1/observations.checkpoint.jsonl"), retry = await jsonl("docs/experiments/runs/best-7b-bounded-retry-m2-v1/retry-observations.checkpoint.jsonl");
if (prereg.value.state !== "SEALED_BEFORE_DEEP_TASK_CLASSIFICATION" || sessionA.value.status !== "PASS" || sessionAReview.value.status !== "PASS" || original.sha256 !== prereg.value.inputs.originalObservations.sha256 || retry.sha256 !== prereg.value.inputs.retryObservations.sha256) throw new Error("Session-A or evidence drift");

const taskById = new Map(manifest.value.tasks.map((row: any) => [row.task_id, row])), oracleById = new Map(oracle.value.rows.map((row: any) => [row.task_id, row])), repoById = new Map(repositories.value.repositories.map((row: any) => [row.repository_id, row])), retryById = new Map(retry.rows.map((row: any, index: number) => [row.taskId, { row, index }]));
function materialize(row: any): ClassificationInput & { retrievalRegeneration: any } {
  const task: any = taskById.get(row.taskId), oracleRow: any = oracleById.get(row.taskId), repo: any = repoById.get(row.repositoryId);
  if (!task || !oracleRow || !repo || task.repository_revision !== repo.immutable_revision) throw new Error(`Missing immutable material ${row.taskId}`);
  const runtimeTask: any = { task_id: task.task_id, repository_id: task.repository_id, repository_commit: task.repository_revision, split: "holdout", prompt: task.prompt, declared_symbols: [], provenance: "E_EDIT_DISCLOSED_TOURNAMENT", category: "local_coding", difficulty: task.difficulty, expected_outcome: "PATCH_PROPOSAL", required_evidence_paths: [oracleRow.exact_relevant_file, task.visible_test_path], target_paths: [oracleRow.exact_relevant_file], required_answer_terms: [], security_sensitive: false, hidden_oracle_kind: "PATCH_SCOPE", candidates: repo.files.map((file: any, index: number) => ({ id: `${task.task_id}-${index}`, path: file.path, content: file.content, evidenceClass: file.role === "test" ? "TEST" : file.role === "documentation" ? "DOCUMENTATION" : "SYMBOL", role: file.role === "test" ? "test" : "source", symbols: file.path === oracleRow.exact_relevant_file ? [oracleRow.exact_relevant_symbol] : [] })) };
  const retrieved = retrieveG3(runtimeTask, "E-MIN-V2", 2048), selectedHashes = retrieved.selectedPaths.map(sha256), includedHashes = retrieved.includedPaths.map(sha256);
  if (JSON.stringify(selectedHashes) !== JSON.stringify(row.retrieval.selectedPathHashes) || JSON.stringify(includedHashes) !== JSON.stringify(row.retrieval.includedPathHashes) || sha256(retrieved.context) !== row.retrieval.contextSha256) throw new Error(`Retrieval regeneration drift ${row.taskId}`);
  return { task, oracle: oracleRow, observation: row, retryTaxonomy: (retryById.get(row.taskId) as any)?.row.outcome.taxonomy, selectedPaths: retrieved.selectedPaths, includedPaths: retrieved.includedPaths, retrievalRegeneration: { selectedPathHashes: selectedHashes, includedPathHashes: includedHashes, contextSha256: sha256(retrieved.context), exactMatchToPersisted: true } } as any;
}
const materials = original.rows.map(materialize), failures = materials.filter((item) => !item.observation.outcome.behavioralSuccess), controls = materials.filter((item) => item.observation.outcome.behavioralSuccess);
if (failures.length !== 66 || controls.length !== 29 || new Set(materials.map((item) => item.task.task_id)).size !== 95) throw new Error("Population cardinality drift");
const artifactRefs = { preregistration: { path: prereg.path, sha256: prereg.sha256 }, sessionA: { path: sessionA.path, sha256: sessionA.sha256 }, manifest: { path: manifest.path, sha256: manifest.sha256 }, oracle: { path: oracle.path, sha256: oracle.sha256 }, repositories: { path: repositories.path, sha256: repositories.sha256 }, originalObservations: { path: original.path, sha256: original.sha256 }, retryObservations: { path: retry.path, sha256: retry.sha256 } };
const classifications = failures.map((input, index) => {
  const derived = classifyFailure(input), retryEntry: any = retryById.get(input.task.task_id), observationIndex = original.rows.findIndex((row: any) => row.taskId === input.task.task_id);
  return { schemaVersion: 1, taskId: input.task.task_id, repositoryId: input.task.repository_id, repositoryRevision: input.task.repository_revision, primaryCategory: derived.primaryCategory, secondaryCategories: derived.secondaryCategories, evidenceSufficiency: derived.evidenceSufficiency, patchScope: derived.patchScope, reasoningHorizon: derived.reasoningHorizon, failureObservability: derived.failureObservability, firstFailureStage: input.observation.outcome.firstFailureStage, retryBehavior: input.retryTaxonomy, taskCategory: input.task.category, difficulty: input.task.difficulty, fileScopeMetadata: input.task.file_scope, confidence: derived.confidence, justification: derived.justification, limitationReasons: derived.limitationReasons, evidenceReferences: [ { artifact: artifactRefs.manifest, selector: `tasks[task_id=${input.task.task_id}]`, fields: ["prompt", "category", "difficulty", "file_scope", "allowed_files", "visible_test_path", "repository_revision"] }, { artifact: artifactRefs.repositories, selector: `repositories[repository_id=${input.task.repository_id}]`, fields: ["immutable_revision", "file paths and hashes used for retrieval regeneration"] }, { artifact: artifactRefs.oracle, selector: `rows[task_id=${input.task.task_id}]`, fields: ["exact_relevant_file", "exact_relevant_symbol", "exact_relevant_range_1_based", "original_source_sha256", "reference_fixed_source_sha256"] }, { artifact: artifactRefs.originalObservations, selector: `jsonl[${observationIndex}]`, rowSha256: sha256(JSON.stringify(input.observation)), fields: ["retrieval", "normalization", "execution", "outcome"] }, { artifact: artifactRefs.retryObservations, selector: `jsonl[${retryEntry.index}]`, rowSha256: sha256(JSON.stringify(retryEntry.row)), fields: ["outcome.taxonomy", "outcome.transition"] } ], retrievalRegeneration: (input as any).retrievalRegeneration, rawModelOutputUsed: false, rawActionUsed: false, privateReasoningStored: false, classificationIndex: index };
});
const controlRows = controls.map((input, index) => { const dimensions = structuralDimensions(input), observationIndex = original.rows.findIndex((row: any) => row.taskId === input.task.task_id); return { schemaVersion: 1, taskId: input.task.task_id, repositoryId: input.task.repository_id, repositoryRevision: input.task.repository_revision, taskCategory: input.task.category, difficulty: input.task.difficulty, patchScope: dimensions.patchScope, reasoningHorizon: dimensions.reasoningHorizon, evidenceSufficiency: dimensions.evidenceSufficiency, fileScopeMetadata: input.task.file_scope, repositoryStructure: input.task.file_scope === "MULTI_FILE_EVIDENCE_SINGLE_TARGET" ? "MULTI_FILE_EVIDENCE_SINGLE_TARGET" : "SINGLE_FILE", requirementStructure: "VISIBLE_AND_HIDDEN_VERIFICATION", exactSourceIncluded: dimensions.exactSourceIncluded, visibleTestIncluded: dimensions.visibleTestIncluded, evidenceReferences: [ { artifact: artifactRefs.manifest, selector: `tasks[task_id=${input.task.task_id}]` }, { artifact: artifactRefs.oracle, selector: `rows[task_id=${input.task.task_id}]`, fields: ["exact_relevant_range_1_based", "reference_fixed_source_sha256"] }, { artifact: artifactRefs.originalObservations, selector: `jsonl[${observationIndex}]`, rowSha256: sha256(JSON.stringify(input.observation)) } ], failureCategoryAssigned: false, controlIndex: index }; });
if (classifications.some((row) => !prereg.value.taxonomy.categories.includes(row.primaryCategory) || row.secondaryCategories.length > 2) || new Set(classifications.map((row) => row.taskId)).size !== 66 || new Set(controlRows.map((row) => row.taskId)).size !== 29) throw new Error("Classification schema/cardinality failed");

const base = "docs/experiments/model-specialization/semantic-failure-decomposition-session-b";
const classificationDoc = { schemaVersion: 1, matrixId: "dca-semantic-failure-classification-matrix-v1", status: "PASS", classification: "FIRST_ATTEMPT_PRIMARY_ZERO_MODEL_CALL", generatedAt: completedAt, inputs: artifactRefs, rows: classifications, counts: cross(classifications, (row) => row.primaryCategory), privacy: { rawModelOutputsStored: false, rawActionsStored: false, rawSourcesRepersisted: false, conciseRationalesOnly: true }, targetModelCalls: 0 };
const classificationRef = await publish(`${base}/SEMANTIC_FAILURE_CLASSIFICATION_MATRIX.v1.json`, classificationDoc);
const controlsRef = await publish(`${base}/SEMANTIC_FAILURE_SUCCESS_CONTROLS.v1.json`, { schemaVersion: 1, matrixId: "dca-semantic-failure-success-controls-v1", status: "PASS", generatedAt: completedAt, inputs: artifactRefs, rows: controlRows, counts: { difficulty: cross(controlRows, (row) => row.difficulty), taskCategory: cross(controlRows, (row) => row.taskCategory), patchScope: cross(controlRows, (row) => row.patchScope), reasoningHorizon: cross(controlRows, (row) => row.reasoningHorizon), evidenceSufficiency: cross(controlRows, (row) => row.evidenceSufficiency), repositoryStructure: cross(controlRows, (row) => row.repositoryStructure) }, targetModelCalls: 0 });
const evidenceRef = await publish(`${base}/SEMANTIC_FAILURE_EVIDENCE_SUFFICIENCY.v1.json`, { schemaVersion: 1, matrixId: "dca-semantic-failure-evidence-sufficiency-v1", status: "PASS", generatedAt: completedAt, definition: "Model-visible task contract plus regenerated frozen E-MIN-V2/C1 context; exact source absent=MISSING, exact source present but visible test absent=PARTIALLY_SUFFICIENT, both present=SUFFICIENT", failures: cross(classifications, (row) => row.evidenceSufficiency), controls: cross(controlRows, (row) => row.evidenceSufficiency), allTasks: cross([...classifications, ...controlRows], (row) => row.evidenceSufficiency), caveat: "PARTIALLY_SUFFICIENT does not establish that missing visible tests caused failure; all 29 successes had the same partial-evidence label.", targetModelCalls: 0 });
const scopeRef = await publish(`${base}/SEMANTIC_FAILURE_PATCH_SCOPE.v1.json`, { schemaVersion: 1, matrixId: "dca-semantic-failure-patch-scope-v1", status: "PASS", generatedAt: completedAt, objectiveRule: "Allowed target count plus sealed exact relevant range/reference-fixed-source scope; never inferred from unpersisted model edit", failures: cross(classifications, (row) => row.patchScope), controls: cross(controlRows, (row) => row.patchScope), observedMutationScopeComparison: "NOT_AVAILABLE_RAW_ACTION_NOT_PERSISTED", p2RepresentationLimitationClaimAllowed: false, targetModelCalls: 0 });
const horizonRef = await publish(`${base}/SEMANTIC_FAILURE_REASONING_HORIZON.v1.json`, { schemaVersion: 1, matrixId: "dca-semantic-failure-reasoning-horizon-v1", status: "PASS", generatedAt: completedAt, deterministicMapping: { CROSS_FILE: "file_scope=MULTI_FILE_EVIDENCE_SINGLE_TARGET", STATEFUL_OR_API_LEVEL: ["api_misuse", "runtime_configuration", "exception_handling", "natural_failure_recovery"], LOCAL: "remaining SINGLE_FILE categories", INTRA_FILE: "none in frozen metadata mapping" }, failures: cross(classifications, (row) => row.reasoningHorizon), controls: cross(controlRows, (row) => row.reasoningHorizon), targetModelCalls: 0 });
const dimensions = ["difficulty", "taskCategory", "fileScopeMetadata", "patchScope", "reasoningHorizon", "evidenceSufficiency"] as const;
const comparisonRef = await publish(`${base}/SEMANTIC_FAILURE_SUCCESS_FAILURE_COMPARISON.v1.json`, { schemaVersion: 1, matrixId: "dca-semantic-failure-success-vs-failure-v1", status: "PASS_DESCRIPTIVE_NO_CAUSAL_CLAIM", generatedAt: completedAt, populations: { success: 29, failure: 66 }, dimensions: Object.fromEntries(dimensions.map((field) => [field, { success: cross(controlRows, (row) => row[field]), failure: cross(classifications, (row) => row[field]) }])), retrieval: { success: cross(controlRows, (row) => row.exactSourceIncluded ? "EXACT_SOURCE_INCLUDED" : "RETRIEVAL_FAILURE"), failure: cross(classifications, (row) => row.evidenceSufficiency === "MISSING_REQUIRED_EVIDENCE" ? "RETRIEVAL_FAILURE" : "EXACT_SOURCE_INCLUDED") }, requirementStructure: { success: { VISIBLE_AND_HIDDEN_VERIFICATION: 29 }, failure: { VISIBLE_AND_HIDDEN_VERIFICATION: 66 } }, causalInferenceAllowed: false, targetModelCalls: 0 });
const retryCategories = ["RECOVERED", "REPEATED_EDIT", "FAILED_DIFFERENT", "CONTRADICTION", "MALFORMED", "SAFETY_REJECTED"];
const retryByCategory = Object.fromEntries([...new Set(classifications.map((row) => row.primaryCategory))].sort().map((category) => { const rows = classifications.filter((row) => row.primaryCategory === category); return [category, { eligible: rows.length, ...Object.fromEntries(retryCategories.map((outcome) => [outcome, rows.filter((row) => row.retryBehavior === outcome).length])) }]; }));
const retryRef = await publish(`${base}/SEMANTIC_FAILURE_RETRY_BY_CATEGORY.v1.json`, { schemaVersion: 1, matrixId: "dca-semantic-failure-retry-by-category-v1", status: "PASS_SECONDARY_ANALYSIS", generatedAt: completedAt, rows: retryByCategory, historicalRetryDecision: "RETRY_NO_MATERIAL_GAIN", decisionChanged: false, targetModelCalls: 0 });
const t14 = classifications.filter((row) => row.primaryCategory === "T14_AMBIGUOUS_OR_INCONCLUSIVE"), t14Reasons = ["RAW_EDIT_CONTENT_NOT_PERSISTED", "REQUIRED_STRUCTURED_MUTATION_METADATA_ABSENT", "FAILURE_STAGE_NON_IDENTIFYING", "MULTIPLE_SEMANTIC_CAUSES_EQUIVALENTLY_PLAUSIBLE", "OTHER_INSUFFICIENT_OBSERVABLE_EVIDENCE"];
const t14Ref = await publish(`${base}/SEMANTIC_FAILURE_T14_OBSERVABILITY.v1.json`, { schemaVersion: 1, reportId: "dca-semantic-failure-t14-observability-v1", status: "PASS_LIMITATION_QUANTIFIED", generatedAt: completedAt, totalFailures: 66, t14: t14.length, t14Percent: 100 * t14.length / 66, reasonCounts: Object.fromEntries(t14Reasons.map((reason) => [reason, t14.filter((row) => row.limitationReasons.includes(reason)).length])), rows: t14.map((row) => ({ taskId: row.taskId, reasons: row.limitationReasons, confidence: row.confidence, firstFailureStage: row.firstFailureStage })), conclusion: "Historical privacy-preserving hashes prove edit identity but cannot support edit-content semantic diagnosis.", targetModelCalls: 0 });
const confidenceRef = await publish(`${base}/SEMANTIC_FAILURE_CONFIDENCE.v1.json`, { schemaVersion: 1, reportId: "dca-semantic-failure-confidence-v1", status: "PASS", generatedAt: completedAt, distribution: cross(classifications, (row) => row.confidence), t14: t14.length, specificPrimaryCoverage: { count: classifications.length - t14.length, denominator: 66, percent: 100 * (classifications.length - t14.length) / 66, definition: "Non-T14 primary classification supported by direct immutable stage/retrieval evidence" }, semanticProgramCauseCoverage: { count: classifications.filter((row) => /^T(?:[1-9])_/.test(row.primaryCategory)).length, denominator: 66, percent: 0, definition: "T1-T9 semantic program-cause classification; intentionally zero because edit bodies are unavailable" }, noSuccessThresholdInvented: true, targetModelCalls: 0 });

const mandatory = new Set(classifications.filter((row) => row.confidence === "LOW" || row.primaryCategory === "T14_AMBIGUOUS_OR_INCONCLUSIVE" || ["T10_EVIDENCE_MISSING_OR_INSUFFICIENT", "T11_RETRIEVAL_FAILURE", "T8_CROSS_FILE_DEPENDENCY_MISSED"].includes(row.primaryCategory)).map((row) => row.taskId));
const remaining = classifications.filter((row) => !mandatory.has(row.taskId)).sort((a, b) => a.taskId.localeCompare(b.taskId)), sampled = remaining.filter((_, index) => index % 5 === 0); for (const row of sampled) mandatory.add(row.taskId);
const audited = classifications.filter((row) => mandatory.has(row.taskId)).map((row) => { const input = failures.find((item) => item.task.task_id === row.taskId)!; const audit = auditFailureIndependently(input); const agrees = audit.primaryCategory === row.primaryCategory && audit.confidence === row.confidence; return { taskId: row.taskId, original: { primaryCategory: row.primaryCategory, confidence: row.confidence }, audit, agrees, auditEvidence: row.evidenceReferences, procedure: "INDEPENDENT_CONTROL_FLOW_FROZEN_PRECEDENCE" }; });
const disagreements = audited.filter((row) => !row.agrees).map((row) => ({ taskId: row.taskId, original: row.original, audit: row.audit, disagreementType: "PRIMARY_OR_CONFIDENCE", finalResolved: { primaryCategory: "T14_AMBIGUOUS_OR_INCONCLUSIVE", confidence: "LOW" }, resolutionEvidence: row.auditEvidence }));
const auditRef = await publish(`${base}/SEMANTIC_FAILURE_QUALITY_AUDIT.v1.json`, { schemaVersion: 1, auditId: "dca-semantic-failure-quality-audit-v1", status: disagreements.length ? "PASS_WITH_APPEND_ONLY_RESOLUTIONS" : "PASS_NO_DISAGREEMENTS", generatedAt: completedAt, frozenPlan: prereg.value.qualityAuditPlan, mandatoryCounts: { low: classifications.filter((row) => row.confidence === "LOW").length, t14: t14.length, t10: classifications.filter((row) => row.primaryCategory.startsWith("T10_")).length, t11: classifications.filter((row) => row.primaryCategory.startsWith("T11_")).length, t8: classifications.filter((row) => row.primaryCategory.startsWith("T8_")).length }, deterministicRemainingSampleTaskIds: sampled.map((row) => row.taskId), uniqueAudited: audited.length, rows: audited, independentProcedure: true, targetModelCalls: 0 });
const disagreementRef = await publish(`${base}/SEMANTIC_FAILURE_DISAGREEMENTS.v1.json`, { schemaVersion: 1, reportId: "dca-semantic-failure-disagreements-v1", status: disagreements.length ? "PASS_RESOLVED_APPEND_ONLY" : "PASS_NO_DISAGREEMENTS", generatedAt: completedAt, disagreements, originalClassificationsMutated: false, unresolved: disagreements.filter((row) => !row.finalResolved).length, targetModelCalls: 0 });

const preliminaryArtifacts = { classificationMatrix: classificationRef, successControls: controlsRef, evidenceSufficiency: evidenceRef, patchScope: scopeRef, reasoningHorizon: horizonRef, successFailureComparison: comparisonRef, retryByCategory: retryRef, t14Observability: t14Ref, confidence: confidenceRef, qualityAudit: auditRef, disagreements: disagreementRef };
const indexRef = await publish(`${base}/SEMANTIC_FAILURE_DECOMPOSITION_RESULTS_INDEX.v1.json`, { schemaVersion: 1, indexId: "dca-semantic-failure-decomposition-session-b-results-index-v1", status: "PASS_SESSION_B_CLASSIFICATION_COMPLETE", generatedAt: completedAt, inputs: artifactRefs, artifacts: preliminaryArtifacts, population: { failures: 66, controls: 29, total: 95 }, primaryCategoryCounts: cross(classifications, (row) => row.primaryCategory), confidenceDistribution: cross(classifications, (row) => row.confidence), t14: t14.length, evidenceSufficiency: cross(classifications, (row) => row.evidenceSufficiency), patchScope: cross(classifications, (row) => row.patchScope), reasoningHorizon: cross(classifications, (row) => row.reasoningHorizon), audit: { audited: audited.length, disagreements: disagreements.length }, historicalDecisionsUnchanged: true, gatesG1ToG5Applied: false, SessionCSelectionPerformed: false, targetModelCalls: 0 });

const sourcePaths = ["services/semantic-failure-decomposition/src/index.ts", "scripts/run_semantic_failure_decomposition_session_b.ts", "tests/semantic-failure-decomposition.test.ts", "services/g3-evaluation-runtime/src/index.ts", "package.json", "package-lock.json"];
const sourceEntries = await Promise.all(sourcePaths.map(async (relative) => { const bytes = await regular(relative); return { path: relative, sha256: sha256(bytes), bytes: bytes.byteLength }; }));
const sourceClosure = { entries: sourceEntries, sha256: sha256(sourceEntries.map((entry) => `${entry.path}\0${entry.sha256}\0${entry.bytes}`).join("\n")) };
const commands = [ await command("npx", ["tsc", "--ignoreConfig", "--noEmit", "--strict", "--skipLibCheck", "--target", "ES2022", "--module", "ESNext", "--moduleResolution", "Bundler", "--types", "node", "services/semantic-failure-decomposition/src/index.ts", "scripts/run_semantic_failure_decomposition_session_b.ts", "tests/semantic-failure-decomposition.test.ts"]), await command("npm", ["run", "typecheck"]), await command("npm", ["run", "test"]), await command("npm", ["run", "build"]), await command("npm", ["run", "validate:design"]) ];
const allRefs = [...Object.values(preliminaryArtifacts), indexRef]; for (const ref of allRefs) if ((await verified(ref.path)).sha256 !== ref.sha256) throw new Error(`Published artifact drift ${ref.path}`);
const secretPattern = /(hf_[A-Za-z0-9]{20,}|sk-[A-Za-z0-9]{20,}|Bearer\s+[A-Za-z0-9._-]{20,})/; for (const ref of allRefs) if (secretPattern.test((await regular(ref.path)).toString("utf8"))) throw new Error(`Secret-shaped content ${ref.path}`);
const { stdout: processes } = await exec("ps", ["-eo", "args="], { cwd: root }), { stdout: sockets } = await exec("ss", ["-ltn"], { cwd: root }), { stdout: apps } = await exec("nvidia-smi", ["--query-compute-apps=pid,process_name,used_memory", "--format=csv,noheader,nounits"], { cwd: root }), { stdout: ambientGpu } = await exec("nvidia-smi", ["--query-gpu=memory.used", "--format=csv,noheader,nounits"], { cwd: root }), { stdout: worktrees } = await exec("git", ["worktree", "list", "--porcelain"], { cwd: root });
const modelProcessCount = processes.split("\n").filter((line) => /vllm\.entrypoints|launch_model_tournament_candidate\.py|run_best_7b_bounded_retry_session_b/.test(line) && !line.includes("run_semantic_failure_decomposition_session_b")).length, port8000Clear = !sockets.split("\n").some((line) => /(?:^|:)8000\s/.test(line)), computeProcesses = apps.split("\n").filter(Boolean).length, worktreeCount = worktrees.split("\n").filter((line) => line.startsWith("worktree ")).length;
const stateEntries = await readdir(path.join(root, ".runtime/model")).catch(() => []), ephemeralState = stateEntries.filter((name) => /api-key|start|launch|ready/i.test(name)), tempEntries = (await readdir("/tmp")).filter((name) => name.startsWith("dca-semantic-failure-") || name.startsWith("dca-model-tournament-") || name.startsWith("dca-best-7b-bounded-retry-"));
if (modelProcessCount || computeProcesses || !port8000Clear || ephemeralState.length || tempEntries.length || worktreeCount !== 1) throw new Error("Runtime cleanup failed");
const validationRef = await publish(`${base}/SEMANTIC_FAILURE_DECOMPOSITION_SESSION_B_VALIDATION.v1.json`, { schemaVersion: 1, validationId: "dca-semantic-failure-decomposition-session-b-validation-v1", status: "PASS", validatedAt: completedAt, inputs: { resultsIndex: indexRef }, checks: { schemaValidation: "PASS", failureRecords: "PASS_66", exactlyOnePrimary: "PASS", maximumTwoSecondary: "PASS", successControls: "PASS_29", duplicateTaskIds: "PASS_NONE", allTasksAccounted: "PASS_95", citations: "PASS", strictTypeScript: "PASS", projectTypecheck: "PASS", completeTests: "PASS", productionBuild: "PASS", designValidation: "PASS", secretScan: "PASS", artifactSidecars: "PASS", sourceClosure: "PASS", lineage: "PASS", gatesApplied: false }, commands, sourceClosure, cleanup: { targetModelCalls: 0, modelProcessCount, modelComputeProcesses: computeProcesses, modelGpuAllocationMiB: 0, ambientGpuMemoryMiB: Number(ambientGpu.trim()), port8000Clear, ephemeralStateAbsent: ephemeralState.length === 0, temporaryDirectories: tempEntries.length, worktrees: worktreeCount } });
const sessionRef = await publish("docs/experiments/model-specialization/SEMANTIC_FAILURE_DECOMPOSITION_SESSION_B.v1.json", { schemaVersion: 1, sessionId: "dca-semantic-failure-decomposition-session-b-v1", session: "B", status: "PASS", classification: "ZERO_TARGET_MODEL_CALL_FULL_CLASSIFICATION_AND_EVIDENCE_AUDIT", completedAt, inputs: { preregistration: { path: prereg.path, sha256: prereg.sha256 }, sessionA: { path: sessionA.path, sha256: sessionA.sha256 }, sessionAReview: { path: sessionAReview.path, sha256: sessionAReview.sha256 } }, resultsIndex: indexRef, validation: validationRef, population: { failures: 66, controls: 29, total: 95 }, primaryCategoryCounts: cross(classifications, (row) => row.primaryCategory), confidenceDistribution: cross(classifications, (row) => row.confidence), t14Observability: { count: t14.length, percent: 100 * t14.length / 66, report: t14Ref }, evidenceSufficiency: cross(classifications, (row) => row.evidenceSufficiency), patchScope: cross(classifications, (row) => row.patchScope), reasoningHorizon: cross(classifications, (row) => row.reasoningHorizon), audit: { uniqueAudited: audited.length, disagreements: disagreements.length, report: auditRef, resolutions: disagreementRef }, historicalDecisions: { retry: "RETRY_NO_MATERIAL_GAIN", productMutation: "KEEP_MUTATION_DISABLED", fimStatus: "BEST_RESEARCH_MODEL__STRONGEST_SCORED_RESEARCH_CANDIDATE_ASSISTED_FLOOR_ONLY", eedit: "RESEARCH_ONLY_MUTATION_INTERFACE", changed: false }, SessionC: { gatesApplied: false, nextExperimentSelected: false, readiness: "READY_SEPARATE_INVOCATION_REQUIRED" }, closedHoldout: "ANALYSIS_EXPOSED_NOT_FRESH_PROMOTION_EVIDENCE", sourceClosure, cleanup: { targetModelCalls: 0, modelProcessCount, modelComputeProcesses: computeProcesses, modelGpuAllocationMiB: 0, ambientGpuMemoryMiB: Number(ambientGpu.trim()), port8000Clear, ephemeralStateAbsent: ephemeralState.length === 0, temporaryDirectories: tempEntries.length, worktrees: worktreeCount }, protectedActions: { targetModelCall: false, modelDownload: false, retry: false, newTaskExecution: false, sudo: false, commit: false, remote: false, push: false, pullRequest: false, tag: false, release: false, signing: false }, stop: "SESSION_B_BOUNDARY_REACHED" });
process.stdout.write(`${JSON.stringify({ status: "PASS", sessionB: sessionRef, resultsIndex: indexRef, validation: validationRef, primaryCategoryCounts: cross(classifications, (row) => row.primaryCategory), confidence: cross(classifications, (row) => row.confidence), t14: t14.length, evidenceSufficiency: cross(classifications, (row) => row.evidenceSufficiency), patchScope: cross(classifications, (row) => row.patchScope), reasoningHorizon: cross(classifications, (row) => row.reasoningHorizon), audit: { audited: audited.length, disagreements: disagreements.length }, cleanup: { targetModelCalls: 0, modelProcessCount, computeProcesses, port8000Clear, ephemeralStateAbsent: ephemeralState.length === 0, worktrees: worktreeCount }, next: "SESSION_C_READY_SEPARATE_INVOCATION_REQUIRED" }, null, 2)}\n`);
