import { createHash, randomUUID } from "node:crypto";
import { link, lstat, mkdir, open, readFile, rm } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(process.cwd()), sealedAt = new Date().toISOString();
const sha256 = (value: string | Buffer) => createHash("sha256").update(value).digest("hex");
async function regular(relative: string) { const target = path.join(root, relative), stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Not regular: ${relative}`); return readFile(target); }
async function verified(relative: string, expected?: string) { const bytes = await regular(relative), digest = sha256(bytes), sidecar = await regular(`${relative}.sha256`); if (sidecar.toString("utf8") !== `${digest}  ${path.basename(relative)}\n` || (expected && digest !== expected)) throw new Error(`Artifact mismatch: ${relative}`); return { path: relative, sha256: digest, value: JSON.parse(bytes.toString("utf8")) as any }; }
async function publishBytes(relative: string, body: string) { const target = path.join(root, relative); await mkdir(path.dirname(target), { recursive: true }); try { const stat = await lstat(target); if (!stat.isFile() || stat.isSymbolicLink() || await readFile(target, "utf8") !== body) throw new Error(`Immutable collision: ${relative}`); return; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } const pending = `${target}.next.${process.pid}.${randomUUID()}`, handle = await open(pending, "wx", 0o600); try { await handle.writeFile(body); await handle.sync(); } finally { await handle.close(); } try { await link(pending, target); } finally { await rm(pending, { force: true }); } }
async function publish(relative: string, value: unknown) { const body = `${JSON.stringify(value, null, 2)}\n`, digest = sha256(body); await publishBytes(relative, body); await publishBytes(`${relative}.sha256`, `${digest}  ${path.basename(relative)}\n`); return { path: relative, sha256: digest }; }

const session = await verified("docs/experiments/model-specialization/BEST_7B_BOUNDED_RETRY_SESSION_C.v1.json", "09b95513e063377646f8cba52e34c181a53182f47380061e59af66707407f25a");
const validation = await verified("docs/experiments/model-specialization/BEST_7B_BOUNDED_RETRY_SESSION_C_VALIDATION.v1.json", "80b8bf3b089facadf47a3150c2c03e5d7274e6aa43df4dc8d90b94a6418b30d7");
const indexV1 = await verified("docs/experiments/model-specialization/BEST_7B_BOUNDED_RETRY_RESULTS_INDEX.v1.json", "d8f22c99a06fad23124fee561ae6bedf558d965a6aca10e9b0034adc3c2b402a");
const analysis = await verified("benchmarks/model-specialization/BEST_7B_BOUNDED_RETRY_ANALYSIS.v1.json", "607cc2fbe41f4e9fd6172d3c848d4f8a2f5c2a9457b746ffd96c8a7b564c6549");
if (session.value.status !== "PASS" || session.value.modelCalls !== 0 || validation.value.status !== "PASS" || analysis.value.analysis.maximumTwoCall.successes !== 30 || analysis.value.analysis.retryRecovery.recovered !== 1) throw new Error("Session-C completion prerequisites invalid");

const review = {
  schemaVersion: 1, reviewId: "dca-best-7b-bounded-retry-session-c-dual-axis-review-v1", status: "PASS", reviewedAt: sealedAt,
  skill: { skill_id: "D07", skill_version: "0.2.0", run_id: randomUUID(), status: "PASS", input_artifact_hashes: [session.sha256, validation.sha256, analysis.sha256], evidence_ids: [analysis.value.analysisId, session.value.sessionId], warnings: [], errors: [], metrics: { specBlockers: 0, standardsBlockers: 0 } },
  specReview: { status: "PASS", findings: [], evidence: { sealedSessionBHashVerified: true, oneShotAndRetryDerivedFromRows: true, completeTransitionMatrix: true, frozenThresholdsUnchanged: true, exactlyOneNextProtocol: true, nextProtocolExecuted: false, SessionCModelCalls: 0 }, acceptanceCriteria: { maximumTwoCall: "PASS_30_OF_95", recovery: "PASS_1_OF_66", classRecovery: "PASS_COMPLETE", migration: "PASS_COMPLETE_66_OF_66", cost: "PASS_ALL_95_DENOMINATOR", retryDecision: "PASS_RETRY_NO_MATERIAL_GAIN", productDecision: "PASS_KEEP_MUTATION_DISABLED", finalQuestions: "PASS_10_OF_10" } },
  standardsReview: { status: "PASS", findings: [], evidence: { strictTypeScript: "PASS", projectTypecheck: "PASS", completeTests: "PASS", productionBuild: "PASS", designValidation: "PASS", securityRegression: "PASS_1540_OF_1540", immutableSidecars: "PASS", appendOnlySupersession: true, sourceClosure: "PASS", privacy: "PASS_HASH_AND_BOUNDED_METADATA", protectedActions: "PASS_ALL_FALSE", runtimeCleanup: "PASS_NO_MODEL_COMPUTE_PROCESS_PORT_CLEAR_STATE_ABSENT_ONE_WORKTREE" } },
  decision: "APPROVED", modelCalls: 0,
};
const reviewRef = await publish("docs/experiments/model-specialization/BEST_7B_BOUNDED_RETRY_SESSION_C_REVIEW.v1.json", review);
const indexV2 = { ...indexV1.value, schemaVersion: 2, indexId: "dca-best-7b-bounded-retry-results-index-v2", generatedAt: sealedAt, supersedes: { path: indexV1.path, sha256: indexV1.sha256, reason: "Append-only binding of the finalized Session-C record and independent dual-axis review; scientific results unchanged", modelCallsAdded: 0 }, sessions: { ...indexV1.value.sessions, C: { path: session.path, sha256: session.sha256 } }, artifacts: { ...indexV1.value.artifacts, validation: { path: validation.path, sha256: validation.sha256 }, dualAxisReview: reviewRef }, accounting: { ...indexV1.value.accounting, SessionCModelCalls: 0 }, completion: { sessionC: "PASS", validation: "PASS", dualAxisReview: "PASS", nextExperimentExecuted: false } };
const indexV2Ref = await publish("docs/experiments/model-specialization/BEST_7B_BOUNDED_RETRY_RESULTS_INDEX.v2.json", indexV2);
const sourcePath = "scripts/seal_best_7b_bounded_retry_session_c_completion.ts", sourceBytes = await regular(sourcePath);
const supplement = { schemaVersion: 1, supplementId: "dca-best-7b-bounded-retry-session-c-completion-supplement-v1", status: "PASS_COMPLETE", sealedAt, inputs: { sessionC: { path: session.path, sha256: session.sha256 }, validation: { path: validation.path, sha256: validation.sha256 }, priorIndex: { path: indexV1.path, sha256: indexV1.sha256 } }, outputs: { canonicalResultsIndex: indexV2Ref, dualAxisReview: reviewRef }, reason: "Resolve the intentional no-forward-reference publication order without mutating the sealed v1 Session-C record or v1 index.", source: { path: sourcePath, sha256: sha256(sourceBytes) }, decisionsUnchanged: true, modelCalls: 0, protectedActions: { modelCall: false, modelDownload: false, retry: false, commit: false, remote: false, push: false, pullRequest: false, tag: false, release: false, signing: false } };
const supplementRef = await publish("docs/experiments/model-specialization/BEST_7B_BOUNDED_RETRY_SESSION_C_COMPLETION_SUPPLEMENT.v1.json", supplement);
process.stdout.write(`${JSON.stringify({ status: supplement.status, canonicalResultsIndex: indexV2Ref, review: reviewRef, supplement: supplementRef, modelCalls: 0 }, null, 2)}\n`);
